import json, sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

kps = []

# 239: High spinal and total spinal anesthesia
kps += [
  {"id":"high-spinal-d1","topic":"High spinal and total spinal anesthesia","domain":"Regional anesthesia, neuraxial techniques & peripheral nerve blocks","discipline":"anesthesia","stem":"What is the most common cause of apnea following a 'high' spinal anesthetic?","answer":"Hypotension and resulting brain ischemia, NOT phrenic nerve or intercostal nerve paralysis per se. Local anesthetic-induced respiratory center depression is also possible but less common.","rationale":"High spinal causes sympathetic blockade with profound hypotension; cerebral hypoperfusion from hypotension causes apnea, making aggressive blood pressure support the priority.","bloom":"analyze","source":[{"book":"Morgan & Mikhail","page":431}],"confusable_with":"phrenic nerve blockade causing diaphragmatic paralysis"},
  {"id":"high-spinal-d2","topic":"High spinal and total spinal anesthesia","domain":"Regional anesthesia, neuraxial techniques & peripheral nerve blocks","discipline":"anesthesia","stem":"What is the immediate management of hypotension following high spinal anesthesia?","answer":"Head-down position (autotransfusion), IV fluid bolus (5-10 mL/kg if cardiac/renal function permits), atropine for bradycardia, vasopressors (phenylephrine or ephedrine).","rationale":"Sympathetic blockade eliminates vasomotor tone; positional autotransfusion increases venous return; direct alpha-agonists (phenylephrine) rapidly restore vascular tone.","bloom":"apply","source":[{"book":"Morgan & Mikhail","page":1556}],"confusable_with":"anaphylaxis management"},
  {"id":"high-spinal-d3","topic":"High spinal and total spinal anesthesia","domain":"Regional anesthesia, neuraxial techniques & peripheral nerve blocks","discipline":"anesthesia","stem":"Phenylephrine 50-100 mcg IV boluses are used for hypotension from spinal anesthesia; what is the mechanism and a key limitation?","answer":"Phenylephrine is a direct alpha-1 agonist causing vasoconstriction; duration is short (~15 min), and tachyphylaxis may develop with infusions requiring upward dose titration.","rationale":"Phenylephrine increases SVR without direct cardiac effects; it is preferred over ephedrine in obstetric spinal hypotension as it does not cause fetal acidosis.","bloom":"apply","source":[{"book":"Morgan & Mikhail","page":390}],"confusable_with":"ephedrine (indirect sympathomimetic, causes fetal acidosis)"},
  {"id":"high-spinal-d4","topic":"High spinal and total spinal anesthesia","domain":"Regional anesthesia, neuraxial techniques & peripheral nerve blocks","discipline":"anesthesia","stem":"The majority of regional anesthesia malpractice claims involve which two techniques?","answer":"Lumbar epidural anesthesia (42%) and spinal anesthesia (34%); obstetric patients are most commonly affected.","rationale":"The high frequency of these claims reflects their widespread use in obstetrics; common claims include nerve injury, brain damage, and death from high/total spinals.","bloom":"recall","source":[{"book":"Morgan & Mikhail","page":1596}],"confusable_with":"peripheral nerve blocks"},
  {"id":"high-spinal-d5","topic":"High spinal and total spinal anesthesia","domain":"Regional anesthesia, neuraxial techniques & peripheral nerve blocks","discipline":"anesthesia","stem":"A 'high spinal' causing total spinal anesthesia at cervical levels produces what specific respiratory sequelae beyond hypotension?","answer":"Intercostal and phrenic nerve paralysis causing diaphragmatic weakness/paralysis; combined with hypotension-induced brainstem ischemia causing loss of medullary respiratory drive and apnea.","rationale":"C3-C5 phrenic nerve roots are blocked at high cervical levels, eliminating diaphragmatic ventilation; combined with brainstem hypoperfusion, respiratory arrest follows.","bloom":"analyze","source":[{"book":"Morgan & Mikhail","page":431}],"confusable_with":"LAST (local anesthetic systemic toxicity)"},
  {"id":"high-spinal-d6","topic":"High spinal and total spinal anesthesia","domain":"Regional anesthesia, neuraxial techniques & peripheral nerve blocks","discipline":"anesthesia","stem":"In patients with high spinal cord transection requiring anesthesia, why is succinylcholine relatively safe in the acute phase?","answer":"Succinylcholine can be used safely in the acute phase of spinal cord injury (within first 24-48 hours before denervation upregulates extrajunctional receptors) without risk of hyperkalemic cardiac arrest.","rationale":"Extrajunctional acetylcholine receptor upregulation occurs 3 days to 6 months post-injury; early administration avoids the hyperkalemic risk that develops later.","bloom":"apply","source":[{"book":"Morgan & Mikhail","page":1013}],"confusable_with":"use of succinylcholine after denervation (contraindicated after 3 days)"},
  {"id":"high-spinal-d7","topic":"High spinal and total spinal anesthesia","domain":"Regional anesthesia, neuraxial techniques & peripheral nerve blocks","discipline":"anesthesia","stem":"Excessive (exaggerated) spread of spinal anesthetic can occur due to what patient-related factors?","answer":"Factors include pregnancy, obesity, shorter stature, increased abdominal pressure (ascites), and use of hyperbaric solution in head-down position; these reduce CSF volume or alter baricity.","rationale":"Reduced CSF volume from venous engorgement or technical positioning increases cephalad spread of hyperbaric solutions; recognizing risk factors allows dose reduction.","bloom":"analyze","source":[{"book":"Morgan & Mikhail","page":1596}],"confusable_with":"epidural LA overdose"}
]

# 240: HCM Anesthetic Management
kps += [
  {"id":"hcm-anesthesia-d1","topic":"Hypertrophic Cardiomyopathy (HCM) - Anesthetic Management","domain":"Cardiothoracic & vascular anesthesia","discipline":"anesthesia","stem":"Why does HCM cause LVOT obstruction that worsens with sympathetic stimulation?","answer":"Asymmetric septal hypertrophy + systolic anterior motion (SAM) of mitral valve creates dynamic LVOT obstruction that increases with higher contractility, faster heart rate, reduced preload, and reduced afterload.","rationale":"Sympathetic stimulation increases contractility and heart rate while reducing LV volume, all of which narrow the outflow tract and increase pressure gradient.","bloom":"analyze","source":[{"book":"Miller/Baby Miller","page":493}],"confusable_with":"aortic stenosis (fixed obstruction)"},
  {"id":"hcm-anesthesia-d2","topic":"Hypertrophic Cardiomyopathy (HCM) - Anesthetic Management","domain":"Cardiothoracic & vascular anesthesia","discipline":"anesthesia","stem":"What are the four hemodynamic goals for anesthetic management of HCM?","answer":"(1) Avoid tachycardia (impairs filling, increases obstruction); (2) maintain or increase preload (full LV reduces obstruction); (3) increase afterload/SVR (reduces SAM and obstruction gradient); (4) avoid increased contractility.","rationale":"Each hemodynamic goal counteracts the dynamic obstruction mechanism; phenylephrine is preferred vasopressor as it increases SVR without increasing contractility or heart rate.","bloom":"apply","source":[{"book":"Morgan & Mikhail","page":660}],"confusable_with":"HF management goals (increase HR, decrease afterload)"},
  {"id":"hcm-anesthesia-d3","topic":"Hypertrophic Cardiomyopathy (HCM) - Anesthetic Management","domain":"Cardiothoracic & vascular anesthesia","discipline":"anesthesia","stem":"Why is the anesthetic management of HCM opposite to that of systolic heart failure?","answer":"Systolic HF is treated by reducing afterload, increasing heart rate, and sometimes increasing contractility; HCM requires increased afterload, reduced heart rate, and reduced contractility to minimize LVOT obstruction.","rationale":"HCM dynamic obstruction worsens with the very interventions (vasodilation, tachycardia, inotropes) used to treat systolic HF, making misidentification potentially catastrophic.","bloom":"analyze","source":[{"book":"Morgan & Mikhail","page":660}],"confusable_with":"dilated cardiomyopathy management"},
  {"id":"hcm-anesthesia-d4","topic":"Hypertrophic Cardiomyopathy (HCM) - Anesthetic Management","domain":"Cardiothoracic & vascular anesthesia","discipline":"anesthesia","stem":"Catheter-based management of obstructive HCM includes which interventional option?","answer":"Alcohol septal ablation (ASA) - injection of ethanol into the first septal perforator artery to create a controlled myocardial infarction, reducing septal hypertrophy and LVOT gradient.","rationale":"Alcohol ablation creates localized septal infarction, thinning the septal bulge that causes SAM and LVOT obstruction, with results similar to surgical myectomy.","bloom":"recall","source":[{"book":"StatPearls: StatPearls   Hypertrophic Cardiomyopathy (HCM)","page":2}],"confusable_with":"surgical myectomy (open-heart alternative)"},
  {"id":"hcm-anesthesia-d5","topic":"Hypertrophic Cardiomyopathy (HCM) - Anesthetic Management","domain":"Cardiothoracic & vascular anesthesia","discipline":"anesthesia","stem":"HCM is a common cause of sudden cardiac death especially in which population?","answer":"HCM is a leading cause of sudden cardiac death especially in young adults, including athletes, despite many remaining asymptomatic for decades.","rationale":"Dynamic LVOT obstruction combined with diastolic dysfunction and arrhythmia susceptibility creates risk for sudden VF; sports-related adrenergic surges are a common trigger.","bloom":"recall","source":[{"book":"Miller/Baby Miller","page":494}],"confusable_with":"ARVC (another cause of SCD in young athletes)"},
  {"id":"hcm-anesthesia-d6","topic":"Hypertrophic Cardiomyopathy (HCM) - Anesthetic Management","domain":"Cardiothoracic & vascular anesthesia","discipline":"anesthesia","stem":"Which vasopressor is preferred for treating hypotension in HCM during anesthesia, and why?","answer":"Phenylephrine (pure alpha-1 agonist) is preferred as it increases SVR and afterload without increasing contractility or heart rate, all of which would worsen LVOT obstruction.","rationale":"Ephedrine and dopamine have beta-1 effects that increase contractility and heart rate, worsening dynamic outflow obstruction; phenylephrine has none of these effects.","bloom":"apply","source":[{"book":"Morgan & Mikhail","page":660}],"confusable_with":"ephedrine (contraindicated in HCM)"},
  {"_type":"illness_script","topic":"Hypertrophic Cardiomyopathy (HCM) - Anesthetic Management","discipline":"anesthesia","enabling_conditions":"Young adults (often asymptomatic); family history SCD; obstructive form: systolic murmur that increases with Valsalva/standing; septal hypertrophy on echo","pathophysiology":"Asymmetric septal hypertrophy + SAM of mitral valve causes dynamic LVOT obstruction; diastolic dysfunction impairs filling; arrhythmias from disorganized myofiber architecture","time_course":"Often presents acutely as SCD or exercise intolerance in young athletes; can remain asymptomatic decades","key_features":"Dynamic LVOT gradient worsens with decreased preload/afterload, tachycardia, increased contractility; murmur increases with Valsalva; syncopal episodes","consequence_if_missed":"Hemodynamic collapse from inadvertent vasodilation/tachycardia; SCD from VF; refractory obstruction if vasoactive drugs given inappropriately"},
  {"_type":"confusable_pair","topic_a":"HCM anesthetic management","topic_b":"Systolic HF (dilated cardiomyopathy) anesthetic management","discriminator":"HCM requires increased afterload, maintained preload, low heart rate, and reduced contractility; systolic HF requires reduced afterload, adequate preload, normal-to-higher heart rate, and improved contractility. Giving a vasodilator or inotrope to an HCM patient worsens obstruction and can cause hemodynamic collapse."}
]

# 241: IONM Anesthetic Optimization (thin chunks - mostly general content)
kps += [
  {"id":"ionm-optimization-d1","topic":"IONM: Anesthetic Optimization & Alert Response","domain":"Neuroanesthesia & neuromonitoring","discipline":"anesthesia","stem":"What minimum MAC of volatile inhalation agent is recommended to prevent awareness and facilitate IONM interpretation?","answer":"At least 0.5-0.7 MAC of inhalation agent; an alarm for low anesthetic gas concentration should be set to prevent awareness during IONM cases requiring reduced volatile agent.","rationale":"IONM requires minimizing volatile agents (which suppress evoked potentials), but reducing below 0.5 MAC risks intraoperative awareness; balance is achieved with TIVA or multimodal techniques.","bloom":"apply","source":[{"book":"Morgan & Mikhail","page":204}],"confusable_with":"awareness prevention without IONM (different thresholds)"},
  {"id":"ionm-optimization-d2","topic":"IONM: Anesthetic Optimization & Alert Response","domain":"Neuroanesthesia & neuromonitoring","discipline":"anesthesia","stem":"Monitored anesthesia care (MAC) includes what specific components and how does it differ from general anesthesia?","answer":"MAC uses pharmacologic sedation (opioids, hypnotics) titrated along the ASA depth-of-sedation continuum; does not include intubation or paralysis; patient maintains protective reflexes at moderate sedation levels.","rationale":"MAC allows varying degrees of sedation and analgesia while preserving spontaneous ventilation and airway reflexes, appropriate for minor procedures or procedures requiring patient cooperation.","bloom":"apply","source":[{"book":"Miller/Baby Miller","page":251}],"confusable_with":"general anesthesia"},
  {"id":"ionm-optimization-d3","topic":"IONM: Anesthetic Optimization & Alert Response","domain":"Neuroanesthesia & neuromonitoring","discipline":"anesthesia","stem":"When intraoperative neurophysiological monitoring shows an alert, what is the standard first response of the anesthesiologist?","answer":"Ensure no anesthetic cause of signal change: check MAC/depth of anesthesia, rule out recent bolus of volatile agent or neuromuscular blocking agent, check temperature and hemodynamics, then communicate alert to surgeon.","rationale":"Anesthetic agents are a common technical cause of IONM alerts; ruling these out before attributing changes to surgical injury prevents unnecessary intervention.","bloom":"apply","source":[{"book":"Morgan & Mikhail","page":204}],"confusable_with":"immediately attributing alert to surgical injury"},
  {"id":"ionm-optimization-d4","topic":"IONM: Anesthetic Optimization & Alert Response","domain":"Neuroanesthesia & neuromonitoring","discipline":"anesthesia","stem":"Naltrexone is used for what purpose in contrast to naloxone, and why is the distinction clinically relevant?","answer":"Naltrexone is an oral opioid antagonist used for maintenance treatment of addiction; unlike naloxone (short half-life), naltrexone has significantly longer duration, which matters perioperatively as it blocks opioid analgesia.","rationale":"Patients on naltrexone who require surgery need it discontinued at least 72 hours before surgery, or higher opioid doses may be needed; failure to recognize this causes inadequate perioperative analgesia.","bloom":"apply","source":[{"book":"Morgan & Mikhail","page":466}],"confusable_with":"naloxone (IV, short-acting reversal agent)"},
  {"id":"ionm-optimization-d5","topic":"IONM: Anesthetic Optimization & Alert Response","domain":"Neuroanesthesia & neuromonitoring","discipline":"anesthesia","stem":"Total intravenous anesthesia (TIVA) is preferred over volatile agents when performing IONM for what reason?","answer":"Volatile agents dose-dependently suppress cortical evoked potentials (MEPs, SSEPs); TIVA (propofol + opioid) causes less signal suppression, making IONM alerts more specific for neural compromise.","rationale":"At equipotent doses, volatile agents produce greater evoked potential suppression than propofol; TIVA allows stable baseline signals against which surgical-related changes can be detected.","bloom":"analyze","source":[{"book":"Morgan & Mikhail","page":204}],"confusable_with":"TIVA for awareness prevention only"}
]

# 242: ICDs Anesthetic Management
kps += [
  {"id":"icd-anesthesia-d1","topic":"Implantable Cardioverter-Defibrillators (ICDs) - Anesthetic Management","domain":"Cardiothoracic & vascular anesthesia","discipline":"anesthesia","stem":"What ASA document governs perioperative management of patients with cardiac implantable electronic devices (CIEDs)?","answer":"The ASA Practice Advisory for the Perioperative Management of Patients with Cardiac Implantable Electronic Devices (pacemakers and ICDs) governs pre, intra, and postoperative CIED management.","rationale":"Specialized advisory exists because electromagnetic interference from electrosurgery can inhibit pacemakers or inappropriately activate ICDs; standardized protocols reduce these risks.","bloom":"recall","source":[{"book":"Morgan & Mikhail","page":1537}],"confusable_with":"general cardiac arrest protocols"},
  {"id":"icd-anesthesia-d2","topic":"Implantable Cardioverter-Defibrillators (ICDs) - Anesthetic Management","domain":"Cardiothoracic & vascular anesthesia","discipline":"anesthesia","stem":"What is the primary concern with ICDs during noncardiac surgery involving electrocautery?","answer":"Electrosurgical interference can be interpreted by the ICD as VF/VT, triggering inappropriate shocks; ICDs should be reprogrammed or deactivated with a magnet for the procedure.","rationale":"Monopolar electrocautery creates electromagnetic interference in the ICD sensing frequency range; inappropriate shocks are painful, can cause burns at lead tips, and may trigger malignant arrhythmias.","bloom":"apply","source":[{"book":"Morgan & Mikhail","page":657}],"confusable_with":"pacemaker inhibition (different mechanism, same interference)"},
  {"id":"icd-anesthesia-d3","topic":"Implantable Cardioverter-Defibrillators (ICDs) - Anesthetic Management","domain":"Cardiothoracic & vascular anesthesia","discipline":"anesthesia","stem":"Anesthetic management for ICD placement and EP procedures depends on what patient-specific factors?","answer":"Depends on underlying conditions including ejection fraction, presence of cardiomyopathy, arrhythmia type, hemodynamic stability, and concurrent medications (antiarrhythmics affecting defibrillation threshold).","rationale":"ICD placement requires testing device function with induced VF; patients with severely reduced EF or hemodynamic instability require careful anesthetic tailoring.","bloom":"analyze","source":[{"book":"Morgan & Mikhail","page":657}],"confusable_with":"routine device battery change"},
  {"id":"icd-anesthesia-d4","topic":"Implantable Cardioverter-Defibrillators (ICDs) - Anesthetic Management","domain":"Cardiothoracic & vascular anesthesia","discipline":"anesthesia","stem":"Magnesium sulfate is useful for torsades de pointes (TdP) associated with long QT syndrome; what other intervention is helpful for pause-dependent TdP?","answer":"Pacing at a rate that eliminates the pauses (rate >80 bpm) can suppress pause-dependent TdP; isoproterenol infusion increases heart rate and also reduces pauses.","rationale":"Pause-dependent TdP occurs when QT prolongs excessively during bradycardia or post-ectopic pauses; eliminating the pause removes the trigger for TdP initiation.","bloom":"apply","source":[{"book":"Morgan & Mikhail","page":657}],"confusable_with":"adrenergic-dependent TdP (beta-blockers preferred)"},
  {"id":"icd-anesthesia-d5","topic":"Implantable Cardioverter-Defibrillators (ICDs) - Anesthetic Management","domain":"Cardiothoracic & vascular anesthesia","discipline":"anesthesia","stem":"Cardiac resynchronization therapy (CRT) combined with an ICD in patients with severe cardiomyopathy - what preoperative assessment is essential?","answer":"Evaluate baseline pacing dependency (especially important if ICD magnet will inhibit ICD), hemodynamic status (EF often < 35%), medication review (antiarrhythmics), and device programming status; contact device clinic or cardiology for programming recommendations.","rationale":"CRT-D patients are often pacemaker-dependent with severely reduced EF; inappropriate device inhibition can cause hemodynamic collapse.","bloom":"apply","source":[{"book":"Morgan & Mikhail","page":1522}],"confusable_with":"standard pacemaker evaluation"}
]

# 243: Inhaled anesthetic mechanisms & MAC
kps += [
  {"id":"inhaled-anesthetic-mac-d1","topic":"Inhaled anesthetic mechanisms & MAC","domain":"Pharmacology, drug interactions & toxicology","discipline":"anesthesia","stem":"MAC-awake, MAC (immobility), and MAC-BAR represent what distinct anesthetic endpoints?","answer":"MAC-awake: concentration preventing voluntary response to verbal command in 50% (0.3-0.4 x MAC); MAC (standard): prevents purposeful movement to surgical incision in 50%; MAC-BAR: blunts autonomic response in 50% (1.3-1.4 x MAC).","rationale":"These endpoints represent different neural targets (consciousness, spinal reflex, autonomic response); MAC-amnesia likely falls below MAC-awake, meaning recall is prevented before consciousness is lost.","bloom":"recall","source":[{"book":"Miller/Baby Miller","page":114}],"confusable_with":"ED50 vs ED95"},
  {"id":"inhaled-anesthetic-mac-d2","topic":"Inhaled anesthetic mechanisms & MAC","domain":"Pharmacology, drug interactions & toxicology","discipline":"anesthesia","stem":"Nitrous oxide and xenon are believed to produce anesthesia primarily through what receptor mechanism?","answer":"N2O and xenon primarily inhibit NMDA (N-methyl-D-aspartate) receptors; this differs mechanistically from halogenated agents which enhance GABA-A receptor function.","rationale":"Diverse anesthetic agents produce anesthesia through different molecular targets; this heterogeneity argues against a single unifying mechanism and guides rational combination of agents.","bloom":"recall","source":[{"book":"Morgan & Mikhail","page":249}],"confusable_with":"halogenated agents (GABA-A potentiation)"},
  {"id":"inhaled-anesthetic-mac-d3","topic":"Inhaled anesthetic mechanisms & MAC","domain":"Pharmacology, drug interactions & toxicology","discipline":"anesthesia","stem":"MAC decreases progressively during pregnancy; at term, by approximately what percentage?","answer":"MAC decreases by approximately 40% at term for all general anesthetic agents; it returns to normal by the third day after delivery.","rationale":"Progesterone and beta-endorphin elevation during pregnancy modulates CNS sensitivity; this reduced MAC requires dose adjustment to prevent both over- and under-dosing.","bloom":"recall","source":[{"book":"Morgan & Mikhail","page":1355}],"confusable_with":"neuraxial LA dose reduction in pregnancy (also reduced, different mechanism)"},
  {"id":"inhaled-anesthetic-mac-d4","topic":"Inhaled anesthetic mechanisms & MAC","domain":"Pharmacology, drug interactions & toxicology","discipline":"anesthesia","stem":"In pediatric patients, why does alveolar anesthetic concentration rise more rapidly than in adults?","answer":"Infants have a higher minute ventilation-to-FRC ratio; combined with relatively greater blood-gas solubility and higher cardiac output directing blood to vessel-rich organs, alveolar concentration rises faster.","rationale":"Rapid induction in pediatric patients means careful titration is needed to avoid overdose; high MAC requirement combined with fast kinetics requires simultaneous dose increase.","bloom":"analyze","source":[{"book":"Morgan & Mikhail","page":1443}],"confusable_with":"adult inhalational induction kinetics"},
  {"id":"inhaled-anesthetic-mac-d5","topic":"Inhaled anesthetic mechanisms & MAC","domain":"Pharmacology, drug interactions & toxicology","discipline":"anesthesia","stem":"Inhaled anesthetics have been shown to have immunosuppressive effects - what clinical implication does this have?","answer":"Immunosuppression may be desirable in inflammatory conditions (e.g., lung inflammation) but potentially deleterious in cancer surgery, where immune function matters for tumor surveillance.","rationale":"Volatile agent-induced suppression of NK cell activity and cytokine signaling raises concerns about cancer recurrence after surgery; TIVA may be preferred for oncologic cases.","bloom":"analyze","source":[{"book":"Morgan & Mikhail","page":253}],"confusable_with":"sterile anti-inflammatory benefit"},
  {"id":"inhaled-anesthetic-mac-d6","topic":"Inhaled anesthetic mechanisms & MAC","domain":"Pharmacology, drug interactions & toxicology","discipline":"anesthesia","stem":"The principal pharmacodynamic change associated with aging that affects inhalational agents is what?","answer":"Reduced MAC with aging: older adult patients require less volatile agent to achieve equivalent anesthetic depth due to reduced CNS neurotransmitter activity and receptor sensitivity.","rationale":"MAC decreases approximately 6% per decade after age 40; failure to reduce doses in elderly patients leads to cardiovascular depression and delayed emergence.","bloom":"recall","source":[{"book":"Morgan & Mikhail","page":1490}],"confusable_with":"pharmacokinetic changes in elderly (also important but different)"}
]

print(f"Batch 3 KPs: {len(kps)}")
with open('data/kp_part7_batch3.json', 'w', encoding='utf-8') as f:
    json.dump(kps, f, ensure_ascii=False, indent=2)
print("Saved batch 3")
