#!/usr/bin/env python3
"""Build KP catalog part 1, items 19-34 — appended to interim file."""
import json, sys, io, re
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

def slug(topic):
    s = topic.lower()
    s = re.sub(r'[^a-z0-9]+', '-', s)
    return s.strip('-')

with open('data/kp_catalog_part1_interim.json', 'r', encoding='utf-8') as f:
    catalog = json.load(f)

print(f"Loaded {len(catalog)} entries from interim file.")

# ─── ITEM 19: Approach to Syncope and Near-Syncope ───────────────────────
T19 = "Approach to Syncope and Near-Syncope"
D19 = "Internal medicine: on-call & cross-cover (approach to the acutely changing ward patient)"
DI19 = "medicine"
S19 = slug(T19)
catalog += [
  {"id":f"{S19}-1","topic":T19,"domain":D19,"discipline":DI19,
   "stem":"What is the physiologic definition of syncope?",
   "answer":"Syncope is a transient loss of consciousness and postural tone with spontaneous recovery, resulting from decreased cerebral perfusion.",
   "rationale":"All causes of syncope share a final common pathway of global cerebral hypoperfusion; identifying the mechanism guides workup.",
   "bloom":"recall",
   "source":[{"book":"StatPearls: StatPearls   Syncope  Evaluation and Management","page":1}],
   "confusable_with":"Seizure (no post-ictal period in syncope; no posture loss in seizure)"},
  {"id":f"{S19}-2","topic":T19,"domain":D19,"discipline":DI19,
   "stem":"What is the minimum workup recommended for older adults presenting to the emergency department with syncope?",
   "answer":"ECG and blood glucose at minimum; routine blood work including hemoglobin and electrolytes; continuous cardiac monitoring and echocardiography if cardiovascular cause suspected.",
   "rationale":"ECG screens for dangerous arrhythmias; glucose excludes hypoglycemia; electrolytes identify metabolic causes.",
   "bloom":"recall",
   "source":[{"book":"StatPearls: StatPearls   Syncope  Evaluation and Management","page":4}],
   "confusable_with":""},
  {"id":f"{S19}-3","topic":T19,"domain":D19,"discipline":DI19,
   "stem":"A patient with severe aortic stenosis presents with exertional syncope. What other two symptoms comprise the classic late-stage AS triad?",
   "answer":"Classic AS triad: heart failure, angina, and syncope.",
   "rationale":"Each component of the triad carries significant mortality; syncope in AS suggests inadequate cardiac output reserve and indicates severe disease.",
   "bloom":"recall",
   "source":[{"book":"Morgan & Mikhail","page":674}],
   "confusable_with":""},
  {"id":f"{S19}-4","topic":T19,"domain":D19,"discipline":DI19,
   "stem":"If a cerebrovascular cause of syncope is suspected, what diagnostic modalities are indicated?",
   "answer":"Head CT, carotid Doppler ultrasound, or brain MRI with or without angiography; EEG if seizure is suspected.",
   "rationale":"Vertebrobasilar TIA can cause syncope; carotid disease can reduce cerebral perfusion; differentiating from seizure requires EEG.",
   "bloom":"recall",
   "source":[{"book":"StatPearls: StatPearls   Syncope  Evaluation and Management","page":4}],
   "confusable_with":""},
  {"id":f"{S19}-5","topic":T19,"domain":D19,"discipline":DI19,
   "stem":"When is a tilt table test indicated in the evaluation of syncope?",
   "answer":"Tilt table test is indicated when vasovagal or orthostatic syncope is suspected but unconfirmed by history and physical examination.",
   "rationale":"Tilt table testing reproduces the orthostatic/neurocardiogenic trigger under monitored conditions to confirm the mechanism.",
   "bloom":"recall",
   "source":[{"book":"StatPearls: StatPearls   Syncope  Evaluation and Management","page":4}],
   "confusable_with":""},
  {"id":f"{S19}-6","topic":T19,"domain":D19,"discipline":DI19,
   "stem":"For a patient discharged from the ED after syncope who is suspected to have a conduction abnormality, what outpatient monitoring device is recommended?",
   "answer":"A cardiac event monitor (external loop recorder) to detect intermittent arrhythmias.",
   "rationale":"Paroxysmal arrhythmias are often missed on a single ECG; prolonged event monitoring captures intermittent bradyarrhythmias or tachyarrhythmias causing syncope.",
   "bloom":"recall",
   "source":[{"book":"StatPearls: StatPearls   Syncope  Evaluation and Management","page":4}],
   "confusable_with":""},
  {"_type":"confusable_pair","topic_a":"Syncope","topic_b":"Seizure","discriminator":"Syncope: brief LOC, rapid return to baseline, no post-ictal confusion, preceded by prodrome; seizure: tonic-clonic activity, post-ictal confusion, possible tongue bite/incontinence"},
]

# ─── ITEM 20: Approach to Tachycardia ────────────────────────────────────
T20 = "Approach to Tachycardia"
D20 = "Internal medicine: on-call & cross-cover (approach to the acutely changing ward patient)"
DI20 = "medicine"
S20 = slug(T20)
catalog += [
  {"id":f"{S20}-1","topic":T20,"domain":D20,"discipline":DI20,
   "stem":"A patient has a heart rate of 140. What is the first assessment that determines management pathway?",
   "answer":"Assess hemodynamic stability: if unstable (hypotension, altered mental status, chest pain, signs of shock) → immediate synchronized cardioversion; if stable → evaluate ECG-based algorithm.",
   "rationale":"Hemodynamic instability mandates immediate cardioversion regardless of rhythm type; stable patients allow time for rhythm diagnosis.",
   "bloom":"apply",
   "source":[{"book":"StatPearls: StatPearls   ACLS  Non Shockable Rhythms (PEA & Asystole)","page":15}],
   "confusable_with":""},
  {"id":f"{S20}-2","topic":T20,"domain":D20,"discipline":DI20,
   "stem":"In the ECG-based approach to tachycardia, what does QRS duration tell you about the origin of the rhythm?",
   "answer":"Normal QRS (≤0.12 s) = supraventricular origin; wide QRS (>0.12 s) = ventricular tachycardia OR SVT with aberrant conduction.",
   "rationale":"The AV conduction system is used in supraventricular rhythms, producing narrow QRS; ventricular rhythms bypass this system.",
   "bloom":"recall",
   "source":[{"book":"Marino ICU Book","page":250}],
   "confusable_with":"SVT with aberrancy vs VT"},
  {"id":f"{S20}-3","topic":T20,"domain":D20,"discipline":DI20,
   "stem":"Sinus tachycardia is most importantly treated by addressing the underlying cause. What are the key reversible causes to exclude first?",
   "answer":"Hypovolemia, hemorrhage, fever/infection, pain, hypoxemia, PE, anemia, tamponade, aortic dissection, hyperthyroidism, EtOH/BZD/opioid/BB withdrawal.",
   "rationale":"Sinus tachycardia is a compensatory mechanism; treating the rhythm without addressing the cause may be harmful.",
   "bloom":"apply",
   "source":[{"book":"MGH Housestaff Manual","page":11}],
   "confusable_with":""},
  {"id":f"{S20}-4","topic":T20,"domain":D20,"discipline":DI20,
   "stem":"Classic digoxin toxicity manifests as which specific rhythm?",
   "answer":"Atrial tachycardia with variable AV block is the classic digoxin toxicity rhythm.",
   "rationale":"Digoxin enhances automaticity at atrial foci while slowing AV conduction, producing the characteristic AT with variable AVB pattern.",
   "bloom":"recall",
   "source":[{"book":"MGH Housestaff Manual","page":11}],
   "confusable_with":"Atrial flutter with variable block"},
  {"id":f"{S20}-5","topic":T20,"domain":D20,"discipline":DI20,
   "stem":"In pediatric tachycardia, fast heart rates may specifically impair which cardiac function?",
   "answer":"Fast rates impair ventricular filling (reduced diastolic filling time), decreasing cardiac output.",
   "rationale":"Cardiac output = SV × HR; beyond a critical rate, SV falls faster than HR rises due to inadequate filling time.",
   "bloom":"apply",
   "source":[{"book":"Morgan & Mikhail","page":761}],
   "confusable_with":""},
  {"id":f"{S20}-6","topic":T20,"domain":D20,"discipline":DI20,
   "stem":"Junctional tachycardia is due to increased automaticity within which structure?",
   "answer":"The AV node (or reentrant rhythms involving it); junctional tachycardia arises from increased automaticity within the AV node.",
   "rationale":"Junctional foci fire faster than the SA node during ischemia, digoxin toxicity, or post-cardiac surgery, overriding sinus rhythm.",
   "bloom":"recall",
   "source":[{"book":"MGH Housestaff Manual","page":11}],
   "confusable_with":""},
  {"_type":"confusable_pair","topic_a":"SVT with aberrant conduction","topic_b":"Ventricular tachycardia","discriminator":"Both have wide QRS; VT: AV dissociation, fusion/capture beats, extreme axis, no response to vagal maneuvers; SVT with aberrancy: responds to adenosine"},
]

# ─── ITEM 21: Approach to the Unresponsive Patient ───────────────────────
T21 = "Approach to the Unresponsive Patient"
D21 = "Internal medicine: on-call & cross-cover (approach to the acutely changing ward patient)"
DI21 = "medicine"
S21 = slug(T21)
catalog += [
  {"id":f"{S21}-1","topic":T21,"domain":D21,"discipline":DI21,
   "stem":"A ward patient is found unresponsive. Following the 2010 ACLS guideline change, which element of BLS now takes priority over airway management?",
   "answer":"Circulation (chest compressions) is now prioritized before Airway-Breathing; the 2010 change was based on evidence that early high-quality CPR improves survival over early airway management.",
   "rationale":"Delayed chest compressions waiting for airway establishment worsens outcomes; early circulation maintains coronary and cerebral perfusion.",
   "bloom":"recall",
   "source":[{"book":"StatPearls: StatPearls   ACLS  Non Shockable Rhythms (PEA & Asystole)","page":6}],
   "confusable_with":"Old A-B-C approach"},
  {"id":f"{S21}-2","topic":T21,"domain":D21,"discipline":DI21,
   "stem":"What are the metrics for high-quality CPR in an unresponsive patient?",
   "answer":"Compression rate 100–120/min, depth ≥2 inches, allow full chest recoil, minimize interruptions, avoid excessive ventilation.",
   "rationale":"Each parameter independently improves coronary perfusion pressure and the likelihood of ROSC.",
   "bloom":"recall",
   "source":[{"book":"StatPearls: StatPearls   ACLS  Non Shockable Rhythms (PEA & Asystole)","page":6}],
   "confusable_with":""},
  {"id":f"{S21}-3","topic":T21,"domain":D21,"discipline":DI21,
   "stem":"In an unresponsive patient with suspected hypothermia, why must aggressive rewarming precede termination of resuscitation?",
   "answer":"Hypothermia lowers metabolic rate and provides cerebral protection; 'no one is dead until they are warm and dead' — complete rewarming to ≥32°C before declaring futility.",
   "rationale":"Cold temperatures cause muscle rigidity and loss of cardiac output but are reversible; premature termination risks missing a survivable cause.",
   "bloom":"apply",
   "source":[{"book":"StatPearls: StatPearls   Hypothermia","page":6}],
   "confusable_with":""},
  {"id":f"{S21}-4","topic":T21,"domain":D21,"discipline":DI21,
   "stem":"For an unresponsive patient where difficult mask ventilation is anticipated (BMI>30, beard, Mallampati III-IV), what is the priority before any airway maneuver?",
   "answer":"Assemble backup airway equipment and personnel before induction; if ≥3 predictors of difficult mask ventilation are present, consider awake intubation.",
   "rationale":"Patients do not die from inability to intubate—they die from inability to oxygenate; a backup plan with skilled assistance prevents 'can't intubate, can't oxygenate' disaster.",
   "bloom":"apply",
   "source":[{"book":"Stanford CA-1","page":43}],
   "confusable_with":""},
  {"id":f"{S21}-5","topic":T21,"domain":D21,"discipline":DI21,
   "stem":"In an unresponsive post-surgical patient, what pheochromocytoma-related diagnosis should be considered if there is a history of paroxysmal hypertension and the classic triad?",
   "answer":"Pheochromocytoma or paraganglioma: paroxysmal headache, tachycardia, diaphoresis; catecholamine crisis can precipitate cardiovascular collapse causing unresponsiveness.",
   "rationale":"Unrecognized pheo can cause hypertensive crisis with hemorrhagic stroke or catecholamine cardiomyopathy causing cardiac arrest.",
   "bloom":"analyze",
   "source":[{"book":"Miller/Baby Miller","page":551}],
   "confusable_with":""},
  {"id":f"{S21}-6","topic":T21,"domain":D21,"discipline":DI21,
   "stem":"In a prone-positioned hospital patient who becomes unresponsive, what CPR adaptation is described in current guidelines?",
   "answer":"Prone-position CPR techniques may be used in hospital settings when the patient cannot be immediately repositioned supine.",
   "rationale":"Supine positioning is preferred for CPR but is sometimes not immediately achievable (e.g., prone spine surgery); prone CPR provides some circulation during repositioning.",
   "bloom":"recall",
   "source":[{"book":"StatPearls: StatPearls   ACLS  Non Shockable Rhythms (PEA & Asystole)","page":6}],
   "confusable_with":""},
]

# ─── ITEM 22: Approach to Acute Abdominal Pain ───────────────────────────
T22 = "Approach to Acute Abdominal Pain"
D22 = "Internal medicine: on-call & cross-cover (approach to the acutely changing ward patient)"
DI22 = "medicine"
S22 = slug(T22)
catalog += [
  {"id":f"{S22}-1","topic":T22,"domain":D22,"discipline":DI22,
   "stem":"A patient with acute abdominal pain has a completely negative imaging workup. Which categories of 'image-negative' causes must still be considered?",
   "answer":"Metabolic: DKA, hypercalcemia, uremia, acute intermittent porphyria; medications/toxins: EtOH, opioid withdrawal, cocaine; functional: IBS; extra-abdominal: acute MI, VZV, angioedema.",
   "rationale":"Image-negative abdominal pain represents a broad diagnostic category; missing MI or DKA in abdominal pain presentation is a high-stakes error.",
   "bloom":"apply",
   "source":[{"book":"MGH Housestaff Manual","page":72}],
   "confusable_with":""},
  {"id":f"{S22}-2","topic":T22,"domain":D22,"discipline":DI22,
   "stem":"In a trauma patient with blunt abdominal injury, what mechanism should you always suspect to evolve into a life-threatening complication?",
   "answer":"Tension pneumothorax: pulmonary injury from blunt or penetrating trauma can evolve into tension PTX when mechanical ventilation is initiated.",
   "rationale":"Positive pressure ventilation converts a simple pneumothorax into a tension pneumothorax; high index of suspicion is warranted in ventilated trauma patients.",
   "bloom":"apply",
   "source":[{"book":"Morgan & Mikhail","page":1319}],
   "confusable_with":""},
  {"id":f"{S22}-3","topic":T22,"domain":D22,"discipline":DI22,
   "stem":"What are the key history elements in evaluating acute abdominal pain?",
   "answer":"Location, chronicity, quality, radiation, associated symptoms (nausea/vomiting, fever, change in bowel/urinary habits), relation to eating, relevant medications, last menstrual period.",
   "rationale":"Pain character and location guide the differential: RUQ → biliary/hepatic; RLQ → appendicitis; epigastric → pancreatic/gastric/cardiac.",
   "bloom":"recall",
   "source":[{"book":"MGH Housestaff Manual","page":72}],
   "confusable_with":""},
  {"id":f"{S22}-4","topic":T22,"domain":D22,"discipline":DI22,
   "stem":"NSAIDs used for abdominal pain may precipitate which three serious complications?",
   "answer":"Gastrointestinal bleeding, kidney toxicity (acute kidney injury), and platelet dysfunction.",
   "rationale":"NSAIDs inhibit prostaglandins protecting GI mucosa and maintaining renal perfusion; both effects are particularly dangerous in high-risk patients.",
   "bloom":"recall",
   "source":[{"book":"Morgan & Mikhail","page":1306}],
   "confusable_with":""},
  {"id":f"{S22}-5","topic":T22,"domain":D22,"discipline":DI22,
   "stem":"A patient with acute abdominal pain has episodic, colicky pain that resolves on its own—what diagnosis category does this suggest?",
   "answer":"Episodic/colicky pain suggests: passed kidney stone, sphincter of Oddi dysfunction, biliary colic; these are discrete events without persistent pathology.",
   "rationale":"Colicky (crescendo-decrescendo) pain reflects smooth muscle spasm; intermittent resolution suggests obstruction that transiently clears.",
   "bloom":"apply",
   "source":[{"book":"MGH Housestaff Manual","page":72}],
   "confusable_with":""},
  {"id":f"{S22}-6","topic":T22,"domain":D22,"discipline":DI22,
   "stem":"In the analgesic management of acute abdominal pain, what is the appropriate role of opioids according to stepwise pain management?",
   "answer":"For moderate to severe pain uncontrolled by non-opioids/adjuvants, opioids are appropriate; use the lowest effective dose with reassessment.",
   "rationale":"The WHO stepwise ladder applies: non-opioids first, then weak opioids, then strong opioids; adequate analgesia does not mask diagnosis and is humane.",
   "bloom":"apply",
   "source":[{"book":"MGH Housestaff Manual","page":164}],
   "confusable_with":""},
]

# ─── ITEM 23: Approach to Acute Agitation ────────────────────────────────
T23 = "Approach to Acute Agitation"
D23 = "Internal medicine: on-call & cross-cover (approach to the acutely changing ward patient)"
DI23 = "medicine"
S23 = slug(T23)
catalog += [
  {"id":f"{S23}-1","topic":T23,"domain":D23,"discipline":DI23,
   "stem":"What are the three primary goals of agitation management?",
   "answer":"(1) Safety of patient and staff; (2) help the patient manage distress (promote calm, not simply sedate/punish); (3) avoid restraints as able.",
   "rationale":"Restraints worsen agitation in many patients and carry risks of injury; de-escalation and treating underlying causes are always preferred first.",
   "bloom":"recall",
   "source":[{"book":"MGH Housestaff Manual","page":206}],
   "confusable_with":""},
  {"id":f"{S23}-2","topic":T23,"domain":D23,"discipline":DI23,
   "stem":"In the stepwise bedside approach to the acutely agitated patient, what three assessments are performed after confirming no immediate threat to life?",
   "answer":"Step 2: assess pain (query patient, assess for noxious stimuli); Step 3: assess anxiety; Step 4: assess delirium and other medical causes.",
   "rationale":"Pain and anxiety are the most common treatable precipitants of acute agitation in hospital; addressing them first often resolves the episode without pharmacology.",
   "bloom":"recall",
   "source":[{"book":"Marino ICU Book","page":683}],
   "confusable_with":""},
  {"id":f"{S23}-3","topic":T23,"domain":D23,"discipline":DI23,
   "stem":"Early warning signs of escalating agitation that nurses and PCAs should be taught to recognize and report promptly include what behaviors?",
   "answer":"Anger/fear, yelling, pacing/restlessness, sweating, and aggressive body language.",
   "rationale":"Early recognition allows non-pharmacologic de-escalation before the patient becomes physically threatening, reducing injury risk for both staff and patient.",
   "bloom":"recall",
   "source":[{"book":"MGH Housestaff Manual","page":206}],
   "confusable_with":""},
  {"id":f"{S23}-4","topic":T23,"domain":D23,"discipline":DI23,
   "stem":"A non-verbal patient with ASD or neurocognitive disorder is increasingly agitated. Which common physical discomforts should be checked first?",
   "answer":"Urinary retention and constipation: these frequently cause unrecognized discomfort in non-verbal patients and can precipitate acute behavioral changes.",
   "rationale":"Non-verbal patients cannot express discomfort; retention and constipation are reversible physical triggers that dramatically improve when treated.",
   "bloom":"apply",
   "source":[{"book":"MGH Housestaff Manual","page":206}],
   "confusable_with":""},
  {"id":f"{S23}-5","topic":T23,"domain":D23,"discipline":DI23,
   "stem":"If restraints are required for an acutely agitated patient, what accompanying intervention is mandatory?",
   "answer":"Patients who require restraints should always receive medication to ease distress and reduce the time spent in restraints.",
   "rationale":"Restraints alone worsen distress and agitation; concurrent pharmacologic treatment reduces duration of restraint and prevents injury.",
   "bloom":"apply",
   "source":[{"book":"MGH Housestaff Manual","page":206}],
   "confusable_with":""},
  {"id":f"{S23}-6","topic":T23,"domain":D23,"discipline":DI23,
   "stem":"The Ramsay sedation scale has how many levels of sedation versus agitation, and what is the implication for monitoring oversedation?",
   "answer":"Ramsay scale: 4 levels of sedation (scores 3–6), only 1 level of agitation (score 1); it is well-suited for detecting oversedation but less detailed for agitation severity.",
   "rationale":"Oversedation in the ICU leads to prolonged ventilation and delirium; routine sedation monitoring using the Ramsay scale reduces these risks.",
   "bloom":"recall",
   "source":[{"book":"Marino ICU Book","page":683}],
   "confusable_with":"RASS (Richmond Agitation-Sedation Scale, more granular for agitation)"},
]

# ─── ITEM 24: Approach to Acute Kidney Injury ────────────────────────────
T24 = "Approach to Acute Kidney Injury"
D24 = "Internal medicine: on-call & cross-cover (approach to the acutely changing ward patient)"
DI24 = "medicine"
S24 = slug(T24)
catalog += [
  {"id":f"{S24}-1","topic":T24,"domain":D24,"discipline":DI24,
   "stem":"What is the KDIGO definition of AKI?",
   "answer":"AKI: increase in serum creatinine ≥0.3 mg/dL within 48 hours, OR ≥1.5× baseline within 7 days, OR urine output <0.5 mL/kg/h for ≥6 hours.",
   "rationale":"KDIGO criteria standardize AKI diagnosis; any single criterion is sufficient; recognition at early stages improves outcomes.",
   "bloom":"recall",
   "source":[{"book":"Society Guideline: Guideline   KDIGO 2012 AKI","page":22}],
   "confusable_with":""},
  {"id":f"{S24}-2","topic":T24,"domain":D24,"discipline":DI24,
   "stem":"What are the three etiologic categories of AKI, and which should be corrected first?",
   "answer":"Prerenal (hypoperfusion), intrinsic renal (tubular/glomerular/interstitial), and postrenal (obstruction); correct prerenal causes (optimize volume and cardiac output) first.",
   "rationale":"Prerenal AKI is the most common and most reversible; correcting hypovolemia or cardiac output restores renal perfusion before structural damage occurs.",
   "bloom":"apply",
   "source":[{"book":"Morgan & Mikhail","page":1106}],
   "confusable_with":""},
  {"id":f"{S24}-3","topic":T24,"domain":D24,"discipline":DI24,
   "stem":"What is the optimal initial approach to evaluation and treatment of acute oliguria?",
   "answer":"Correct any existing hypovolemia and optimize cardiac output and kidney perfusion first before attributing oliguria to intrinsic renal disease.",
   "rationale":"Most in-hospital oliguria is prerenal; fluid resuscitation and optimization of hemodynamics often restores urine output without need for further workup.",
   "bloom":"apply",
   "source":[{"book":"Morgan & Mikhail","page":1079}],
   "confusable_with":""},
  {"id":f"{S24}-4","topic":T24,"domain":D24,"discipline":DI24,
   "stem":"Is there evidence that mannitol prevents AKI or converts oliguric to non-oliguric renal failure?",
   "answer":"No: there is no clinical evidence that mannitol provides kidney protection, lessens AKI severity, or reduces morbidity/mortality compared to volume correction alone.",
   "rationale":"Despite widespread historic use, mannitol has not proven renoprotective in clinical trials; the key intervention is correcting hypovolemia.",
   "bloom":"recall",
   "source":[{"book":"Morgan & Mikhail","page":1079}],
   "confusable_with":""},
  {"id":f"{S24}-5","topic":T24,"domain":D24,"discipline":DI24,
   "stem":"Oliguria is defined as urine output <0.5 mL/kg/h. What does this reflect about glomerular filtration rate?",
   "answer":"Oliguria at <0.5 mL/kg/h reflects reabsorption of >99.5% of the glomerular filtrate, indicating profound stimulation of tubular reabsorption (consistent with decreased GFR).",
   "rationale":"Normal GFR ~125 mL/min produces ~107 mL/kg/h filtrate; oliguria means almost all is being reabsorbed, signaling inadequate perfusion.",
   "bloom":"analyze",
   "source":[{"book":"Society Guideline: Guideline   KDIGO 2012 AKI","page":38}],
   "confusable_with":""},
  {"id":f"{S24}-6","topic":T24,"domain":D24,"discipline":DI24,
   "stem":"In critically ill patients, what glucose target does KDIGO recommend to minimize AKI-related adverse outcomes?",
   "answer":"KDIGO suggests insulin therapy targeting plasma glucose 110–149 mg/dL in critically ill patients.",
   "rationale":"Tight glycemic control (80–110) worsens outcomes due to hypoglycemia; permissive glucose targets balance hyperglycemia harm vs hypoglycemia risk.",
   "bloom":"recall",
   "source":[{"book":"Society Guideline: Guideline   KDIGO 2012 AKI","page":46}],
   "confusable_with":""},
]

# ─── ITEM 25: Approach to Acute Rash ─────────────────────────────────────
T25 = "Approach to Acute Rash"
D25 = "Internal medicine: on-call & cross-cover (approach to the acutely changing ward patient)"
DI25 = "medicine"
S25 = slug(T25)
# Chunks for item 25 are mostly off-topic (ILD, COPD, abdominal pain). The most relevant chunks:
# MGH p.130 (tickborne diseases with fever/rash), MGH p.154 (HSCT infectious complications with rash context)
catalog += [
  {"id":f"{S25}-1","topic":T25,"domain":D25,"discipline":DI25,
   "stem":"A febrile patient returns from camping with a rash, myalgias, and thrombocytopenia. What approach guides workup for tickborne illness?",
   "answer":"Obtain history of outdoor/hiking activity in late spring to early autumn; 50–80% will NOT recall a tick bite. Send diagnostic tests (tick panel, babesia smear) and start empiric doxycycline early if clinical suspicion is high.",
   "rationale":"Empiric treatment before test results is indicated in tickborne illness due to high morbidity from delay; doxycycline covers Rocky Mountain Spotted Fever and Lyme.",
   "bloom":"apply",
   "source":[{"book":"MGH Housestaff Manual","page":130}],
   "confusable_with":""},
  {"id":f"{S25}-2","topic":T25,"domain":D25,"discipline":DI25,
   "stem":"In a patient with a new acute rash, what features indicate a potentially serious skin and soft tissue infection requiring urgent surgical evaluation?",
   "answer":"Rapidly spreading erythema, systemic toxicity (fever, hypotension, tachycardia), pain disproportionate to appearance, crepitus/gas on imaging—these suggest necrotizing fasciitis.",
   "rationale":"Necrotizing fasciitis progresses rapidly; surgical debridement is life-saving and must not be delayed waiting for antibiotics alone to work.",
   "bloom":"analyze",
   "source":[{"book":"Society Guideline: Guideline   IDSA 2014 SSTI","page":30}],
   "confusable_with":"Cellulitis"},
  {"id":f"{S25}-3","topic":T25,"domain":D25,"discipline":DI25,
   "stem":"Sarcoidosis can present with a characteristic rash. What is the Lofgren syndrome triad?",
   "answer":"Lofgren syndrome (high specificity for sarcoidosis): hilar adenopathy + erythema nodosum + arthritis.",
   "rationale":"Lofgren syndrome is a benign, acute form of sarcoidosis with high diagnostic specificity; biopsy may be avoided if the triad is present.",
   "bloom":"recall",
   "source":[{"book":"MGH Housestaff Manual","page":178}],
   "confusable_with":""},
  {"id":f"{S25}-4","topic":T25,"domain":D25,"discipline":DI25,
   "stem":"In evaluating a skin infection in an immunocompromised host where standard empiric treatment may be inadequate, what early step is recommended?",
   "answer":"Early skin biopsy by an experienced dermatologist or surgeon to identify the etiologic agent; microbial resistance makes dogmatic empiric regimens dangerous in this population.",
   "rationale":"Immunocompromised patients are at risk from unusual organisms (fungi, atypical bacteria); tissue diagnosis guides targeted therapy.",
   "bloom":"apply",
   "source":[{"book":"Society Guideline: Guideline   IDSA 2014 SSTI","page":30}],
   "confusable_with":""},
  {"id":f"{S25}-5","topic":T25,"domain":D25,"discipline":DI25,
   "stem":"A rash in a post-HSCT patient in the first 30 days is most likely from which categories of infection?",
   "answer":"Day 0–30 post-HSCT: GPCs and GNRs (bacterial, neutropenic fever); viral (HSV, CMV reactivation); fungal (Candida, Aspergillus).",
   "rationale":"HSCT immune reconstitution follows a predictable timeline; early infections are dominated by bacterial and fungal pathogens during neutropenia.",
   "bloom":"recall",
   "source":[{"book":"MGH Housestaff Manual","page":154}],
   "confusable_with":""},
  {"id":f"{S25}-6","topic":T25,"domain":D25,"discipline":DI25,
   "stem":"Impetigo and ecthyma are skin infections addressed by which management principle per IDSA guidelines?",
   "answer":"Topical or systemic antibiotics targeting Staphylococcus aureus and Streptococcus pyogenes; MRSA-active agents for resistant cases.",
   "rationale":"IDSA SSTI guidelines standardize management based on severity and organism; distinguishing impetigo (superficial) from ecthyma (deeper ulceration) guides depth of treatment.",
   "bloom":"recall",
   "source":[{"book":"Society Guideline: Guideline   IDSA 2014 SSTI","page":11}],
   "confusable_with":""},
]

# ─── ITEM 26: Approach to Acute Urinary Retention ────────────────────────
T26 = "Approach to Acute Urinary Retention"
D26 = "Internal medicine: on-call & cross-cover (approach to the acutely changing ward patient)"
DI26 = "medicine"
S26 = slug(T26)
# Chunks mostly off-topic. Relevant: MGH p.72 (AUR as cause of agitation), MGH p.206 (AUR in non-verbal),
# Morgan p.1106 (postrenal AKI from obstruction)
catalog += [
  {"id":f"{S26}-1","topic":T26,"domain":D26,"discipline":DI26,
   "stem":"What is the immediate treatment for acute urinary retention?",
   "answer":"Urethral catheterization for immediate bladder decompression; if urethral catheterization fails, suprapubic catheter placement.",
   "rationale":"AUR causes pain and progressive bladder damage; catheterization provides immediate relief and prevents bladder ischemia from over-distension.",
   "bloom":"recall",
   "source":[{"book":"MGH Housestaff Manual","page":206}],
   "confusable_with":""},
  {"id":f"{S26}-2","topic":T26,"domain":D26,"discipline":DI26,
   "stem":"Acute urinary retention that is not promptly relieved can cause which type of kidney injury?",
   "answer":"Postrenal AKI: bilateral urinary tract obstruction causes back-pressure azotemia; relief of obstruction usually reverses renal dysfunction.",
   "rationale":"Obstructed urine cannot drain; elevated hydrostatic pressure reduces GFR and, if prolonged, causes tubular damage.",
   "bloom":"apply",
   "source":[{"book":"Morgan & Mikhail","page":1106}],
   "confusable_with":"Intrinsic renal AKI"},
  {"id":f"{S26}-3","topic":T26,"domain":D26,"discipline":DI26,
   "stem":"In a non-verbal or cognitively impaired patient who becomes acutely agitated postoperatively, what diagnosis must be quickly excluded?",
   "answer":"Acute urinary retention: a common but easily missed cause of agitation in non-verbal patients who cannot express the urge to urinate.",
   "rationale":"Palpation of a distended bladder or bladder ultrasound confirms the diagnosis; catheterization provides immediate resolution of both retention and agitation.",
   "bloom":"apply",
   "source":[{"book":"MGH Housestaff Manual","page":206}],
   "confusable_with":"Delirium"},
  {"id":f"{S26}-4","topic":T26,"domain":D26,"discipline":DI26,
   "stem":"Which two epidural anesthesia complications can directly cause urinary retention in the immediate postoperative period?",
   "answer":"Epidural/spinal anesthesia blocks sacral parasympathetic outflow (S2–S4), inhibiting detrusor contraction and causing urinary retention.",
   "rationale":"Sacral nerve blockade from neuraxial anesthesia prevents bladder contraction; retention is anticipated and catheterization is planned in appropriate cases.",
   "bloom":"apply",
   "source":[{"book":"Morgan & Mikhail","page":1106}],
   "confusable_with":""},
  {"id":f"{S26}-5","topic":T26,"domain":D26,"discipline":DI26,
   "stem":"Acute urinary retention can be precipitated by which medication class commonly used in the perioperative setting?",
   "answer":"Anticholinergics (e.g., atropine, glycopyrrolate, scopolamine) reduce bladder detrusor contraction and increase urethral resistance, precipitating AUR.",
   "rationale":"Anticholinergic medications block muscarinic M3 receptors in the bladder, relaxing the detrusor and causing retention especially in men with BPH.",
   "bloom":"recall",
   "source":[{"book":"MGH Housestaff Manual","page":72}],
   "confusable_with":""},
  {"id":f"{S26}-6","topic":T26,"domain":D26,"discipline":DI26,
   "stem":"In acute urinary retention from benign prostatic hyperplasia (BPH), what medication class is used for longer-term management after acute decompression?",
   "answer":"Alpha-1 blockers (e.g., tamsulosin) relax prostate smooth muscle, reducing outlet resistance; 5-alpha reductase inhibitors reduce prostate volume over months.",
   "rationale":"Both classes target different aspects of BPH; alpha blockers provide rapid symptom relief; 5-ARIs reduce prostate size to prevent recurrence.",
   "bloom":"recall",
   "source":[{"book":"MGH Housestaff Manual","page":206}],
   "confusable_with":""},
]

# ─── ITEM 27: Approach to Asymptomatic Hypertension ─────────────────────
T27 = "Approach to Asymptomatic Hypertension"
D27 = "Internal medicine: on-call & cross-cover (approach to the acutely changing ward patient)"
DI27 = "medicine"
S27 = slug(T27)
catalog += [
  {"id":f"{S27}-1","topic":T27,"domain":D27,"discipline":DI27,
   "stem":"A patient is found to have BP 165/95 on routine morning vital signs with no symptoms. What distinguishes this from a hypertensive emergency?",
   "answer":"Asymptomatic hypertension (no target organ damage): no need for emergency IV treatment; manage with oral agents and close follow-up. Emergency requires evidence of acute end-organ damage.",
   "rationale":"Most asymptomatic BP elevations in hospitalized patients represent undertreated chronic hypertension or pain/anxiety; aggressive acute lowering is unnecessary and potentially harmful.",
   "bloom":"apply",
   "source":[{"book":"StatPearls: StatPearls   Hypertensive Urgency and Emergency","page":1}],
   "confusable_with":"Hypertensive emergency"},
  {"id":f"{S27}-2","topic":T27,"domain":D27,"discipline":DI27,
   "stem":"Patients with chronic hypertension have atherosclerotic stenosis becoming symptomatic at what degree of coronary occlusion?",
   "answer":"Symptoms typically appear when stenotic lesions cause 50–75% occlusion; maximum compensatory dilation is present at 70% occlusion.",
   "rationale":"Chronic hypertension accelerates atherosclerosis; asymptomatic hypertension is the driver of silent coronary disease progression.",
   "bloom":"recall",
   "source":[{"book":"Morgan & Mikhail","page":636}],
   "confusable_with":""},
  {"id":f"{S27}-3","topic":T27,"domain":D27,"discipline":DI27,
   "stem":"The pheochromocytoma classic triad includes hypertension, tachycardia, and diaphoresis. In a patient with otherwise asymptomatic hypertension, when should pheo be considered?",
   "answer":"Consider pheo when hypertension is episodic/paroxysmal, associated with headache, palpitations, diaphoresis, or resistant to multiple antihypertensives.",
   "rationale":"Pheo should not be missed as it is a surgically curable cause of hypertension with potentially lethal catecholamine crises.",
   "bloom":"apply",
   "source":[{"book":"Miller/Baby Miller","page":551}],
   "confusable_with":""},
  {"id":f"{S27}-4","topic":T27,"domain":D27,"discipline":DI27,
   "stem":"In the perioperative medicine context, what is the role of a perioperative medicine consultant for a patient with asymptomatic hypertension undergoing elective surgery?",
   "answer":"Optimize modifiable risk factors preoperatively including BP control; ensure chronic antihypertensives are continued perioperatively; decide whether to delay surgery for better control.",
   "rationale":"Perioperative medicine spans preoperative assessment through recovery; BP optimization before elective surgery reduces intraoperative hemodynamic lability.",
   "bloom":"apply",
   "source":[{"book":"Miller/Baby Miller","page":778}],
   "confusable_with":""},
  {"id":f"{S27}-5","topic":T27,"domain":D27,"discipline":DI27,
   "stem":"CKD and hypertension have a bidirectional relationship. According to KDIGO CKD guidelines, what cardiac complication is addressed by coronary revascularization in this population?",
   "answer":"Coronary revascularization continues to have a key role in angina relief in CKD patients with stable ischemic heart disease, though patients with EF <35% or left main disease were excluded from definitive trials.",
   "rationale":"CKD patients have accelerated CAD; revascularization addresses the angina component while BP control addresses the underlying driver.",
   "bloom":"recall",
   "source":[{"book":"Society Guideline: Guideline   KDIGO 2024 CKD","page":125}],
   "confusable_with":""},
  {"id":f"{S27}-6","topic":T27,"domain":D27,"discipline":DI27,
   "stem":"Hypertensive urgency (no organ damage) is associated with what long-term risk that justifies follow-up rather than dismissal?",
   "answer":"Higher incidence of adverse cardiovascular events over the long term; warrants nuanced outpatient management and medication optimization.",
   "rationale":"Even without acute target organ damage, persistently elevated BP accelerates atherosclerosis and end-organ damage over time.",
   "bloom":"recall",
   "source":[{"book":"StatPearls: StatPearls   Hypertensive Urgency and Emergency","page":1}],
   "confusable_with":""},
]

# ─── ITEM 28: Approach to Capacity and the Refusing Patient ──────────────
T28 = "Approach to Capacity and the Refusing Patient"
D28 = "Internal medicine: on-call & cross-cover (approach to the acutely changing ward patient)"
DI28 = "medicine"
S28 = slug(T28)
# Chunks are mostly off-topic (cardiac risk assessment, COPD, airway). Use general principles present.
catalog += [
  {"id":f"{S28}-1","topic":T28,"domain":D28,"discipline":DI28,
   "stem":"What are the four components of decision-making capacity that must be assessed when a patient refuses treatment?",
   "answer":"(1) Understanding: comprehends information about condition and treatment; (2) Appreciation: recognizes how it applies to them; (3) Reasoning: can reason about options; (4) Communication: can express a consistent choice.",
   "rationale":"Capacity is decision-specific and can fluctuate; all four elements must be present for a legally valid refusal.",
   "bloom":"recall",
   "source":[{"book":"Miller/Baby Miller","page":778}],
   "confusable_with":"Competence (legal determination by court, not bedside assessment)"},
  {"id":f"{S28}-2","topic":T28,"domain":D28,"discipline":DI28,
   "stem":"A patient with COPD refuses recommended intubation. What must you document to support a valid refusal?",
   "answer":"Document that the patient demonstrates all four capacity elements; document the discussion of risks, benefits, and alternatives; ensure the refusal is voluntary and not from coercion.",
   "rationale":"A documented capacity assessment protects both the patient's autonomy and the clinician legally; an undocumented refusal creates medicolegal risk.",
   "bloom":"apply",
   "source":[{"book":"Morgan & Mikhail","page":859}],
   "confusable_with":""},
  {"id":f"{S28}-3","topic":T28,"domain":D28,"discipline":DI28,
   "stem":"In a patient with fluctuating consciousness (e.g., encephalopathy), when can their previously expressed refusal of treatment override acute intervention?",
   "answer":"A previously documented advance directive (e.g., POLST, living will) or legally appointed healthcare proxy can direct care when current capacity is absent.",
   "rationale":"Advance directives extend autonomous decision-making to times when the patient lacks capacity; clinicians must honor legally executed directives.",
   "bloom":"apply",
   "source":[{"book":"Miller/Baby Miller","page":785}],
   "confusable_with":""},
  {"id":f"{S28}-4","topic":T28,"domain":D28,"discipline":DI28,
   "stem":"If a patient lacks capacity and has no advance directive or surrogate, what ethical principle guides emergency treatment decisions?",
   "answer":"Best interest standard: clinician acts in the patient's best medical interest to preserve life and health until a surrogate or legal authority can be established.",
   "rationale":"Emergency exception doctrine allows treatment without consent to prevent serious harm when no authorized decision-maker is available.",
   "bloom":"recall",
   "source":[{"book":"Miller/Baby Miller","page":778}],
   "confusable_with":""},
  {"id":f"{S28}-5","topic":T28,"domain":D28,"discipline":DI28,
   "stem":"A patient with diabetes and recent hyperglycemia refuses insulin therapy. What reversible metabolic factor might impair their capacity?",
   "answer":"Severe hyperglycemia or hypoglycemia, electrolyte disturbances, uremia, or hepatic encephalopathy can transiently impair capacity; treating the metabolic cause may restore capacity.",
   "rationale":"Metabolic encephalopathy is a reversible cause of impaired capacity; treating the underlying condition first allows a valid subsequent consent process.",
   "bloom":"analyze",
   "source":[{"book":"Morgan & Mikhail","page":1491}],
   "confusable_with":""},
  {"id":f"{S28}-6","topic":T28,"domain":D28,"discipline":DI28,
   "stem":"In preoperative assessment, when does emergency surgery override the need for capacity assessment and informed consent?",
   "answer":"Emergency surgery (life-threatening condition requiring immediate intervention) proceeds under emergency exception; document urgency and inability to obtain consent.",
   "rationale":"Delay for formal consent in a true surgical emergency can cause irreversible harm; the emergency exception is a well-established ethical and legal doctrine.",
   "bloom":"recall",
   "source":[{"book":"Morgan & Mikhail","page":622}],
   "confusable_with":""},
]

# ─── ITEM 29: Approach to Constipation ───────────────────────────────────
T29 = "Approach to Constipation"
D29 = "Internal medicine: on-call & cross-cover (approach to the acutely changing ward patient)"
DI29 = "medicine"
S29 = slug(T29)
catalog += [
  {"id":f"{S29}-1","topic":T29,"domain":D29,"discipline":DI29,
   "stem":"What symptom criteria define constipation using the Rome IV framework?",
   "answer":"Dissatisfaction with defecation with ≥2 of: <3 BM/week, hard stools, straining, sensation of incomplete evacuation, sensation of anorectal blockage, or manual facilitation.",
   "rationale":"Rome IV criteria provide standardized diagnosis; clinical management targets the dominant symptom pattern.",
   "bloom":"recall",
   "source":[{"book":"MGH Housestaff Manual","page":78}],
   "confusable_with":""},
  {"id":f"{S29}-2","topic":T29,"domain":D29,"discipline":DI29,
   "stem":"What test is used to diagnose slow-transit constipation?",
   "answer":"Sitz-marker study showing delay in colonic transit; this distinguishes slow-transit constipation from dyssynergic defecation.",
   "rationale":"Radiopaque markers are ingested and followed radiographically; retention of >20% at 5 days indicates slow transit.",
   "bloom":"recall",
   "source":[{"book":"MGH Housestaff Manual","page":78}],
   "confusable_with":""},
  {"id":f"{S29}-3","topic":T29,"domain":D29,"discipline":DI29,
   "stem":"A patient on chronic opioids develops constipation. What type of constipation does this represent, and what is the appropriate treatment?",
   "answer":"Opioid-induced constipation (OIC) is a secondary/functional constipation; treat with peripherally acting mu-opioid receptor antagonists (PAMORAs, e.g., methylnaltrexone) or osmotic laxatives.",
   "rationale":"OIC results from mu-receptor activation in the GI tract; PAMORAs reverse this without affecting central analgesia.",
   "bloom":"apply",
   "source":[{"book":"MGH Housestaff Manual","page":78}],
   "confusable_with":""},
  {"id":f"{S29}-4","topic":T29,"domain":D29,"discipline":DI29,
   "stem":"Severe hypermagnesemia can cause what GI and neurological complications?",
   "answer":"Severe hypermagnesemia (>12 mg/dL): cardiovascular complications (hypotension, arrhythmias), neurological disorder (confusion, lethargy); paradoxically, magnesium is also used as a cathartic laxative at lower doses.",
   "rationale":"Magnesium's dual role (cathartic laxative vs cardiac/neurological toxin) depends on dose and renal function; accumulation in renal failure causes toxicity.",
   "bloom":"recall",
   "source":[{"book":"StatPearls: StatPearls   Hypermagnesemia  Causes and Management","page":6}],
   "confusable_with":""},
  {"id":f"{S29}-5","topic":T29,"domain":D29,"discipline":DI29,
   "stem":"Dyssynergic defecation is characterized by what pathophysiology?",
   "answer":"Dyssynergic defecation: impaired rectal evacuation from inadequate rectal propulsive forces OR increased resistance (failure to relax or inappropriate contraction of pelvic floor).",
   "rationale":"Normal defecation requires coordinated relaxation of puborectalis and external anal sphincter; dyssynergia means paradoxical contraction during straining.",
   "bloom":"recall",
   "source":[{"book":"MGH Housestaff Manual","page":78}],
   "confusable_with":""},
  {"id":f"{S29}-6","topic":T29,"domain":D29,"discipline":DI29,
   "stem":"Constipation and urinary retention often co-occur in hospitalized patients. What common ward patient population is at highest risk?",
   "answer":"Elderly, non-verbal patients with neurocognitive disorders, and post-operative patients on opioids and anticholinergics are at highest risk for both constipation and urinary retention.",
   "rationale":"Multiple factors converge: immobility, opioids, anticholinergics, dehydration, and impaired communication—proactive monitoring prevents complications.",
   "bloom":"apply",
   "source":[{"book":"MGH Housestaff Manual","page":206}],
   "confusable_with":""},
]

# ─── ITEM 30: Approach to Diarrhea ───────────────────────────────────────
T30 = "Approach to Diarrhea"
D30 = "Internal medicine: on-call & cross-cover (approach to the acutely changing ward patient)"
DI30 = "medicine"
S30 = slug(T30)
catalog += [
  {"id":f"{S30}-1","topic":T30,"domain":D30,"discipline":DI30,
   "stem":"When should C. difficile infection be considered as the cause of diarrhea in a hospitalized patient?",
   "answer":"Consider C. diff in patients with 3 or more loose stools with recent hospitalization, antibiotic use, or close contact with diarrheal individuals.",
   "rationale":"Hospitalization and antibiotics are the two strongest risk factors for CDI; early testing prevents spread and allows targeted treatment.",
   "bloom":"apply",
   "source":[{"book":"StatPearls: StatPearls   Clostridioides difficile Infection (CDI)","page":7}],
   "confusable_with":""},
  {"id":f"{S30}-2","topic":T30,"domain":D30,"discipline":DI30,
   "stem":"What is fulminant C. difficile colitis, and what are its defining features?",
   "answer":"Fulminant CDI: diarrhea + diffuse abdominal pain + abdominal distension + hypovolemia; may progress to toxic megacolon, bowel perforation, and peritonitis.",
   "rationale":"Fulminant CDI has high mortality requiring urgent surgical consultation, ICU admission, and IV vancomycin ± fidaxomicin.",
   "bloom":"recall",
   "source":[{"book":"StatPearls: StatPearls   Clostridioides difficile Infection (CDI)","page":7}],
   "confusable_with":""},
  {"id":f"{S30}-3","topic":T30,"domain":D30,"discipline":DI30,
   "stem":"Why are alcohol hand antiseptics NOT sufficient for C. difficile prevention, unlike standard hand hygiene?",
   "answer":"Alcohol-based antiseptics do not effectively eliminate C. difficile spores; soap-and-water handwashing is required to mechanically remove spores.",
   "rationale":"C. diff forms environmentally resistant spores; alcohol denatures proteins but does not disrupt spore coats.",
   "bloom":"recall",
   "source":[{"book":"StatPearls: StatPearls   Clostridioides difficile Infection (CDI)","page":11}],
   "confusable_with":""},
  {"id":f"{S30}-4","topic":T30,"domain":D30,"discipline":DI30,
   "stem":"Secretory diarrhea causes metabolic acidosis more frequently than inflammatory diarrhea. Why?",
   "answer":"Secretory diarrhea contains a higher concentration of HCO3, causing non-anion gap metabolic acidosis (NAGMA) from bicarbonate loss.",
   "rationale":"Intestinal secretions are bicarbonate-rich; secretory diarrhea (e.g., cholera, VIPoma) causes hyperchloremic NAGMA.",
   "bloom":"analyze",
   "source":[{"book":"StatPearls: StatPearls   Metabolic Acidosis  Approach and Anion Gap","page":5}],
   "confusable_with":""},
  {"id":f"{S30}-5","topic":T30,"domain":D30,"discipline":DI30,
   "stem":"What are the recurrence risk factors for C. difficile infection?",
   "answer":"Recurrence risk factors: recent hospitalization, recent antibiotic use, close contact with individuals who have had diarrhea.",
   "rationale":"Recurrent CDI requires treatment with fidaxomicin or bezlotoxumab prophylaxis; understanding risk factors guides preventive strategy.",
   "bloom":"recall",
   "source":[{"book":"StatPearls: StatPearls   Clostridioides difficile Infection (CDI)","page":7}],
   "confusable_with":""},
  {"id":f"{S30}-6","topic":T30,"domain":D30,"discipline":DI30,
   "stem":"A patient on enteral tube feeding develops new diarrhea. What approach is recommended when starting tube feeds to minimize GI complications?",
   "answer":"Start with full-strength formula at full rate; traditional dilute/slow ramp-up prolongs inadequate nutrition without GI benefit.",
   "rationale":"Studies show intragastric full feedings are well tolerated; the traditional slow ramp-up extends nutritional deficiency without reducing complication rates.",
   "bloom":"recall",
   "source":[{"book":"Marino ICU Book","page":604}],
   "confusable_with":""},
]

# ─── ITEM 31: Approach to Fever ──────────────────────────────────────────
T31 = "Approach to Fever"
D31 = "Internal medicine: on-call & cross-cover (approach to the acutely changing ward patient)"
DI31 = "medicine"
S31 = slug(T31)
catalog += [
  {"id":f"{S31}-1","topic":T31,"domain":D31,"discipline":DI31,
   "stem":"In a febrile patient with suspected sepsis, what must be obtained before starting antibiotics?",
   "answer":"Obtain adequate cultures first (blood x2, urine, wounds, sputum); additional studies based on history and exam (e.g., LP, thoracentesis, imaging) before empiric antibiotics.",
   "rationale":"Post-antibiotic cultures have dramatically reduced sensitivity; culture results are essential for de-escalation to targeted therapy.",
   "bloom":"apply",
   "source":[{"book":"Morgan & Mikhail","page":2155}],
   "confusable_with":""},
  {"id":f"{S31}-2","topic":T31,"domain":D31,"discipline":DI31,
   "stem":"After cardiac arrest with return of spontaneous circulation, what is the relationship between fever and neurological outcome?",
   "answer":"Fever is associated with worse neurological outcomes and neuronal damage from inflammatory changes and biochemical cascades following ischemia-reperfusion; goal is normothermia ≤37.5°C for ≥72 hours.",
   "rationale":"Post-cardiac arrest fever accelerates excitotoxic injury in the ischemic brain; targeted temperature management prevents this.",
   "bloom":"recall",
   "source":[{"book":"MGH Housestaff Manual","page":5}],
   "confusable_with":""},
  {"id":f"{S31}-3","topic":T31,"domain":D31,"discipline":DI31,
   "stem":"A patient develops fever with rash after a hike in May. They do not recall a tick bite. How should this affect your clinical approach?",
   "answer":"50–80% of patients with tickborne illness do not recall a tick bite; fever + rash + outdoor exposure in late spring/summer warrants empiric doxycycline even without a tick history.",
   "rationale":"Waiting for confirmed tick bite before treating causes dangerous delays; RMSF mortality increases sharply without early antibiotic therapy.",
   "bloom":"apply",
   "source":[{"book":"MGH Housestaff Manual","page":130}],
   "confusable_with":""},
  {"id":f"{S31}-4","topic":T31,"domain":D31,"discipline":DI31,
   "stem":"Fever in immunocompromised patients should be treated empirically targeting what organism categories?",
   "answer":"Empiric antibiotics should target pathogens associated with the specific immune defect (e.g., gram-negative bacilli in neutropenic fever, PCP in HIV).",
   "rationale":"Immune defects create predictable vulnerability; targeted empiric coverage improves outcomes compared to generic broad-spectrum regimens.",
   "bloom":"apply",
   "source":[{"book":"Morgan & Mikhail","page":2155}],
   "confusable_with":""},
  {"id":f"{S31}-5","topic":T31,"domain":D31,"discipline":DI31,
   "stem":"Treatment of bubonic plague includes which specific antibiotic regimen per IDSA guidelines?",
   "answer":"Streptomycin 15 mg/kg IM every 12 hours (first-line) or doxycycline 100 mg BID (alternative); gentamicin can substitute for streptomycin.",
   "rationale":"Bubonic plague requires specific antibiotic selection; doxycycline is widely available and effective for mild-moderate cases.",
   "bloom":"recall",
   "source":[{"book":"Society Guideline: Guideline   IDSA 2014 SSTI","page":9}],
   "confusable_with":""},
  {"id":f"{S31}-6","topic":T31,"domain":D31,"discipline":DI31,
   "stem":"In a post-cardiac arrest patient with fever, what three specific causes should be investigated given the pathophysiology?",
   "answer":"(1) Inflammatory response to global ischemia-reperfusion; (2) Infection (aspiration pneumonia, gut bacterial translocation from ischemia); (3) Drug fever.",
   "rationale":"Post-arrest fever has multiple causes; pan-culture and aggressive antibiotic treatment are indicated given the risk of infection from aspiration and gut ischemia.",
   "bloom":"recall",
   "source":[{"book":"MGH Housestaff Manual","page":5}],
   "confusable_with":""},
]

# ─── ITEM 32: Approach to Headache ───────────────────────────────────────
T32 = "Approach to Headache"
D32 = "Internal medicine: on-call & cross-cover (approach to the acutely changing ward patient)"
DI32 = "medicine"
S32 = slug(T32)
catalog += [
  {"id":f"{S32}-1","topic":T32,"domain":D32,"discipline":DI32,
   "stem":"What does the SNOOP4 mnemonic identify in headache evaluation, and what does each letter stand for?",
   "answer":"SNOOP4 identifies secondary (dangerous) headache: S=Systemic symptoms; N=Neurological deficits; O1=Older onset (>50 yr); O2=Onset sudden (thunderclap); P1=Papilledema; P2=Positional; P3=Valsalva/exertional; P4=Progressive pattern change.",
   "rationale":"Each SNOOP4 feature raises the probability of a secondary cause (SAH, CVST, mass lesion, meningitis) requiring urgent neuroimaging.",
   "bloom":"recall",
   "source":[{"book":"StatPearls: StatPearls   Headache  Primary Disorders","page":7}],
   "confusable_with":""},
  {"id":f"{S32}-2","topic":T32,"domain":D32,"discipline":DI32,
   "stem":"A patient develops a severe headache after a lumbar puncture. What is the mechanism of post-dural puncture headache (PDPH)?",
   "answer":"CSF leaks through the dural hole, reducing CSF pressure; postural decrease in hydrostatic driving pressure worsens the headache when upright.",
   "rationale":"Reduced CSF volume causes downward traction on pain-sensitive meningeal structures; supine positioning reduces this traction.",
   "bloom":"analyze",
   "source":[{"book":"Morgan & Mikhail","page":1600}],
   "confusable_with":""},
  {"id":f"{S32}-3","topic":T32,"domain":D32,"discipline":DI32,
   "stem":"What is the conservative treatment of post-dural puncture headache?",
   "answer":"Recumbent positioning (reduces hydrostatic CSF pressure at dural hole), analgesics (acetaminophen to opioids), IV/oral fluid hydration, and caffeine (stimulates CSF production + vasoconstriction).",
   "rationale":"Conservative measures work by reducing CSF egress and stimulating CSF production; epidural blood patch is definitive for refractory cases.",
   "bloom":"recall",
   "source":[{"book":"Morgan & Mikhail","page":1600}],
   "confusable_with":""},
  {"id":f"{S32}-4","topic":T32,"domain":D32,"discipline":DI32,
   "stem":"An alternative procedural approach to managing post-dural puncture headache (beyond blood patch) involves which nerve block?",
   "answer":"Sphenopalatine ganglion block has been suggested as an approach to treating dural puncture headache.",
   "rationale":"SPG block modulates parasympathetic input to cerebral vessels and dura mater; it provides an alternative for patients who decline or fail blood patch.",
   "bloom":"recall",
   "source":[{"book":"Morgan & Mikhail","page":1600}],
   "confusable_with":""},
  {"id":f"{S32}-5","topic":T32,"domain":D32,"discipline":DI32,
   "stem":"In a patient >50 years with new-onset headache, which secondary cause must be urgently excluded?",
   "answer":"New onset headache age >50 is a red flag for secondary headache (SNOOP4 'O1'); urgent evaluation for temporal arteritis (GCA), intracranial malignancy, and vascular causes is required.",
   "rationale":"Primary headache disorders typically begin in younger patients; new headache in the elderly has high probability of secondary etiology requiring specific workup.",
   "bloom":"apply",
   "source":[{"book":"StatPearls: StatPearls   Headache  Primary Disorders","page":7}],
   "confusable_with":""},
  {"id":f"{S32}-6","topic":T32,"domain":D32,"discipline":DI32,
   "stem":"Headache is a common symptom of arteriovenous malformations (AVMs). When are AVMs most likely to bleed?",
   "answer":"Bleeding from AVMs is most common between ages 10 and 30; other presentations include headache and seizures.",
   "rationale":"AVMs are congenital; the high-flow low-resistance circulation gradually weakens vessel walls until rupture, most commonly in young adults.",
   "bloom":"recall",
   "source":[{"book":"Morgan & Mikhail","page":989}],
   "confusable_with":""},
]

# ─── ITEM 33: Approach to Hematuria ──────────────────────────────────────
T33 = "Approach to Hematuria"
D33 = "Internal medicine: on-call & cross-cover (approach to the acutely changing ward patient)"
DI33 = "medicine"
S33 = slug(T33)
catalog += [
  {"id":f"{S33}-1","topic":T33,"domain":D33,"discipline":DI33,
   "stem":"What defines microscopic hematuria on urinalysis?",
   "answer":"Microhematuria: ≥3 RBCs per high-power field (HPF) on microscopic urinalysis; dipstick alone is insufficient and must be confirmed with microscopy.",
   "rationale":"Dipstick detects hemoglobin/myoglobin and can be falsely positive; microscopy confirms true RBCs and may reveal casts indicating glomerular disease.",
   "bloom":"recall",
   "source":[{"book":"StatPearls: StatPearls   Microscopic Colitis","page":2}],
   "confusable_with":""},
  {"id":f"{S33}-2","topic":T33,"domain":D33,"discipline":DI33,
   "stem":"In a 55-year-old male with gross hematuria and no other symptoms, what is the clinical risk classification and recommended workup?",
   "answer":"Gross hematuria automatically places patient in high-risk category; warrants imaging (CT urogram preferred for higher-risk patients) and cystoscopy to rule out urological malignancy.",
   "rationale":"Hematuria is a sentinel symptom for bladder and renal cancer; <20% of patients receive both imaging and cystoscopy despite being recommended.",
   "bloom":"apply",
   "source":[{"book":"StatPearls: StatPearls   Microscopic Colitis","page":7}],
   "confusable_with":""},
  {"id":f"{S33}-3","topic":T33,"domain":D33,"discipline":DI33,
   "stem":"Hematuria in women is frequently attributed to what causes, leading to diagnostic delays?",
   "answer":"UTI, menstrual contamination, or vaginal bleeding are often incorrectly assumed to explain hematuria in women; these assumptions contribute to delays in diagnosing malignancy.",
   "rationale":"Delayed diagnosis of bladder cancer is more common in women due to attribution bias; persistent hematuria despite UTI treatment requires full urological evaluation.",
   "bloom":"recall",
   "source":[{"book":"StatPearls: StatPearls   Microscopic Colitis","page":9}],
   "confusable_with":""},
  {"id":f"{S33}-4","topic":T33,"domain":D33,"discipline":DI33,
   "stem":"For a patient with microscopic hematuria who initially defers cystoscopy, what follow-up is recommended?",
   "answer":"Repeat microscopic urinalysis within 12 months; persistent microhematuria at 12 months warrants cystoscopic evaluation.",
   "rationale":"Deferring cystoscopy is acceptable with appropriate surveillance; persistent hematuria significantly raises the probability of significant pathology.",
   "bloom":"recall",
   "source":[{"book":"StatPearls: StatPearls   Microscopic Colitis","page":12}],
   "confusable_with":""},
  {"id":f"{S33}-5","topic":T33,"domain":D33,"discipline":DI33,
   "stem":"Nephrolithiasis as a cause of hematuria: what confirms the diagnosis and what symptom pattern is typical?",
   "answer":"Imaging (renal ultrasound, KUB X-ray, or CT abdomen) confirms calculi; presentation includes acute renal colic with severe flank pain, nausea/vomiting, and hematuria with urinary crystals.",
   "rationale":"Urinalysis crystals suggest stone type but are not diagnostic alone; CT is most sensitive for calculi.",
   "bloom":"recall",
   "source":[{"book":"StatPearls: StatPearls   Microscopic Colitis","page":10}],
   "confusable_with":""},
  {"id":f"{S33}-6","topic":T33,"domain":D33,"discipline":DI33,
   "stem":"In a child with hematuria following a respiratory infection, what immune-mediated glomerulonephritis should be considered?",
   "answer":"IgA vasculitis (Henoch-Schönlein purpura): immune-mediated glomerulonephritis occurring primarily in children <10, often following infection; involves GI tract and hematuria.",
   "rationale":"HSP/IgA vasculitis has a characteristic post-infectious onset with purpuric rash, arthritis, abdominal pain, and nephritis; most resolve spontaneously.",
   "bloom":"recall",
   "source":[{"book":"StatPearls: StatPearls   Microscopic Colitis","page":16}],
   "confusable_with":"IgA nephropathy (similar post-infectious hematuria but no systemic features)"},
]

# ─── ITEM 34: Approach to Hyperglycemia ──────────────────────────────────
T34 = "Approach to Hyperglycemia"
D34 = "Internal medicine: on-call & cross-cover (approach to the acutely changing ward patient)"
DI34 = "medicine"
S34 = slug(T34)
catalog += [
  {"id":f"{S34}-1","topic":T34,"domain":D34,"discipline":DI34,
   "stem":"In a critically ill ICU patient with hyperglycemia, what glucose target is recommended to balance glycemic control against hypoglycemia risk?",
   "answer":"Target glucose 140–180 mg/dL with insulin drips; avoid hypoglycemia (<100 mg/dL) which increases mortality from seizures, arrhythmias, and stroke.",
   "rationale":"NICE-SUGAR trial showed aggressive tight control (80–110 mg/dL) paradoxically worsened ICU outcomes due to hypoglycemic episodes.",
   "bloom":"recall",
   "source":[{"book":"Curated Units","page":0}],
   "confusable_with":"Tight glycemic control (80–110 mg/dL target, shown to worsen outcomes in NICE-SUGAR)"},
  {"id":f"{S34}-2","topic":T34,"domain":D34,"discipline":DI34,
   "stem":"In the ICU setting, what physiologic mechanism causes stress hyperglycemia in non-diabetic patients?",
   "answer":"Sepsis and critical illness cause cytokine-mediated insulin resistance, leading to hyperglycemia (>180 mg/dL) in up to 50% of non-diabetic patients.",
   "rationale":"Counter-regulatory hormones (cortisol, catecholamines, glucagon) and inflammatory cytokines impair insulin signaling, driving hepatic glucose production.",
   "bloom":"analyze",
   "source":[{"book":"Curated Units","page":0}],
   "confusable_with":""},
  {"id":f"{S34}-3","topic":T34,"domain":D34,"discipline":DI34,
   "stem":"Per KDIGO 2012, what glucose target is suggested for critically ill patients with AKI to minimize adverse outcomes?",
   "answer":"Insulin therapy targeting plasma glucose 110–149 mg/dL (6.1–8.3 mmol/L) is suggested in critically ill patients with AKI.",
   "rationale":"This target is slightly stricter than the general ICU target; it balances hyperglycemia-induced AKI risk against hypoglycemia danger.",
   "bloom":"recall",
   "source":[{"book":"Society Guideline: Guideline   KDIGO 2012 AKI","page":46}],
   "confusable_with":"General ICU target 140–180 (NICE-SUGAR)"},
  {"id":f"{S34}-4","topic":T34,"domain":D34,"discipline":DI34,
   "stem":"Chronic hyperglycemia in type 1 diabetes leads to glycosylation of tissue proteins. What clinical complication does joint glycosylation cause relevant to anesthesia?",
   "answer":"Reduced joint mobility: glycosylation of the temporomandibular joint and cervical spine can impair mouth opening and neck extension, complicating airway management.",
   "rationale":"'Prayer sign' (inability to approximate palmar surfaces of fingers) indicates generalized joint glycosylation; limited TMJ/cervical mobility predicts difficult intubation.",
   "bloom":"apply",
   "source":[{"book":"Morgan & Mikhail","page":1221}],
   "confusable_with":""},
  {"id":f"{S34}-5","topic":T34,"domain":D34,"discipline":DI34,
   "stem":"How does hyperglycemia in sepsis specifically harm the immune response?",
   "answer":"Hyperglycemia impairs neutrophil function and phagocytosis, increases infection risk, and worsens outcomes; tight control restores some immune function.",
   "rationale":"High glucose concentrations impair chemotaxis, oxidative burst, and complement function; sepsis + hyperglycemia creates a vicious cycle worsening infection.",
   "bloom":"analyze",
   "source":[{"book":"Curated Units","page":0}],
   "confusable_with":""},
  {"id":f"{S34}-6","topic":T34,"domain":D34,"discipline":DI34,
   "stem":"A hospitalized diabetic patient's glucose is well-controlled but they are now tolerating oral intake. What transition should be made in insulin management?",
   "answer":"Transition from IV insulin drip to subcutaneous insulin regimen once oral intake resumes; monitor glucose q4–6 hours after transition.",
   "rationale":"IV insulin is rapidly titratable but requires ICU-level monitoring; subcutaneous insulin is appropriate once eating and metabolically stable.",
   "bloom":"apply",
   "source":[{"book":"Curated Units","page":0}],
   "confusable_with":""},
  {"_type":"confusable_pair","topic_a":"Tight glycemic control (80–110 mg/dL)","topic_b":"Standard glycemic control (140–180 mg/dL)","discriminator":"NICE-SUGAR showed tight control increased ICU mortality from hypoglycemia; target 140–180 mg/dL is now standard for critically ill patients"},
]

print(f"Total entries after items 19-34: {len(catalog)}")
kps = [e for e in catalog if '_type' not in e]
pairs = [e for e in catalog if e.get('_type') == 'confusable_pair']
print(f"KPs: {len(kps)}, Confusable pairs: {len(pairs)}")

with open('data/kp_catalog_part_1.json', 'w', encoding='utf-8') as f:
    json.dump(catalog, f, ensure_ascii=False, indent=2)
print("Final file written to data/kp_catalog_part_1.json")

# Validate
with open('data/kp_catalog_part_1.json', 'r', encoding='utf-8') as f:
    validated = json.load(f)
print(f"Validation OK: {len(validated)} total entries parsed successfully.")
