import json, sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

kps = []

# 248: ICP Physiology & Monitoring
kps += [
  {"id":"icp-physiology-d1","topic":"Intracranial Pressure: Physiology & Monitoring","domain":"Neuroanesthesia & neuromonitoring","discipline":"anesthesia","stem":"What are the three components of the Monro-Kellie doctrine that determine intracranial volume?","answer":"Brain parenchyma, cerebrospinal fluid (CSF), and intracranial blood volume; because the skull is rigid, an increase in any one component must be compensated by reduction in another or ICP rises.","rationale":"This doctrine is fundamental to understanding ICP management: interventions target one or more compartments (e.g., mannitol reduces brain water, hyperventilation reduces CBF/blood volume, ventriculostomy removes CSF).","bloom":"recall","source":[{"book":"Miller/Baby Miller","page":564}],"confusable_with":"Fick principle (cerebral oxygen)"},
  {"id":"icp-physiology-d2","topic":"Intracranial Pressure: Physiology & Monitoring","domain":"Neuroanesthesia & neuromonitoring","discipline":"anesthesia","stem":"What is cerebral perfusion pressure (CPP) and what is the therapeutic target in TBI management?","answer":"CPP = MAP - ICP; target is generally 60-70 mmHg in TBI. Values < 50 mmHg are associated with secondary ischemic injury; aggressive ICP reduction should not compromise MAP.","rationale":"CPP determines cerebral blood flow in the setting of impaired autoregulation; below 50 mmHg, ischemia risk escalates even if ICP is controlled.","bloom":"recall","source":[{"book":"Stanford CA-1","page":17}],"confusable_with":"MAP alone as cerebral perfusion target"},
  {"id":"icp-physiology-d3","topic":"Intracranial Pressure: Physiology & Monitoring","domain":"Neuroanesthesia & neuromonitoring","discipline":"anesthesia","stem":"Deep levels of anesthesia in neurosurgery should achieve what goals beyond unconsciousness?","answer":"Maintain optimal cerebral perfusion, facilitate neurophysiologic monitoring, enable smooth prompt emergence without agitation, confusion, nausea, or shivering.","rationale":"Emergence agitation can dramatically increase ICP and blood pressure; smooth emergence is as important as induction in neurosurgical cases.","bloom":"apply","source":[{"book":"Miller/Baby Miller","page":564}],"confusable_with":"generic emergence criteria"},
  {"id":"icp-physiology-d4","topic":"Intracranial Pressure: Physiology & Monitoring","domain":"Neuroanesthesia & neuromonitoring","discipline":"anesthesia","stem":"Normal ICP is generally < 10-15 mmHg; what level requires treatment?","answer":"ICP > 20-25 mmHg sustained requires treatment; values > 40 mmHg represent severe intracranial hypertension with imminent herniation risk.","rationale":"ICP thresholds guide intervention timing; transient elevations with coughing or Valsalva are normal, but sustained elevations reduce CPP and threaten neuronal viability.","bloom":"recall","source":[{"book":"Miller/Baby Miller","page":387}],"confusable_with":"CSF opening pressure (different measurement)"},
  {"id":"icp-physiology-d5","topic":"Intracranial Pressure: Physiology & Monitoring","domain":"Neuroanesthesia & neuromonitoring","discipline":"anesthesia","stem":"Body temperature reduction reduces cerebral metabolic requirements by what rate?","answer":"Metabolic rate decreases by approximately 8% per 1 deg C decrease in temperature; this principle is used for hypothermic neuroprotection during cerebrovascular surgery.","rationale":"Even modest hypothermia (33-35 deg C) provides meaningful metabolic suppression; during temporary vessel occlusion, hypothermia extends the safe ischemic window.","bloom":"recall","source":[{"book":"Stanford CA-1","page":64}],"confusable_with":"Q10 effect (similar but stated as halving per 10 deg C)"},
  {"id":"icp-physiology-d6","topic":"Intracranial Pressure: Physiology & Monitoring","domain":"Neuroanesthesia & neuromonitoring","discipline":"anesthesia","stem":"An intraoperative MAP < 50 mmHg or > 40% decrease from baseline is associated with what outcome?","answer":"A large prospective study found that intraoperative MAP < 50 mmHg or a 40% decrease from baseline is associated with increased postoperative AKI, MI, and stroke risk.","rationale":"Cerebral autoregulation maintains CBF constant between MAP 50-150 mmHg; below 50 mmHg autoregulation fails and CBF falls, causing ischemia in the brain and other organs.","bloom":"recall","source":[{"book":"Miller/Baby Miller","page":390}],"confusable_with":"hypotension in neurologically normal patients (less consequential)"}
]

# 249: IONM (thin chunks, general)
kps += [
  {"id":"ionm-d1","topic":"Intraoperative Neurophysiological Monitoring (IONM)","domain":"Neuroanesthesia & neuromonitoring","discipline":"anesthesia","stem":"What essential safety resources must be immediately available when performing any regional or neuraxial block that could cause LA systemic toxicity?","answer":"Standard anesthetic monitors, supplemental oxygen, IV access, resuscitative medications, and lipid emulsion (20% Intralipid 1.5 mL/kg rescue dose) must be available at the site of block administration.","rationale":"LAST can evolve rapidly from CNS to cardiovascular toxicity; immediate availability of lipid emulsion and full resuscitation capability is mandatory.","bloom":"recall","source":[{"book":"Morgan & Mikhail","page":1608}],"confusable_with":"crash cart only (insufficient without lipid emulsion)"},
  {"id":"ionm-d2","topic":"Intraoperative Neurophysiological Monitoring (IONM)","domain":"Neuroanesthesia & neuromonitoring","discipline":"anesthesia","stem":"Neuromuscular blockade directly interferes with what type of intraoperative neuromonitoring?","answer":"NMBs block motor evoked potential (MEP) monitoring and electromyography (EMG) responses; maintenance of single-twitch or TOF > 2 twitches is required to maintain interpretable motor responses.","rationale":"MEPs require intact neuromuscular junction function; complete NMB abolishes motor responses, eliminating the ability to detect motor pathway compromise intraoperatively.","bloom":"recall","source":[{"book":"Stanford CA-1","page":37}],"confusable_with":"SSEP monitoring (not affected by NMB)"},
  {"id":"ionm-d3","topic":"Intraoperative Neurophysiological Monitoring (IONM)","domain":"Neuroanesthesia & neuromonitoring","discipline":"anesthesia","stem":"Non-invasive blood pressure measurement by oscillometry most accurately measures which blood pressure value?","answer":"MAP is the most accurate value produced by oscillometric NIBP measurement; SBP and DBP are calculated from MAP.","rationale":"Oscillometric sensors detect the point of maximal oscillation (MAP); systolic and diastolic values are algorithmically derived and inherently less precise.","bloom":"recall","source":[{"book":"Stanford CA-1","page":35}],"confusable_with":"invasive arterial line (direct measurement of all values)"},
  {"id":"ionm-d4","topic":"Intraoperative Neurophysiological Monitoring (IONM)","domain":"Neuroanesthesia & neuromonitoring","discipline":"anesthesia","stem":"Depth of anesthesia monitoring with MAC calculations incorporating age correction alerts providers to what specific risk?","answer":"Age-adjusted MAC calculations alert when anesthetic concentration may be insufficient to prevent postoperative recall; MAC-awake equivalent declines with age.","rationale":"Older patients require less volatile agent to prevent awareness; failure to account for age when interpreting MAC values may lead to awareness at seemingly adequate MAC levels.","bloom":"apply","source":[{"book":"Miller/Baby Miller","page":399}],"confusable_with":"BIS monitoring (different modality, similar goal)"},
  {"id":"ionm-d5","topic":"Intraoperative Neurophysiological Monitoring (IONM)","domain":"Neuroanesthesia & neuromonitoring","discipline":"anesthesia","stem":"An acute change in alveolar dead space occurs classically in what intraoperative clinical situation?","answer":"Pulmonary embolism causes acute increase in alveolar dead space (ventilated but non-perfused alveoli), evidenced by sudden decrease in EtCO2 with unchanged or rising PaCO2.","rationale":"EtCO2 monitors alveolar dead space indirectly; PE reduces pulmonary perfusion while ventilation continues, widening the EtCO2-PaCO2 gradient and dropping EtCO2.","bloom":"apply","source":[{"book":"Miller/Baby Miller","page":386}],"confusable_with":"bronchospasm (increases dead space differently)"}
]

# 250: IV Anesthetic Pharmacology
kps += [
  {"id":"iv-anesthetic-pharm-d1","topic":"Intravenous Anesthetic Pharmacology","domain":"Pharmacology, drug interactions & toxicology","discipline":"anesthesia","stem":"Target-controlled infusion (TCI) uses what input parameters for propofol to achieve an effect-site concentration?","answer":"TCI requires patient age and weight as inputs; the DiprifusorTM system then calculates infusion rates using pharmacokinetic modeling to achieve and maintain the clinician-set blood concentration.","rationale":"TCI automates the complex pharmacokinetic calculations needed to maintain stable effect-site concentrations, avoiding the peak-trough oscillations of manual bolus dosing.","bloom":"recall","source":[{"book":"Morgan & Mikhail","page":737}],"confusable_with":"manual infusion rate calculation"},
  {"id":"iv-anesthetic-pharm-d2","topic":"Intravenous Anesthetic Pharmacology","domain":"Pharmacology, drug interactions & toxicology","discipline":"anesthesia","stem":"What are the pharmacokinetic mechanisms that prolong IV anesthetic effects in elderly patients?","answer":"Reduced clearance (decreased liver/kidney function), altered volume of distribution (reduced lean body mass, altered plasma protein binding), and increased pharmacodynamic sensitivity all prolong effect in elderly.","rationale":"Age-related changes in protein binding, hepatic microsomal enzyme activity, and renal excretion compound to extend drug half-lives and intensify effects.","bloom":"analyze","source":[{"book":"Morgan & Mikhail","page":1506}],"confusable_with":"pediatric pharmacokinetics"},
  {"id":"iv-anesthetic-pharm-d3","topic":"Intravenous Anesthetic Pharmacology","domain":"Pharmacology, drug interactions & toxicology","discipline":"anesthesia","stem":"Combination of opioids and benzodiazepines produces what important synergistic cardiovascular effect?","answer":"Opioid-benzodiazepine combination markedly reduces arterial blood pressure and peripheral vascular resistance through synergistic vasodilation, more than either agent alone.","rationale":"This synergy is clinically important during cardiac anesthesia induction; while beneficial for reducing pressor responses, it can cause severe hypotension in volume-depleted patients.","bloom":"apply","source":[{"book":"Morgan & Mikhail","page":284}],"confusable_with":"additive (not synergistic) effect"},
  {"id":"iv-anesthetic-pharm-d4","topic":"Intravenous Anesthetic Pharmacology","domain":"Pharmacology, drug interactions & toxicology","discipline":"anesthesia","stem":"During cardiac surgery with CPB, why should anesthetic gas concentration be monitored at the bypass circuit?","answer":"During CPB, ventilation stops; volatile agents must be administered via vaporizer on the bypass machine. Monitoring gas concentration from the bypass machine prevents awareness during the bypass period.","rationale":"Intraoperative awareness during CPB is a recognized risk; without active volatile agent administration through the bypass circuit, TIVA or IV supplements must be used.","bloom":"apply","source":[{"book":"Morgan & Mikhail","page":204}],"confusable_with":"ventilator-delivered gas during CPB (not possible)"},
  {"id":"iv-anesthetic-pharm-d5","topic":"Intravenous Anesthetic Pharmacology","domain":"Pharmacology, drug interactions & toxicology","discipline":"anesthesia","stem":"Propofol undergoes extrahepatic metabolism in addition to hepatic metabolism - what sites contribute?","answer":"Propofol is metabolized at extrahepatic sites including the kidney, small intestine, and lung; this was confirmed by its continued metabolism during the anhepatic phase of liver transplantation.","rationale":"Extrahepatic metabolism explains why propofol clearance exceeds hepatic blood flow; this property makes it useful even in severe liver disease.","bloom":"recall","source":[{"book":"Miller/Baby Miller","page":134}],"confusable_with":"hepatic first-pass metabolism only"},
  {"id":"iv-anesthetic-pharm-d6","topic":"Intravenous Anesthetic Pharmacology","domain":"Pharmacology, drug interactions & toxicology","discipline":"anesthesia","stem":"Barbiturates stimulate what enzyme system that has clinical implications for anesthetic dosing?","answer":"Barbiturates stimulate aminolevulinic acid synthetase, increasing porphyrin production; they are absolutely contraindicated in patients with acute porphyria as they can precipitate a potentially fatal attack.","rationale":"Porphyria attacks occur when porphyrin precursors accumulate; enzyme induction by barbiturates accelerates the metabolic pathway, producing neurotoxic precursors.","bloom":"recall","source":[{"book":"Miller/Baby Miller","page":138}],"confusable_with":"general hepatic enzyme induction"}
]

# 251: Isoflurane (thin/off-topic chunks - use what's relevant)
kps += [
  {"id":"isoflurane-d1","topic":"Isoflurane: clinical pharmacology","domain":"Pharmacology, drug interactions & toxicology","discipline":"anesthesia","stem":"Why is choosing a potent inhalation agent (e.g., isoflurane) rather than TIVA an important consideration for preventing intraoperative awareness?","answer":"Potent inhaled agents provide reliable amnesia and titrable anesthesia depth trackable by end-tidal gas monitoring; TIVA is harder to monitor directly for inadequate depth without processed EEG.","rationale":"Exhaled gas concentration is a pharmacokinetic proxy for anesthetic effect; real-time end-tidal monitoring with low-concentration alarms provides a safety layer absent with TIVA alone.","bloom":"apply","source":[{"book":"Morgan & Mikhail","page":204}],"confusable_with":"TIVA (no exhaled concentration monitoring)"},
  {"id":"isoflurane-d2","topic":"Isoflurane: clinical pharmacology","domain":"Pharmacology, drug interactions & toxicology","discipline":"anesthesia","stem":"Cimetidine limits hepatic metabolism of co-administered drugs via what mechanism?","answer":"Cimetidine inhibits hepatic microsomal cytochrome P450 enzymes and reduces liver blood flow, thereby impairing hepatic drug metabolism and prolonging effects of drugs with high hepatic extraction ratios.","rationale":"Drugs such as isoflurane (minimal hepatic metabolism) are less affected, but agents dependent on hepatic clearance (e.g., some benzodiazepines, opioids) will have prolonged effects with cimetidine.","bloom":"apply","source":[{"book":"Morgan & Mikhail","page":352}],"confusable_with":"ranitidine (H2 blocker with less P450 inhibition)"},
  {"id":"isoflurane-d3","topic":"Isoflurane: clinical pharmacology","domain":"Pharmacology, drug interactions & toxicology","discipline":"anesthesia","stem":"Emergence from general anesthesia with isoflurane is ideally characterized by what features?","answer":"Smooth and gradual awakening in a controlled environment; complications include airway obstruction, shivering, agitation, delirium, pain, nausea and vomiting.","rationale":"Isoflurane's relatively higher blood-gas solubility (compared to desflurane/sevoflurane) means slightly slower emergence; smooth emergence reduces laryngospasm and CV stress.","bloom":"recall","source":[{"book":"Morgan & Mikhail","page":2098}],"confusable_with":"desflurane emergence (faster, more airway reactivity)"},
  {"id":"isoflurane-d4","topic":"Isoflurane: clinical pharmacology","domain":"Pharmacology, drug interactions & toxicology","discipline":"anesthesia","stem":"Anticholinergic side effects of antiparkinsonian drugs and tricyclic antidepressants augment the sedation produced by what premedication agent?","answer":"Scopolamine — its sedative and anticholinergic effects are potentiated by concomitant use of tricyclic antidepressants and antiparkinsonian drugs.","rationale":"Additive anticholinergic CNS effects can cause excessive sedation, delirium, and urinary retention; this interaction is important in elderly patients taking TCAs for pain management.","bloom":"apply","source":[{"book":"Morgan & Mikhail","page":352}],"confusable_with":"atropine (different anticholinergic profile)"},
  {"id":"isoflurane-d5","topic":"Isoflurane: clinical pharmacology","domain":"Pharmacology, drug interactions & toxicology","discipline":"anesthesia","stem":"In cardiac surgery, why is monitoring volatile anesthetic gas concentration critical during CPB?","answer":"During CPB, the lungs are bypassed; isoflurane or other volatiles must be delivered through the bypass circuit oxygenator. Without monitoring, patients may receive inadequate depth, causing awareness.","rationale":"Standard ventilator gas delivery is interrupted during CPB; the bypass machine oxygenator becomes the delivery route, requiring dedicated monitoring of delivered concentration.","bloom":"apply","source":[{"book":"Morgan & Mikhail","page":204}],"confusable_with":"standard ventilated anesthesia"}
]

print(f"Batch 5 KPs: {len(kps)}")
with open('data/kp_part7_batch5.json', 'w', encoding='utf-8') as f:
    json.dump(kps, f, ensure_ascii=False, indent=2)
print("Saved batch 5")
