#!/usr/bin/env python3
"""Build KP catalog part 1 (items 0-34, all Approach-to-X topics)."""
import json, sys, io, re
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

def slug(topic):
    s = topic.lower()
    s = re.sub(r'[^a-z0-9]+', '-', s)
    return s.strip('-')

catalog = []

# ─── ITEM 0: Approach to Acute Anemia and Falling Hemoglobin ───────────────
T0 = "Approach to Acute Anemia and Falling Hemoglobin"
D0 = "Internal medicine: on-call & cross-cover (approach to the acutely changing ward patient)"
DI0 = "medicine"
S0 = slug(T0)
catalog += [
  {"id":f"{S0}-1","topic":T0,"domain":D0,"discipline":DI0,
   "stem":"A post-op patient has a hemoglobin drop from 10 to 7 g/dL overnight. What does patient blood management (PBM) emphasize as the first step before considering transfusion?",
   "answer":"Identify and treat the underlying cause (e.g., iron deficiency, surgical bleeding); preoperative correction with iron ± erythropoietin reduces transfusion need.",
   "rationale":"A higher presurgical hemoglobin level decreases intraoperative transfusion requirements and lowers overall morbidity and mortality.",
   "bloom":"apply",
   "source":[{"book":"Miller/Baby Miller","page":474}],
   "confusable_with":""},
  {"id":f"{S0}-2","topic":T0,"domain":D0,"discipline":DI0,
   "stem":"In a patient with sickle cell trait (HbAS) who is becoming anemic perioperatively, what distinguishes their risk profile from homozygous HbSS disease?",
   "answer":"HbAS patients are generally not anemic, are asymptomatic, and have a normal life span; sickling requires extreme conditions unlike HbSS.",
   "rationale":"Patients with sickle cell trait produce 55–60% HbA and 35–40% HbS; sickling occurs only under extreme conditions not typical in perioperative care.",
   "bloom":"analyze",
   "source":[{"book":"Morgan & Mikhail","page":1971}],
   "confusable_with":"Sickle cell anemia (HbSS)"},
  {"id":f"{S0}-3","topic":T0,"domain":D0,"discipline":DI0,
   "stem":"A patient with chronic kidney disease presents with worsening anemia. What additional hematologic finding should you expect on labs?",
   "answer":"Prolonged bleeding time (platelet dysfunction) and increased susceptibility to infection (impaired white cell function).",
   "rationale":"Both platelet and white cell function are impaired in kidney failure, manifesting as prolonged bleeding time and infection susceptibility.",
   "bloom":"recall",
   "source":[{"book":"Morgan & Mikhail","page":1111}],
   "confusable_with":""},
  {"id":f"{S0}-4","topic":T0,"domain":D0,"discipline":DI0,
   "stem":"On visual estimation of blood loss in the OR, what is the main limitation of this technique for detecting acute anemia?",
   "answer":"Visual estimation is the simplest but least accurate method; it systematically underestimates blood loss.",
   "rationale":"Blood mixing with irrigation fluid and surgical drapes makes visual estimation unreliable for quantifying true blood loss.",
   "bloom":"recall",
   "source":[{"book":"Miller/Baby Miller","page":474}],
   "confusable_with":""},
  {"id":f"{S0}-5","topic":T0,"domain":D0,"discipline":DI0,
   "stem":"In a patient with G6PD deficiency who develops hemolytic anemia, what is the primary management principle?",
   "answer":"Management is primarily preventive—avoid factors known to promote hemolysis; preserve kidney function if hemoglobinuria develops.",
   "rationale":"G6PD deficiency is managed by avoiding triggers (certain drugs, infections, oxidants) rather than treating acute hemolysis after the fact.",
   "bloom":"apply",
   "source":[{"book":"Morgan & Mikhail","page":1977}],
   "confusable_with":""},
  {"id":f"{S0}-6","topic":T0,"domain":D0,"discipline":DI0,
   "stem":"What is the hemoglobin threshold below which most patients with CKD (without symptomatic heart disease) begin to experience significant clinical consequences of anemia?",
   "answer":"Most CKD patients without symptomatic heart disease tolerate anemia well; metabolic acidosis in CKD also shifts the O2-Hgb curve rightward, partially compensating.",
   "rationale":"Rightward shift of the hemoglobin-oxygen dissociation curve from CKD-associated metabolic acidosis increases oxygen delivery to tissues.",
   "bloom":"analyze",
   "source":[{"book":"Morgan & Mikhail","page":1111}],
   "confusable_with":""},
]

# ─── ITEM 1: Approach to Acute Dyspnea ────────────────────────────────────
T1 = "Approach to Acute Dyspnea"
D1 = "Internal medicine: on-call & cross-cover (approach to the acutely changing ward patient)"
DI1 = "medicine"
S1 = slug(T1)
catalog += [
  {"id":f"{S1}-1","topic":T1,"domain":D1,"discipline":DI1,
   "stem":"A hospitalized patient develops acute dyspnea. You suspect pulmonary embolism. What is the most critical first action before pursuing diagnostic workup?",
   "answer":"Ensure hemodynamic stability and oxygenation first; then risk-stratify with pre-test probability scoring before imaging.",
   "rationale":"PE can cause obstructive shock; stabilization precedes diagnosis, and pre-test probability guides whether CT-PA vs empiric anticoagulation is appropriate.",
   "bloom":"apply",
   "source":[{"book":"StatPearls: StatPearls   Pulmonary embolism  diagnosis and treatment","page":1}],
   "confusable_with":""},
  {"id":f"{S1}-2","topic":T1,"domain":D1,"discipline":DI1,
   "stem":"In a COPD patient with acute dyspnea requiring ventilatory support, what is the advantage of HFNC over standard oxygen therapy or NIPPV for certain patients?",
   "answer":"In hypoxemic respiratory failure, HFNC reduced mortality compared to standard oxygen therapy or NIPPV, though without significant difference in intubation rate.",
   "rationale":"HFNC provides high-flow humidified oxygen with low-level PEEP effect, improving oxygenation and patient comfort without the seal issues of masks.",
   "bloom":"recall",
   "source":[{"book":"Miller/Baby Miller","page":767}],
   "confusable_with":"NIPPV (BiPAP)"},
  {"id":f"{S1}-3","topic":T1,"domain":D1,"discipline":DI1,
   "stem":"A patient with acute dyspnea has diffuse 'velcro-like' crackles on auscultation and worsening hypoxemia with exertion. What category of lung disease should be high on the differential?",
   "answer":"Interstitial lung disease (ILD): presents with progressive dyspnea, non-productive cough, hypoxemia especially with exercise, and velcro crackles.",
   "rationale":"ILD involves replacement of normal lung parenchyma with inflammation and fibrosis, causing restrictive physiology and impaired gas exchange.",
   "bloom":"apply",
   "source":[{"book":"MGH Housestaff Manual","page":53}],
   "confusable_with":"Pulmonary edema"},
  {"id":f"{S1}-4","topic":T1,"domain":D1,"discipline":DI1,
   "stem":"For a patient with COPD exacerbation presenting with severe dyspnea, what defines a severe exacerbation requiring hospitalization?",
   "answer":"Severe COPD exacerbation: patient requires hospitalization or emergency room visit; may be associated with acute respiratory failure.",
   "rationale":"Severity grading of COPD exacerbation is based on healthcare resource utilization, though this has recognized limitations due to global variability.",
   "bloom":"recall",
   "source":[{"book":"Society Guideline: Guideline   GOLD 2024 COPD Full Report","page":112}],
   "confusable_with":""},
  {"id":f"{S1}-5","topic":T1,"domain":D1,"discipline":DI1,
   "stem":"In a patient with acute dyspnea from decompensated heart failure, which clinical findings indicate severe decompensation rather than mild HFpEF?",
   "answer":"Severe decompensation: diaphoresis, tachycardia, tachypnea, hypoxia; may be hypotensive from decreased peripheral tissue perfusion.",
   "rationale":"Mild HFpEF at baseline shows mild systolic hypertension; acute decompensation activates sympathetic compensatory mechanisms leading to these signs.",
   "bloom":"apply",
   "source":[{"book":"StatPearls","page":9}],
   "confusable_with":""},
  {"id":f"{S1}-6","topic":T1,"domain":D1,"discipline":DI1,
   "stem":"A patient on an ACE inhibitor develops acute onset dyspnea and cough that worsens over weeks. Which common cause should be considered first?",
   "answer":"ACE inhibitor-induced cough (upper airway cough syndrome): accounts for a significant portion of chronic cough; removing the offending agent is the key management step.",
   "rationale":"ACE inhibitors cause bradykinin accumulation leading to cough and potentially angioedema; discontinuation resolves symptoms.",
   "bloom":"apply",
   "source":[{"book":"MGH Housestaff Manual","page":226}],
   "confusable_with":"Asthma"},
]

# ─── ITEM 2: Approach to Acute Focal Neurologic Deficit ───────────────────
T2 = "Approach to Acute Focal Neurologic Deficit"
D2 = "Internal medicine: on-call & cross-cover (approach to the acutely changing ward patient)"
DI2 = "medicine"
S2 = slug(T2)
catalog += [
  {"id":f"{S2}-1","topic":T2,"domain":D2,"discipline":DI2,
   "stem":"A ward patient develops sudden onset right-sided weakness and slurred speech. What is the most time-critical first step in management?",
   "answer":"Activate stroke response immediately; determine last known well time to assess eligibility for thrombolysis or thrombectomy.",
   "rationale":"Time-to-treatment is the dominant determinant of outcome in ischemic stroke; 'time is brain' mandates immediate activation of the stroke protocol.",
   "bloom":"apply",
   "source":[{"book":"StatPearls: StatPearls   Transient Ischemic Attack (TIA)","page":1}],
   "confusable_with":"Todd's paralysis"},
  {"id":f"{S2}-2","topic":T2,"domain":D2,"discipline":DI2,
   "stem":"A patient with known hypercoagulable state develops progressive headache, papilledema, and focal motor weakness over days. Unlike arterial stroke, these deficits do not localize cleanly. What diagnosis must be considered?",
   "answer":"Cerebral venous sinus thrombosis (CVST): focal deficits occur in up to 44% of cases, motor weakness is most frequent, and deficits do not follow arterial territories.",
   "rationale":"CVST causes venous congestion and edema in watershed areas, producing deficits that cross typical arterial boundaries.",
   "bloom":"analyze",
   "source":[{"book":"StatPearls: StatPearls   Cerebral Venous Sinus Thrombosis (CVST)","page":4}],
   "confusable_with":"Arterial ischemic stroke"},
  {"id":f"{S2}-3","topic":T2,"domain":D2,"discipline":DI2,
   "stem":"A TIA patient presents with transient left arm weakness that fully resolved 30 minutes ago. What is the priority workup within the next 24–48 hours?",
   "answer":"Urgent neuroimaging (MRI/DWI), cardiac monitoring for atrial fibrillation, carotid imaging, and antiplatelet therapy; TIA has high short-term stroke risk.",
   "rationale":"TIA is a medical emergency; up to 10–15% of TIA patients stroke within 3 months, with highest risk in the first 48 hours.",
   "bloom":"apply",
   "source":[{"book":"StatPearls: StatPearls   Transient Ischemic Attack (TIA)","page":1}],
   "confusable_with":""},
  {"id":f"{S2}-4","topic":T2,"domain":D2,"discipline":DI2,
   "stem":"When evaluating a new focal neurologic deficit, the SNOOP4 mnemonic is used to identify secondary (dangerous) headache disorders. What does the 'N' stand for?",
   "answer":"N = Neurological symptoms, especially focal neurologic deficits, indicating a secondary cause requiring urgent workup.",
   "rationale":"Focal deficits accompanying headache markedly raise the probability of a structural or vascular cause requiring emergent neuroimaging.",
   "bloom":"recall",
   "source":[{"book":"StatPearls: StatPearls   Headache  Primary Disorders","page":7}],
   "confusable_with":""},
  {"id":f"{S2}-5","topic":T2,"domain":D2,"discipline":DI2,
   "stem":"A trauma patient with loss of consciousness and intoxication is found to have focal motor deficits. Why should cervical spine injury be presumed?",
   "answer":"Cervical spine injury is presumed in any trauma patient with neck pain, neurologic injury, significant head injury, loss of consciousness, or intoxication until ruled out by imaging.",
   "rationale":"Unrecognized cervical instability with manipulation can cause irreversible spinal cord injury; immobilization protects until imaging confirms safety.",
   "bloom":"recall",
   "source":[{"book":"Morgan & Mikhail","page":1319}],
   "confusable_with":""},
  {"id":f"{S2}-6","topic":T2,"domain":D2,"discipline":DI2,
   "stem":"For neuroprotection in a patient with focal cerebral ischemia undergoing neurosurgery, which anesthetic agent class may provide some benefit?",
   "answer":"Barbiturates may provide neuroprotection from focal cerebral ischemia (stroke, surgical retraction, temporary clips) but probably not from global cerebral ischemia.",
   "rationale":"Barbiturates reduce CMRO2 and can decrease ICP; their protective effect is limited to focal rather than global ischemia mechanisms.",
   "bloom":"analyze",
   "source":[{"book":"Miller/Baby Miller","page":139}],
   "confusable_with":""},
]

# ─── ITEM 3: Approach to Acute GI Bleed ──────────────────────────────────
T3 = "Approach to Acute GI Bleed"
D3 = "Internal medicine: on-call & cross-cover (approach to the acutely changing ward patient)"
DI3 = "medicine"
S3 = slug(T3)
catalog += [
  {"id":f"{S3}-1","topic":T3,"domain":D3,"discipline":DI3,
   "stem":"A patient presents with hematemesis and a BUN/Cr ratio of 38. What does this ratio suggest, and how reliable is it?",
   "answer":"BUN/Cr >30 has +LR 7.5 for UGIB; ratio >35 is 100% specific for upper GI source.",
   "rationale":"Blood in the upper GI tract is digested and absorbed, raising BUN disproportionately to creatinine.",
   "bloom":"apply",
   "source":[{"book":"MGH Housestaff Manual","page":70}],
   "confusable_with":""},
  {"id":f"{S3}-2","topic":T3,"domain":D3,"discipline":DI3,
   "stem":"A patient with lower GI bleed is hemodynamically stable. Which risk score predicts 30-day mortality, and which predicts safe discharge?",
   "answer":"ABC score predicts 30-day mortality; Oakland score <8 may predict safe discharge.",
   "rationale":"Validated risk scores allow appropriate triage of LGIB patients to inpatient vs outpatient management.",
   "bloom":"recall",
   "source":[{"book":"MGH Housestaff Manual","page":71}],
   "confusable_with":""},
  {"id":f"{S3}-3","topic":T3,"domain":D3,"discipline":DI3,
   "stem":"On initial cross-cover assessment of GI bleed, what hemodynamic findings indicate the patient is NOT stable and requires urgent escalation?",
   "answer":"Tachycardia, hypotension, orthostatic changes, altered mental status, syncope—any of these indicate hemodynamic instability.",
   "rationale":"These signs reflect significant intravascular volume depletion requiring urgent resuscitation and emergent endoscopy/intervention.",
   "bloom":"apply",
   "source":[{"book":"Intern Notes / Survival Guide","page":13}],
   "confusable_with":""},
  {"id":f"{S3}-4","topic":T3,"domain":D3,"discipline":DI3,
   "stem":"In a patient with UGIB, the presence of blood clots in stool makes UGIB less likely. What likelihood ratio supports this?",
   "answer":"Blood clots in stool make UGIB less likely (+LR 0.05); melena on exam is strongly positive for UGIB (+LR 25).",
   "rationale":"Clots require slower transit than typical UGIB; melena indicates blood has spent sufficient time in the GI tract to be degraded.",
   "bloom":"recall",
   "source":[{"book":"MGH Housestaff Manual","page":70}],
   "confusable_with":""},
  {"id":f"{S3}-5","topic":T3,"domain":D3,"discipline":DI3,
   "stem":"A patient with cirrhosis presents with acute upper GI bleeding. Urgent endoscopy confirms gastric variceal bleeding. What is the mainstay of endoscopic management?",
   "answer":"Endoscopic hemostasis is the mainstay; options include injection sclerotherapy and other endoscopic interventions for gastric variceal bleeding.",
   "rationale":"Gastric varices are at high risk for massive hemorrhage; data on specific endoscopic modalities is limited but endoscopic therapy remains first-line.",
   "bloom":"recall",
   "source":[{"book":"StatPearls: StatPearls   Lower GI Bleed  Evaluation & Management","page":6}],
   "confusable_with":""},
  {"id":f"{S3}-6","topic":T3,"domain":D3,"discipline":DI3,
   "stem":"After recovery from gastric variceal hemorrhage (GOV2 or IGV1 type), what is first-line secondary prophylaxis against rebleeding?",
   "answer":"TIPS or BRTO are indicated as first-line therapy for secondary prophylaxis in GOV2 or IGV1 gastric variceal hemorrhage.",
   "rationale":"Unlike esophageal varices where EVL + beta-blockers are first-line, gastric varices (GOV2/IGV1) respond better to TIPS or BRTO for secondary prevention.",
   "bloom":"recall",
   "source":[{"book":"StatPearls: StatPearls   Lower GI Bleed  Evaluation & Management","page":9}],
   "confusable_with":"EVL + non-selective beta-blockers (correct for esophageal varices, not GOV2/IGV1)"},
  {"id":f"{S3}-7","topic":T3,"domain":D3,"discipline":DI3,
   "stem":"In a patient with refractory hypotension from GI hemorrhage unresponsive to norepinephrine and epinephrine, what vasopressor can be added?",
   "answer":"Vasopressin may be added for refractory hypotension; severe acidosis (pH <7.20) should be corrected with bicarbonate or THAM to maintain inotrope efficacy.",
   "rationale":"Severe acidosis decreases inotrope responsiveness; vasopressin acts through V1 receptors independently of adrenergic pathways.",
   "bloom":"apply",
   "source":[{"book":"Morgan & Mikhail","page":2156}],
   "confusable_with":""},
]

# ─── ITEM 4: Approach to Acute Respiratory Failure ────────────────────────
T4 = "Approach to Acute Respiratory Failure"
D4 = "Internal medicine: on-call & cross-cover (approach to the acutely changing ward patient)"
DI4 = "medicine"
S4 = slug(T4)
catalog += [
  {"id":f"{S4}-1","topic":T4,"domain":D4,"discipline":DI4,
   "stem":"A mechanically ventilated patient with ARDS has a PaO2:FiO2 ratio of 180. What tidal volume strategy is recommended?",
   "answer":"Low tidal volume ventilation: Vt 4–8 mL/kg predicted body weight, maintain plateau pressures below 30 cm H2O.",
   "rationale":"Lung-protective ventilation reduces ventilator-induced lung injury by limiting overdistension and cyclic atelectrauma.",
   "bloom":"apply",
   "source":[{"book":"Society Guideline","page":39}],
   "confusable_with":""},
  {"id":f"{S4}-2","topic":T4,"domain":D4,"discipline":DI4,
   "stem":"For a patient with moderate-to-severe ARDS, what positional maneuver is recommended for more than 12 hours per day to improve oxygenation?",
   "answer":"Prone positioning for >12 hours per day improves oxygenation and outcomes in moderate-to-severe ARDS.",
   "rationale":"Prone positioning redistributes lung perfusion to better-ventilated dorsal regions, improving V/Q matching.",
   "bloom":"recall",
   "source":[{"book":"StatPearls: StatPearls   Lactic Acidosis","page":8}],
   "confusable_with":""},
  {"id":f"{S4}-3","topic":T4,"domain":D4,"discipline":DI4,
   "stem":"A patient with acute respiratory failure is trialed on NIPPV (BiPAP). For which patient population is NIPPV most supported by evidence?",
   "answer":"NIPPV (CPAP/BiPAP) delivers positive-pressure breaths without an ETT and is supported for hypercapnic respiratory failure (COPD exacerbation) and cardiogenic pulmonary edema.",
   "rationale":"BiPAP reduces work of breathing and avoids intubation complications; strongest evidence is in COPD and cardiogenic pulmonary edema.",
   "bloom":"apply",
   "source":[{"book":"Miller/Baby Miller","page":767}],
   "confusable_with":"HFNC"},
  {"id":f"{S4}-4","topic":T4,"domain":D4,"discipline":DI4,
   "stem":"A patient develops acute metabolic alkalosis with compensatory hypoventilation causing respiratory failure. What is the primary acid-base defect and treatment target?",
   "answer":"Metabolic alkalosis (pH >7.45 from HCO3 gain or H+ loss); treat the underlying cause (e.g., replace chloride/potassium); avoid overcorrecting ventilation.",
   "rationale":"Metabolic alkalosis from GI H+ loss or diuretics causes compensatory hypoventilation; correcting the metabolic abnormality restores respiratory drive.",
   "bloom":"analyze",
   "source":[{"book":"Miller/Baby Miller","page":431}],
   "confusable_with":""},
  {"id":f"{S4}-5","topic":T4,"domain":D4,"discipline":DI4,
   "stem":"In ARDS management, moderate-dose corticosteroids have been shown to likely improve which outcomes?",
   "answer":"Moderate-dose corticosteroids likely improve morbidity and mortality in ARDS; benefit in COVID-19 lung disease is established.",
   "rationale":"Steroids modulate the dysregulated inflammatory cascade in ARDS; evidence is strongest for COVID-19-associated ARDS but underlying data overall remain controversial.",
   "bloom":"recall",
   "source":[{"book":"Morgan & Mikhail","page":2132}],
   "confusable_with":""},
  {"id":f"{S4}-6","topic":T4,"domain":D4,"discipline":DI4,
   "stem":"In acute respiratory failure, when is sodium bicarbonate indicated?",
   "answer":"Consider small-dose sodium bicarbonate in severe metabolic acidosis; administer then repeat pH and hemodynamic monitoring to assess impact before further dosing.",
   "rationale":"Bicarbonate can worsen intracellular acidosis via CO2 generation; a cautious titrated approach limits this risk.",
   "bloom":"apply",
   "source":[{"book":"Miller/Baby Miller","page":431}],
   "confusable_with":""},
]

# ─── ITEM 5: Approach to Alcohol Withdrawal ───────────────────────────────
T5 = "Approach to Alcohol Withdrawal"
D5 = "Internal medicine: on-call & cross-cover (approach to the acutely changing ward patient)"
DI5 = "medicine"
S5 = slug(T5)
catalog += [
  {"id":f"{S5}-1","topic":T5,"domain":D5,"discipline":DI5,
   "stem":"A hospitalized patient with heavy alcohol use has tremors and diaphoresis on day 2 of admission. What screening tool best quantifies withdrawal severity?",
   "answer":"CIWA-Ar (Clinical Institute Withdrawal Assessment for Alcohol) quantifies severity; AUDIT-C screens for unhealthy use, CAGE for dependence.",
   "rationale":"CIWA-Ar guides symptom-triggered benzodiazepine dosing, reducing total benzodiazepine exposure compared to fixed-schedule protocols.",
   "bloom":"recall",
   "source":[{"book":"MGH Housestaff Manual","page":212}],
   "confusable_with":"CAGE (detects dependence, not withdrawal severity)"},
  {"id":f"{S5}-2","topic":T5,"domain":D5,"discipline":DI5,
   "stem":"What is the typical time course for major alcohol withdrawal seizures after the last drink?",
   "answer":"Alcohol withdrawal seizures typically occur within 6–48 hours of the last drink; delirium tremens (DTs) peaks at 48–72 hours.",
   "rationale":"Understanding the timeline guides monitoring intensity; patients admitted electively may develop withdrawal without history disclosure.",
   "bloom":"recall",
   "source":[{"book":"MGH Housestaff Manual","page":212}],
   "confusable_with":"Delirium tremens timeline"},
  {"id":f"{S5}-3","topic":T5,"domain":D5,"discipline":DI5,
   "stem":"A patient in severe alcohol withdrawal develops hyperthermia, tachycardia, and muscle rigidity. Which life-threatening syndrome must be excluded before attributing this to DTs?",
   "answer":"Neuroleptic malignant syndrome (NMS): develops over days, associated with antidopaminergic agents; serotonin syndrome: associated drug interactions; both can mimic severe DTs.",
   "rationale":"DTs are a diagnosis of exclusion; NMS and serotonin syndrome require different treatment and may worsen with benzodiazepines alone.",
   "bloom":"analyze",
   "source":[{"book":"Stanford CA-1","page":85}],
   "confusable_with":"Neuroleptic Malignant Syndrome, Serotonin Syndrome"},
  {"id":f"{S5}-4","topic":T5,"domain":D5,"discipline":DI5,
   "stem":"In a patient with severe alcohol withdrawal being managed with benzodiazepines, what electrolyte abnormality should be repleted to prevent refractory seizures?",
   "answer":"Magnesium deficiency is common in chronic alcohol use and must be repleted; also check and correct thiamine (before glucose), potassium, and phosphate.",
   "rationale":"Magnesium deficiency lowers the seizure threshold and blunts response to benzodiazepines; thiamine must precede glucose to prevent precipitating Wernicke encephalopathy.",
   "bloom":"apply",
   "source":[{"book":"MGH Housestaff Manual","page":212}],
   "confusable_with":""},
  {"id":f"{S5}-5","topic":T5,"domain":D5,"discipline":DI5,
   "stem":"A patient is identified as having an alcohol use disorder during a routine screening. What validated brief tool does the USPSTF recommend for screening?",
   "answer":"AUDIT-C screens for unhealthy alcohol use; CAGE detects dependence.",
   "rationale":"Brief validated instruments allow systematic identification of alcohol use disorder in primary care and inpatient settings.",
   "bloom":"recall",
   "source":[{"book":"MGH Housestaff Manual","page":212}],
   "confusable_with":"CAGE (dependence) vs AUDIT-C (unhealthy use)"},
]

# ─── ITEM 6: Approach to Altered Mental Status ────────────────────────────
T6 = "Approach to Altered Mental Status"
D6 = "Internal medicine: on-call & cross-cover (approach to the acutely changing ward patient)"
DI6 = "medicine"
S6 = slug(T6)
catalog += [
  {"id":f"{S6}-1","topic":T6,"domain":D6,"discipline":DI6,
   "stem":"A post-operative patient fails to wake up after general anesthesia. What systematic approach guides the diagnostic workup?",
   "answer":"Review medical and surgical history, drug ingestions (including anesthetic agents), physical exam, and laboratory results; consider prolonged paralysis, drug accumulation, and metabolic causes.",
   "rationale":"Delayed awakening is most commonly from residual anesthetic, opioid, or neuromuscular blocker effect; systematic review prevents missing reversible causes.",
   "bloom":"apply",
   "source":[{"book":"Morgan & Mikhail","page":351}],
   "confusable_with":""},
  {"id":f"{S6}-2","topic":T6,"domain":D6,"discipline":DI6,
   "stem":"A cirrhotic patient develops confusion. What metabolic process is the primary cause of hepatic encephalopathy?",
   "answer":"Hepatic encephalopathy results from hepatic failure to clear neurotoxins (primarily ammonia); it can alter consciousness at any stage.",
   "rationale":"Ammonia and other gut-derived toxins bypass hepatic metabolism via portosystemic shunting, directly impairing neuronal function.",
   "bloom":"recall",
   "source":[{"book":"Morgan & Mikhail","page":351}],
   "confusable_with":""},
  {"id":f"{S6}-3","topic":T6,"domain":D6,"discipline":DI6,
   "stem":"In altered mental status from neurogenic or distributive shock, what is the underlying hemodynamic mechanism that contributes to cerebral dysfunction?",
   "answer":"Distributive shock (neurogenic, anaphylactic) causes systemic vasodilation and capillary leak, reducing cerebral perfusion pressure.",
   "rationale":"Loss of sympathetic tone or massive histamine release leads to vasodilation and hypotension, impairing cerebral autoregulation.",
   "bloom":"analyze",
   "source":[{"book":"StatPearls: StatPearls   Distributive Shock (Non septic)","page":3}],
   "confusable_with":""},
  {"id":f"{S6}-4","topic":T6,"domain":D6,"discipline":DI6,
   "stem":"In a patient with AMS and known diabetes, which two metabolic emergencies must be immediately excluded at the bedside?",
   "answer":"Hypoglycemia and hyperosmotic hyperglycemic nonketotic coma; both are reversible if caught early.",
   "rationale":"Glucose check is the most immediately actionable test in any AMS patient with diabetes, as both extremes can cause rapid neurologic deterioration.",
   "bloom":"apply",
   "source":[{"book":"Morgan & Mikhail","page":351}],
   "confusable_with":""},
  {"id":f"{S6}-5","topic":T6,"domain":D6,"discipline":DI6,
   "stem":"A patient with AMS is found to have cortisol deficiency. Which induction agent is preferred if intubation is required?",
   "answer":"Ketamine or etomidate are preferred for induction in hemodynamically unstable patients; refractory hypotension should prompt consideration of coexistent primary adrenal insufficiency.",
   "rationale":"Etomidate transiently suppresses cortisol synthesis; ketamine maintains sympathetic tone; either is preferable to propofol in adrenal insufficiency with hemodynamic instability.",
   "bloom":"apply",
   "source":[{"book":"Morgan & Mikhail","page":1229}],
   "confusable_with":""},
  {"id":f"{S6}-6","topic":T6,"domain":D6,"discipline":DI6,
   "stem":"In a patient with AMS and elevated ammonia, what is the recommended treatment approach for hepatic encephalopathy?",
   "answer":"Reduce ammonia production: lactulose, rifaximin; treat precipitating factors (infection, GI bleed, constipation, electrolyte imbalance).",
   "rationale":"Lactulose acidifies colonic contents trapping ammonia as NH4+; rifaximin reduces ammonia-producing gut bacteria.",
   "bloom":"apply",
   "source":[{"book":"Morgan & Mikhail","page":1182}],
   "confusable_with":""},
]

# ─── ITEM 7: Approach to Anaphylaxis ─────────────────────────────────────
T7 = "Approach to Anaphylaxis"
D7 = "Internal medicine: on-call & cross-cover (approach to the acutely changing ward patient)"
DI7 = "medicine"
S7 = slug(T7)
catalog += [
  {"id":f"{S7}-1","topic":T7,"domain":D7,"discipline":DI7,
   "stem":"A patient develops urticaria, hypotension, and bronchospasm 5 minutes after IV contrast. What is the first-line treatment?",
   "answer":"Epinephrine IM (1:1000, 0.3–0.5 mg in adults) to the lateral thigh is the first-line treatment for anaphylaxis.",
   "rationale":"Epinephrine reverses vasodilation, bronchoconstriction, and capillary leak via alpha-1 and beta-2 adrenergic effects; delay increases mortality risk.",
   "bloom":"recall",
   "source":[{"book":"Morgan & Mikhail","page":771}],
   "confusable_with":"Antihistamines (adjunctive, not first-line)"},
  {"id":f"{S7}-2","topic":T7,"domain":D7,"discipline":DI7,
   "stem":"In a perioperative anaphylactic reaction with refractory hypotension despite initial epinephrine, what infusion strategy is described?",
   "answer":"An epinephrine infusion should be initiated; small doses of epinephrine (5–10 mcg IV boluses) are useful as a temporary inotrope/chronotrope while the infusion is prepared.",
   "rationale":"Ongoing catecholamine support is needed for sustained hemodynamic instability; IV epinephrine at low doses provides inotropic and vasopressor support.",
   "bloom":"apply",
   "source":[{"book":"Morgan & Mikhail","page":771}],
   "confusable_with":""},
  {"id":f"{S7}-3","topic":T7,"domain":D7,"discipline":DI7,
   "stem":"In an anaphylactic reaction, systemic histamine release produces hemodynamic effects similar to which other mechanism?",
   "answer":"Histamine-mediated anaphylaxis produces systemic vasodilation and capillary leak similar to distributive shock (e.g., septic shock), with potential cardiomyopathy.",
   "rationale":"Massive histamine release activates H1/H2 receptors causing vasodilation and increased vascular permeability, mimicking other distributive shock states.",
   "bloom":"analyze",
   "source":[{"book":"StatPearls: StatPearls   Distributive Shock (Non septic)","page":3}],
   "confusable_with":"Cardiogenic shock"},
  {"id":f"{S7}-4","topic":T7,"domain":D7,"discipline":DI7,
   "stem":"After initial resuscitation of anaphylaxis, what is the purpose of keeping the patient supine rather than sitting them up?",
   "answer":"Supine position maintains venous return and cardiac output; sitting up in distributive shock can precipitate cardiac arrest from loss of preload.",
   "rationale":"Anaphylaxis causes massive venodilation; orthostatic position dramatically reduces preload and can be fatal in severe reactions.",
   "bloom":"apply",
   "source":[{"book":"Morgan & Mikhail","page":771}],
   "confusable_with":""},
  {"id":f"{S7}-5","topic":T7,"domain":D7,"discipline":DI7,
   "stem":"A patient with a known latex allergy is brought emergently to the OR. What preoperative measure is most critical?",
   "answer":"Use a latex-free environment: latex-free gloves, tubing, and all equipment that may contact the patient; ensure epinephrine infusion is available.",
   "rationale":"Latex anaphylaxis occurs on contact; a latex-free environment prevents the trigger; epinephrine availability allows immediate treatment if reactions occur despite precautions.",
   "bloom":"apply",
   "source":[{"book":"Morgan & Mikhail","page":771}],
   "confusable_with":""},
  {"id":f"{S7}-6","topic":T7,"domain":D7,"discipline":DI7,
   "stem":"What is the key clinical distinction between anaphylaxis and anaphylactoid reactions in terms of mechanism?",
   "answer":"Anaphylaxis is IgE-mediated (requires prior sensitization); anaphylactoid reactions are non-IgE-mediated (direct mast cell degranulation) but clinically identical and treated the same way.",
   "rationale":"Both produce identical clinical presentations requiring the same epinephrine-based treatment; mechanism distinction matters for future allergen avoidance planning.",
   "bloom":"analyze",
   "source":[{"book":"Morgan & Mikhail","page":993}],
   "confusable_with":""},
  {"_type":"confusable_pair","topic_a":"Anaphylaxis","topic_b":"Anaphylactoid reaction","discriminator":"IgE-mediated (prior sensitization required) vs direct mast cell degranulation (no prior exposure needed); treatment is identical"},
]

# ─── ITEM 8: Approach to Aspiration Event ────────────────────────────────
T8 = "Approach to Aspiration Event"
D8 = "Internal medicine: on-call & cross-cover (approach to the acutely changing ward patient)"
DI8 = "medicine"
S8 = slug(T8)
catalog += [
  {"id":f"{S8}-1","topic":T8,"domain":D8,"discipline":DI8,
   "stem":"A patient develops fever, cough, and infiltrate 2 days after a witnessed aspiration event. What is the distinction between aspiration pneumonitis and aspiration pneumonia?",
   "answer":"Aspiration pneumonitis is a chemical injury from acidic gastric contents (not requiring antibiotics); aspiration pneumonia is bacterial infection from aspirated oropharyngeal flora (requires antibiotics).",
   "rationale":"Distinguishing between chemical and infectious aspiration directs appropriate management; unnecessary antibiotics in pneumonitis risk C. diff and resistance.",
   "bloom":"analyze",
   "source":[{"book":"StatPearls: StatPearls   Aspiration Pneumonia and Pneumonitis","page":13}],
   "confusable_with":"Aspiration pneumonia vs pneumonitis"},
  {"id":f"{S8}-2","topic":T8,"domain":D8,"discipline":DI8,
   "stem":"At extubation, what criteria confirm adequate airway protection and reduce aspiration risk?",
   "answer":"Intact gag reflex, ability to cough, oropharynx suctioned, alert and following commands; if aspiration risk, consider OG tube suction and emergence in lateral decubitus.",
   "rationale":"These criteria ensure the patient can protect the airway independently; lateral positioning uses gravity to reduce aspiration if regurgitation occurs.",
   "bloom":"apply",
   "source":[{"book":"Stanford CA-1","page":70}],
   "confusable_with":""},
  {"id":f"{S8}-3","topic":T8,"domain":D8,"discipline":DI8,
   "stem":"A patient with post-tonsillectomy bleeding requires emergency re-operation. How does the risk of aspiration change management of induction?",
   "answer":"Rapid-sequence induction with cricoid pressure is mandated; these patients have a stomach full of blood and are at high aspiration risk.",
   "rationale":"Swallowed blood from tonsil hemorrhage fills the stomach; RSI avoids passive regurgitation during the apneic induction period.",
   "bloom":"apply",
   "source":[{"book":"Miller/Baby Miller","page":579}],
   "confusable_with":""},
  {"id":f"{S8}-4","topic":T8,"domain":D8,"discipline":DI8,
   "stem":"In patients with dysphagia at risk for aspiration, what multilevel support has been shown to decrease aspiration pneumonia risk and hospital readmissions?",
   "answer":"Multilevel support including nutritionists, speech-language pathologists, physical therapists, and nurses; regular dysphagia screening is essential.",
   "rationale":"Dysphagia increases aspiration pneumonia rate from 3.67 to 6.7 per 100 person-years; coordinated multidisciplinary management reduces this risk.",
   "bloom":"recall",
   "source":[{"book":"StatPearls: StatPearls   Aspiration Pneumonia and Pneumonitis","page":13}],
   "confusable_with":""},
  {"id":f"{S8}-5","topic":T8,"domain":D8,"discipline":DI8,
   "stem":"A pregnant trauma patient has reduced FRC and lower esophageal sphincter incompetence. Why does this dramatically increase aspiration risk?",
   "answer":"Reduced FRC causes rapid desaturation during apnea; lower esophageal sphincter incompetence increases risk of passive regurgitation—both increase aspiration risk requiring RSI.",
   "rationale":"These physiologic changes in pregnancy mandate treating all pregnant trauma patients as full-stomach with RSI regardless of fasting status.",
   "bloom":"analyze",
   "source":[{"book":"Miller/Baby Miller","page":815}],
   "confusable_with":""},
  {"id":f"{S8}-6","topic":T8,"domain":D8,"discipline":DI8,
   "stem":"Following an aspiration event in a patient with OSA, what additional monitoring consideration is important?",
   "answer":"OSA patients have critical events including aspiration-related hypoxia; they require close monitoring of oxygenation and airway patency post-event.",
   "rationale":"OSA patients are at higher risk of upper airway obstruction post-sedation; aspiration combined with OSA significantly elevates post-event hypoxia risk.",
   "bloom":"apply",
   "source":[{"book":"Miller/Baby Miller","page":887}],
   "confusable_with":""},
]

# ─── ITEM 9: Approach to Bradycardia ─────────────────────────────────────
T9 = "Approach to Bradycardia"
D9 = "Internal medicine: on-call & cross-cover (approach to the acutely changing ward patient)"
DI9 = "medicine"
S9 = slug(T9)
catalog += [
  {"id":f"{S9}-1","topic":T9,"domain":D9,"discipline":DI9,
   "stem":"A patient develops sudden bradycardia during eye surgery. What is this reflex called, and what is the first management step?",
   "answer":"Oculocardiac reflex (OCR): immediately notify surgeon to stop stimulation and wait for heart rate to recover; confirm adequate ventilation, oxygenation, and anesthetic depth.",
   "rationale":"OCR is triggered by traction on extraocular muscles; cessation of stimulus is the first and usually definitive intervention.",
   "bloom":"apply",
   "source":[{"book":"Morgan & Mikhail","page":1252}],
   "confusable_with":""},
  {"id":f"{S9}-2","topic":T9,"domain":D9,"discipline":DI9,
   "stem":"If bradycardia persists after cessation of surgical stimulation during eye surgery, what is the next pharmacologic intervention?",
   "answer":"Administer IV atropine 10 mcg/kg; if refractory, infiltrate rectus muscles with local anesthetic.",
   "rationale":"Atropine blocks the efferent vagal limb of the OCR; local anesthetic injection eliminates the afferent trigger.",
   "bloom":"apply",
   "source":[{"book":"Morgan & Mikhail","page":1252}],
   "confusable_with":""},
  {"id":f"{S9}-3","topic":T9,"domain":D9,"discipline":DI9,
   "stem":"In a child who develops cardiac arrest after succinylcholine administration for emergency intubation, what electrolyte abnormality should be immediately treated?",
   "answer":"Hyperkalemia: succinylcholine causes acute potassium release; treat immediately with calcium, bicarbonate, glucose/insulin, and beta-agonists; prolonged resuscitation may be required.",
   "rationale":"Children are more susceptible to succinylcholine-induced hyperkalemia and cardiac arrhythmias; cardiac arrest from succinylcholine in children mandates hyperkalemia treatment.",
   "bloom":"apply",
   "source":[{"book":"Morgan & Mikhail","page":1458}],
   "confusable_with":""},
  {"id":f"{S9}-4","topic":T9,"domain":D9,"discipline":DI9,
   "stem":"In a patient with aortic stenosis requiring anesthesia, why is bradycardia particularly dangerous?",
   "answer":"Slow heart rates decrease cardiac output in obstructive lesions; the optimal heart rate avoids both extremes—slow rates decrease output, fast rates impair ventricular filling.",
   "rationale":"AS patients have fixed outflow obstruction; cardiac output is heart-rate-dependent, making both brady- and tachycardia hazardous.",
   "bloom":"analyze",
   "source":[{"book":"Morgan & Mikhail","page":761}],
   "confusable_with":""},
  {"id":f"{S9}-5","topic":T9,"domain":D9,"discipline":DI9,
   "stem":"In an ACLS non-shockable rhythm scenario, an end-tidal CO2 below what threshold after 20 minutes of ALS resuscitation strongly predicts futility?",
   "answer":"EtCO2 below 10 mm Hg after 20 minutes of ALS resuscitation strongly predicts futility in intubated patients.",
   "rationale":"EtCO2 reflects cardiac output; persistently low EtCO2 indicates inadequate cardiac output and near-zero chance of ROSC.",
   "bloom":"recall",
   "source":[{"book":"StatPearls: StatPearls   ACLS  Non Shockable Rhythms (PEA & Asystole)","page":12}],
   "confusable_with":""},
  {"id":f"{S9}-6","topic":T9,"domain":D9,"discipline":DI9,
   "stem":"A ward patient with complete heart block and symptomatic bradycardia (HR 32, hypotensive) is awaiting pacemaker insertion. What is the immediate pharmacologic bridge?",
   "answer":"Atropine IV (0.5–1 mg) is first-line; if unresponsive, transcutaneous pacing or dopamine/epinephrine infusion as bridge to transvenous pacing.",
   "rationale":"Atropine blocks vagal tone and is effective for AV nodal block; it is less effective for infranodal (His-Purkinje) block requiring pacing.",
   "bloom":"apply",
   "source":[{"book":"Morgan & Mikhail","page":761}],
   "confusable_with":""},
]

# ─── ITEM 10: Approach to Chest Pain ─────────────────────────────────────
T10 = "Approach to Chest Pain"
D10 = "Internal medicine: on-call & cross-cover (approach to the acutely changing ward patient)"
DI10 = "medicine"
S10 = slug(T10)
catalog += [
  {"id":f"{S10}-1","topic":T10,"domain":D10,"discipline":DI10,
   "stem":"On cross-cover for a patient with new chest pain, what is the immediate first step before detailed workup?",
   "answer":"Assess hemodynamic stability; obtain ECG and determine if this is a STEMI or unstable presentation requiring emergent activation.",
   "rationale":"Life-threatening etiologies (STEMI, aortic dissection, tension pneumothorax, PE) must be excluded before a systematic detailed workup.",
   "bloom":"apply",
   "source":[{"book":"Intern Notes / Survival Guide","page":9}],
   "confusable_with":""},
  {"id":f"{S10}-2","topic":T10,"domain":D10,"discipline":DI10,
   "stem":"Which cardiac history features raise the pretest probability of an ischemic cause for chest pain?",
   "answer":"Known CAD, prior MI, ECG changes, congestive heart failure, DM, age >65, hypertension, hyperlipidemia, smoking, family history, PVD.",
   "rationale":"Rapid risk stratification using known risk factors guides urgency of cardiac biomarkers, ECG, and cardiology consultation.",
   "bloom":"recall",
   "source":[{"book":"Intern Notes / Survival Guide","page":9}],
   "confusable_with":""},
  {"id":f"{S10}-3","topic":T10,"domain":D10,"discipline":DI10,
   "stem":"In the ACC/AHA stepwise approach to perioperative cardiac risk, when should a patient with known CAD proceed directly to surgery without further cardiac workup?",
   "answer":"If surgery is emergent, proceed with appropriate monitoring based on clinical assessment; emergent cases bypass non-emergent cardiac evaluation.",
   "rationale":"Emergency surgery overrides elective cardiac workup; clinical assessment and intraoperative monitoring substitute for preoperative testing.",
   "bloom":"apply",
   "source":[{"book":"Morgan & Mikhail","page":622}],
   "confusable_with":""},
  {"id":f"{S10}-4","topic":T10,"domain":D10,"discipline":DI10,
   "stem":"A patient with coronary stenosis of 70% is asymptomatic at rest but develops angina with exertion. What physiologic explanation underlies this pattern?",
   "answer":"At 70% stenosis, maximum compensatory distal vasodilation is present; flow is adequate at rest but inadequate when metabolic demand increases.",
   "rationale":"Flow reserve is exhausted at high-grade stenosis; exercise-induced demand unmasks the supply-demand mismatch causing symptoms.",
   "bloom":"analyze",
   "source":[{"book":"Morgan & Mikhail","page":636}],
   "confusable_with":""},
  {"id":f"{S10}-5","topic":T10,"domain":D10,"discipline":DI10,
   "stem":"A patient with abdominal pain is found to have an acute MI as the cause. What makes 'image-negative' abdominal pain a pitfall in chest pain workup?",
   "answer":"Acute MI can present as epigastric or abdominal pain; metabolic causes (DKA, hypercalcemia, uremia) and cardiac ischemia must always be included in the differential for abdominal pain.",
   "rationale":"Inferior MI commonly refers pain to the epigastrium; missing an MI due to 'atypical' presentation is a high-stakes error.",
   "bloom":"analyze",
   "source":[{"book":"MGH Housestaff Manual","page":72}],
   "confusable_with":""},
  {"id":f"{S10}-6","topic":T10,"domain":D10,"discipline":DI10,
   "stem":"The conditions classified as major cardiac risk (ACC/AHA) that warrant intensive management prior to all but emergency surgery include which three?",
   "answer":"Unstable coronary syndromes, decompensated heart failure, significant arrhythmias, and severe valvular disease—these require intensive management before elective surgery.",
   "rationale":"These conditions carry high perioperative mortality and may benefit from optimization or delay of surgery.",
   "bloom":"recall",
   "source":[{"book":"Morgan & Mikhail","page":619}],
   "confusable_with":""},
]

# ─── ITEM 11: Approach to Delirium in the Elderly ────────────────────────
T11 = "Approach to Delirium in the Elderly"
D11 = "Internal medicine: on-call & cross-cover (approach to the acutely changing ward patient)"
DI11 = "medicine"
S11 = slug(T11)
catalog += [
  {"id":f"{S11}-1","topic":T11,"domain":D11,"discipline":DI11,
   "stem":"An 80-year-old post-op patient becomes acutely confused. Which validated tool is used to formally diagnose delirium?",
   "answer":"Confusion Assessment Method (CAM) is the standard tool for diagnosing delirium; Riker Sedation Agitation Scale is used in ICU settings.",
   "rationale":"CAM identifies the four key features: acute onset with fluctuating course, inattention, disorganized thinking, altered level of consciousness.",
   "bloom":"recall",
   "source":[{"book":"Miller/Baby Miller","page":682}],
   "confusable_with":"Mini-Mental State Exam (MMSE, screens for cognitive impairment, not delirium per se)"},
  {"id":f"{S11}-2","topic":T11,"domain":D11,"discipline":DI11,
   "stem":"Which subtype of postoperative delirium carries the worst prognosis for subsequent morbidity and mortality?",
   "answer":"Hypoactive delirium carries the worst prognosis; it is often unrecognized compared to hyperactive (agitated) delirium.",
   "rationale":"Hypoactive delirium presents as lethargy and withdrawal rather than agitation, leading to delayed recognition and intervention.",
   "bloom":"recall",
   "source":[{"book":"Miller/Baby Miller","page":682}],
   "confusable_with":"Hyperactive delirium (more visible, but better prognosis)"},
  {"id":f"{S11}-3","topic":T11,"domain":D11,"discipline":DI11,
   "stem":"What is the single strongest predictor for postoperative delirium?",
   "answer":"Preexisting cognitive impairment is the strongest predictor; other risk factors include advanced age, multiple comorbidities, frailty, higher ASA score, and prolonged mechanical ventilation.",
   "rationale":"Pre-existing cognitive reserve is protective; its absence markedly increases vulnerability to the metabolic and pharmacologic insults of surgery.",
   "bloom":"recall",
   "source":[{"book":"Miller/Baby Miller","page":682}],
   "confusable_with":""},
  {"id":f"{S11}-4","topic":T11,"domain":D11,"discipline":DI11,
   "stem":"In elderly patients, which two opioids should be avoided because of delirium-promoting metabolites or anticholinergic effects?",
   "answer":"Meperidine (normeperidine accumulation + anticholinergic effects → delirium) and morphine (morphine-6-glucuronide accumulates in renal impairment).",
   "rationale":"Active metabolites of meperidine and morphine accumulate in elderly with renal impairment; fentanyl has no active metabolites and is preferred.",
   "bloom":"recall",
   "source":[{"book":"Miller/Baby Miller","page":675}],
   "confusable_with":""},
  {"id":f"{S11}-5","topic":T11,"domain":D11,"discipline":DI11,
   "stem":"How does delirium differ from dementia in terms of the key distinguishing clinical feature?",
   "answer":"Delirium: acute onset with fluctuating course, impaired attention; dementia: gradual onset, relatively stable course (unless superimposed delirium), memory predominant.",
   "rationale":"Delirium and dementia frequently coexist in the elderly; the acute fluctuating course distinguishes delirium as an emergency requiring workup.",
   "bloom":"analyze",
   "source":[{"book":"StatPearls: StatPearls   Delirium  Diagnosis, Subtypes & Assessment","page":1}],
   "confusable_with":"Dementia"},
  {"id":f"{S11}-6","topic":T11,"domain":D11,"discipline":DI11,
   "stem":"In a non-verbal elderly patient with delirium-like behavior, what commonly overlooked reversible causes should be addressed first?",
   "answer":"Urinary retention, constipation, pain, hunger/thirst, and communication breakdowns—all can precipitate agitation/delirium in non-verbal patients.",
   "rationale":"Physical discomfort from retention or constipation is a common precipitant in patients who cannot verbalize; addressing these reverses the behavior.",
   "bloom":"apply",
   "source":[{"book":"MGH Housestaff Manual","page":206}],
   "confusable_with":""},
  {"_type":"confusable_pair","topic_a":"Delirium","topic_b":"Dementia","discriminator":"Acute fluctuating onset with inattention (delirium) vs gradual progressive memory loss with stable course (dementia); delirium requires urgent workup"},
]

# ─── ITEM 12: Approach to Hyperkalemia ───────────────────────────────────
T12 = "Approach to Hyperkalemia"
D12 = "Internal medicine: on-call & cross-cover (approach to the acutely changing ward patient)"
DI12 = "medicine"
S12 = slug(T12)
catalog += [
  {"id":f"{S12}-1","topic":T12,"domain":D12,"discipline":DI12,
   "stem":"A patient has a potassium of 6.8 mEq/L with peaked T-waves on ECG. What is the first priority intervention?",
   "answer":"Calcium gluconate/chloride IV to stabilize the cardiac membrane (cardioprotection); this does not lower potassium but prevents fatal arrhythmia.",
   "rationale":"Calcium antagonizes the membrane effects of hyperkalemia immediately; it is followed by agents to shift K+ intracellularly and then eliminate total body K+.",
   "bloom":"apply",
   "source":[{"book":"Stanford CA-1","page":58}],
   "confusable_with":"Sodium bicarbonate (shifts K+ but is not first priority over membrane stabilization)"},
  {"id":f"{S12}-2","topic":T12,"domain":D12,"discipline":DI12,
   "stem":"Which agent promotes intracellular shift of potassium via beta-2 adrenergic receptor activation?",
   "answer":"Beta-2 agonists (e.g., albuterol, low-dose epinephrine) activate Na+-K+-ATPase via beta-2 receptors, shifting K+ into muscle and liver cells.",
   "rationale":"Beta-2 stimulation increases intracellular K+ uptake; alpha-adrenergic activity conversely impairs this shift.",
   "bloom":"recall",
   "source":[{"book":"Morgan & Mikhail","page":1877}],
   "confusable_with":"Alpha-adrenergic agonists (worsen hyperkalemia)"},
  {"id":f"{S12}-3","topic":T12,"domain":D12,"discipline":DI12,
   "stem":"What is the definitive treatment for removing excess total body potassium in a patient with impaired kidney function?",
   "answer":"Dialysis is the definitive treatment for total body potassium removal in patients with impaired kidney function.",
   "rationale":"Loop diuretics work for patients with adequate renal function; dialysis is required when kidneys cannot excrete the potassium load.",
   "bloom":"recall",
   "source":[{"book":"Morgan & Mikhail","page":1887}],
   "confusable_with":"Loop diuretics (only effective with adequate renal function)"},
  {"id":f"{S12}-4","topic":T12,"domain":D12,"discipline":DI12,
   "stem":"A patient receives old packed red blood cells during massive transfusion and develops hyperkalemia. How does the K+ level of old PRBCs contribute?",
   "answer":"Old PRBCs have potassium concentrations of 50 mEq/L or greater due to cellular K+ leak during storage; large-volume transfusion delivers a significant K+ load.",
   "rationale":"RBC membranes become leaky with storage; transfusing large volumes of old blood delivers an acute potassium load especially dangerous with impaired renal clearance.",
   "bloom":"analyze",
   "source":[{"book":"Stanford CA-1","page":58}],
   "confusable_with":""},
  {"id":f"{S12}-5","topic":T12,"domain":D12,"discipline":DI12,
   "stem":"Which ECG changes progress in order with worsening hyperkalemia from mild to severe?",
   "answer":"Mild (5.5–6.5): peaked T waves; moderate (6.6–7.5): PR prolongation, QRS widening; severe (>7.5): sine wave pattern, VF/asystole.",
   "rationale":"Progressive hyperkalemia depolarizes resting membrane potential, slowing conduction and ultimately causing fatal arrhythmias.",
   "bloom":"recall",
   "source":[{"book":"Stanford CA-1","page":58}],
   "confusable_with":""},
  {"id":f"{S12}-6","topic":T12,"domain":D12,"discipline":DI12,
   "stem":"A patient with hyperkalemia has a plasma osmolality increase from acute hyperglycemia. By how much does plasma K+ rise per 10 mOsm/L increase in osmolality?",
   "answer":"Plasma K+ rises approximately 0.6 mEq/L per 10 mOsm/L increase in osmolality (water exits cells carrying K+ out).",
   "rationale":"Hyperosmolality drives water out of cells down its gradient; intracellular K+ follows, raising plasma concentrations transiently.",
   "bloom":"recall",
   "source":[{"book":"Morgan & Mikhail","page":1877}],
   "confusable_with":""},
]

print(f"Items 0-12 built: {len(catalog)} entries so far")

# ─── ITEM 13: Approach to Hypertensive Emergency ─────────────────────────
T13 = "Approach to Hypertensive Emergency"
D13 = "Internal medicine: on-call & cross-cover (approach to the acutely changing ward patient)"
DI13 = "medicine"
S13 = slug(T13)
catalog += [
  {"id":f"{S13}-1","topic":T13,"domain":D13,"discipline":DI13,
   "stem":"What is the definition of hypertensive urgency, and how does it differ from hypertensive emergency?",
   "answer":"Hypertensive urgency: marked BP elevation (SBP >180 or DBP >120) WITHOUT target organ damage. Emergency: same BP range WITH acute target organ damage (pulmonary edema, cardiac ischemia, neurologic deficits, acute renal failure).",
   "rationale":"The distinction drives management: emergency requires IV agents and controlled BP reduction in ICU; urgency can be managed with oral agents over hours.",
   "bloom":"recall",
   "source":[{"book":"StatPearls: StatPearls   Hypertensive Urgency and Emergency","page":1}],
   "confusable_with":"Hypertensive urgency"},
  {"id":f"{S13}-2","topic":T13,"domain":D13,"discipline":DI13,
   "stem":"In a hypertensive emergency with acute ischemic stroke, why is rapid blood pressure lowering potentially harmful?",
   "answer":"Rapid BP reduction in acute ischemic stroke can extend the ischemic penumbra; cerebral autoregulation is impaired and BP reduction decreases perfusion to at-risk tissue.",
   "rationale":"Autoregulation shifts rightward in chronic hypertension; abrupt reduction below the new autoregulatory floor worsens ischemia in the penumbra.",
   "bloom":"analyze",
   "source":[{"book":"StatPearls: StatPearls   Hypertensive Urgency and Emergency","page":1}],
   "confusable_with":""},
  {"id":f"{S13}-3","topic":T13,"domain":D13,"discipline":DI13,
   "stem":"A patient with hypertensive urgency (SBP 190, no organ damage) is admitted. What is the appropriate rate of blood pressure reduction?",
   "answer":"Gradual reduction over 24–48 hours with oral agents; avoid rapid IV lowering as this can cause ischemic events in a system accustomed to higher pressures.",
   "rationale":"Chronic hypertension shifts cerebral autoregulation; abrupt reduction can cause cerebral ischemia even without a 'hypertensive emergency' target organ crisis.",
   "bloom":"apply",
   "source":[{"book":"StatPearls: StatPearls   Hypertensive Urgency and Emergency","page":1}],
   "confusable_with":"Hypertensive emergency management"},
  {"id":f"{S13}-4","topic":T13,"domain":D13,"discipline":DI13,
   "stem":"Despite no acute organ damage, hypertensive urgency warrants attention because of what long-term risk?",
   "answer":"Hypertensive urgencies are associated with a higher incidence of adverse cardiovascular events over the long term and warrant nuanced follow-up management.",
   "rationale":"Even without acute organ damage, sustained hypertension accelerates atherosclerosis, LV hypertrophy, and CKD progression.",
   "bloom":"recall",
   "source":[{"book":"StatPearls: StatPearls   Hypertensive Urgency and Emergency","page":1}],
   "confusable_with":""},
  {"id":f"{S13}-5","topic":T13,"domain":D13,"discipline":DI13,
   "stem":"A patient with pheochromocytoma presents with paroxysmal severe hypertension. What is the classic triad?",
   "answer":"Classic triad: paroxysmal headaches (from hypertension), tachycardia, and diaphoresis.",
   "rationale":"Pheo causes episodic catecholamine release; the triad has high specificity and should prompt measurement of plasma metanephrines.",
   "bloom":"recall",
   "source":[{"book":"Miller/Baby Miller","page":551}],
   "confusable_with":""},
  {"id":f"{S13}-6","topic":T13,"domain":D13,"discipline":DI13,
   "stem":"In a patient with hypertensive emergency and suspected aortic dissection, which BP target is most appropriate and what is the primary goal?",
   "answer":"Target SBP <120 mmHg and HR <60 bpm using IV labetalol or esmolol; reducing shear stress on the dissection is the primary goal.",
   "rationale":"Rate of pressure rise (dP/dt) drives propagation of aortic dissection; beta-blockade reduces both heart rate and force of ventricular ejection.",
   "bloom":"apply",
   "source":[{"book":"Morgan & Mikhail","page":778}],
   "confusable_with":""},
  {"_type":"confusable_pair","topic_a":"Hypertensive emergency","topic_b":"Hypertensive urgency","discriminator":"Presence of acute target organ damage (encephalopathy, cardiac ischemia, renal failure, retinal hemorrhage) defines emergency; absence defines urgency"},
]

# ─── ITEM 14: Approach to Hypoglycemia ───────────────────────────────────
T14 = "Approach to Hypoglycemia"
D14 = "Internal medicine: on-call & cross-cover (approach to the acutely changing ward patient)"
DI14 = "medicine"
S14 = slug(T14)
catalog += [
  {"id":f"{S14}-1","topic":T14,"domain":D14,"discipline":DI14,
   "stem":"What plasma glucose concentration defines hypoglycemia, and below what level do symptoms typically manifest?",
   "answer":"Hypoglycemia: plasma glucose <70 mg/dL; symptoms typically begin below 55 mg/dL.",
   "rationale":"Whipple's triad (symptoms + low glucose + symptom relief with glucose) defines clinical hypoglycemia; the 70 mg/dL threshold prompts treatment even before symptoms.",
   "bloom":"recall",
   "source":[{"book":"StatPearls: StatPearls   Hypoglycemia","page":1}],
   "confusable_with":""},
  {"id":f"{S14}-2","topic":T14,"domain":D14,"discipline":DI14,
   "stem":"What are the three components of Whipple's triad for diagnosing hypoglycemia?",
   "answer":"(1) Symptoms consistent with hypoglycemia; (2) low blood glucose measurement; (3) relief of symptoms with glucose administration.",
   "rationale":"Whipple's triad (described in 1938) remains the clinical standard; it distinguishes true hypoglycemia from glucose measurement artifact.",
   "bloom":"recall",
   "source":[{"book":"StatPearls: StatPearls   Hypoglycemia","page":1}],
   "confusable_with":""},
  {"id":f"{S14}-3","topic":T14,"domain":D14,"discipline":DI14,
   "stem":"A diabetic patient has recurring hypoglycemic episodes requiring ER visits. What medication class adjustments should be considered?",
   "answer":"Adjust insulin regimen, oral hypoglycemics (sulfonylureas are high-risk), meal plan, and exercise schedule; frequent hypoglycemia may indicate hypoglycemia unawareness.",
   "rationale":"Recurrent hypoglycemia blunts counterregulatory responses (hypoglycemia unawareness), markedly increasing mortality risk.",
   "bloom":"apply",
   "source":[{"book":"StatPearls: StatPearls   Hypoglycemia","page":6}],
   "confusable_with":""},
  {"id":f"{S14}-4","topic":T14,"domain":D14,"discipline":DI14,
   "stem":"What are the most serious neurological consequences of untreated severe hypoglycemia?",
   "answer":"Seizures, permanent brain damage, coma, and death; severe prolonged hypoglycemia is correlated with increased mortality in diabetics.",
   "rationale":"Neurons depend on glucose as their primary fuel; prolonged deficiency causes irreversible excitotoxic injury.",
   "bloom":"recall",
   "source":[{"book":"StatPearls: StatPearls   Hypoglycemia","page":6}],
   "confusable_with":""},
  {"id":f"{S14}-5","topic":T14,"domain":D14,"discipline":DI14,
   "stem":"In a critically ill septic patient with hypoglycemia, what makes this particularly dangerous compared to stable diabetic hypoglycemia?",
   "answer":"Hypoglycemia in sepsis impairs immune response and causes neurologic complications; it is associated with significantly increased ICU mortality.",
   "rationale":"Sepsis creates high metabolic demand; hypoglycemia on top of sepsis impairs both immune function and end-organ perfusion.",
   "bloom":"analyze",
   "source":[{"book":"Curated Units","page":0}],
   "confusable_with":""},
  {"id":f"{S14}-6","topic":T14,"domain":D14,"discipline":DI14,
   "stem":"Patients with diabetes are prone to which two metabolic extremes that can both present with altered mental status?",
   "answer":"Hypoglycemia and hyperosmotic hyperglycemic nonketotic (HHNK) coma; both can cause AMS and must be distinguished by point-of-care glucose.",
   "rationale":"HHNK presents with extreme hyperglycemia and profound dehydration without significant ketosis; treatment is opposite to hypoglycemia management.",
   "bloom":"apply",
   "source":[{"book":"Morgan & Mikhail","page":351}],
   "confusable_with":"DKA"},
]

# ─── ITEM 15: Approach to Hypotension ────────────────────────────────────
T15 = "Approach to Hypotension"
D15 = "Internal medicine: on-call & cross-cover (approach to the acutely changing ward patient)"
DI15 = "medicine"
S15 = slug(T15)
catalog += [
  {"id":f"{S15}-1","topic":T15,"domain":D15,"discipline":DI15,
   "stem":"A ward patient develops sudden hypotension. What are the four main mechanistic categories to systematically evaluate?",
   "answer":"(1) Hypovolemia; (2) distributive/vasodilatory (sepsis, anaphylaxis, neuraxial block); (3) cardiogenic; (4) obstructive (tension pneumothorax, tamponade, massive PE).",
   "rationale":"Categorizing the mechanism directs specific treatment: fluids for hypovolemia, vasopressors for distributive, inotropes for cardiogenic, decompression for obstructive.",
   "bloom":"apply",
   "source":[{"book":"Morgan & Mikhail","page":2116}],
   "confusable_with":""},
  {"id":f"{S15}-2","topic":T15,"domain":D15,"discipline":DI15,
   "stem":"In hypovolemic shock, what clinical signs typically accompany hypotension?",
   "answer":"Tachycardia, tachypnea, mottled skin, decreased urine output; tachycardia may not be reliable in elderly or beta-blocked patients.",
   "rationale":"Compensatory sympathetic activation produces these signs; absence of tachycardia does not exclude hypovolemia in beta-blocked patients.",
   "bloom":"recall",
   "source":[{"book":"Miller/Baby Miller","page":729}],
   "confusable_with":""},
  {"id":f"{S15}-3","topic":T15,"domain":D15,"discipline":DI15,
   "stem":"In septic hypotension, what is the initial volume resuscitation approach?",
   "answer":"500 mL bolus infusions of crystalloid every 30 minutes to achieve the desired CVP; vasopressors are added if MAP does not reach target despite adequate volume.",
   "rationale":"Sepsis causes relative hypovolemia from capillary leak and vasodilation; crystalloid boluses restore intravascular volume while vasopressors address vasodilation.",
   "bloom":"apply",
   "source":[{"book":"Marino ICU Book","page":544}],
   "confusable_with":""},
  {"id":f"{S15}-4","topic":T15,"domain":D15,"discipline":DI15,
   "stem":"Hypotension from neuraxial (spinal/epidural) anesthesia results from which two hemodynamic mechanisms?",
   "answer":"Arterial vasodilation AND venous pooling of blood, reducing the effective circulating volume.",
   "rationale":"Neuraxial blockade sympatholysis prevents vasoconstriction and causes venous pooling, markedly reducing preload and SVR.",
   "bloom":"recall",
   "source":[{"book":"Morgan & Mikhail","page":2116}],
   "confusable_with":""},
  {"id":f"{S15}-5","topic":T15,"domain":D15,"discipline":DI15,
   "stem":"In a patient with hypotension and a low stroke volume from decreased PCOP/LVEDP, what is the clinical interpretation and first treatment?",
   "answer":"Low SV + low PCOP = hypovolemia; treat with volume administration.",
   "rationale":"PA catheter hemodynamics distinguish hypovolemic (low PCOP, low SV) from cardiogenic (high PCOP, low SV) shock, directing appropriate therapy.",
   "bloom":"apply",
   "source":[{"book":"Morgan & Mikhail","page":157}],
   "confusable_with":"Cardiogenic shock (high PCOP, low SV)"},
  {"id":f"{S15}-6","topic":T15,"domain":D15,"discipline":DI15,
   "stem":"Hypotension from tension pneumothorax or cardiac tamponade shares which common hemodynamic mechanism?",
   "answer":"Impaired venous return to the right atrium (obstructive shock); treatment is immediate decompression, not fluids or vasopressors.",
   "rationale":"External compression prevents diastolic filling; decompression (needle/finger thoracostomy for tension PTX; pericardiocentesis for tamponade) is curative.",
   "bloom":"recall",
   "source":[{"book":"Morgan & Mikhail","page":2116}],
   "confusable_with":"Hypovolemic shock"},
]

# ─── ITEM 16: Approach to Hypoxia and Desaturation ───────────────────────
T16 = "Approach to Hypoxia and Desaturation"
D16 = "Internal medicine: on-call & cross-cover (approach to the acutely changing ward patient)"
DI16 = "medicine"
S16 = slug(T16)
catalog += [
  {"id":f"{S16}-1","topic":T16,"domain":D16,"discipline":DI16,
   "stem":"A mechanically ventilated patient has new desaturation. What is the mnemonic approach to the differential diagnosis?",
   "answer":"DOPE: Displacement of ETT, Obstruction of ETT, Pneumothorax, Equipment failure; assess each systematically.",
   "rationale":"DOPE provides a structured approach to new hypoxia in a ventilated patient, prioritizing immediately life-threatening causes first.",
   "bloom":"apply",
   "source":[{"book":"Miller/Baby Miller","page":292}],
   "confusable_with":""},
  {"id":f"{S16}-2","topic":T16,"domain":D16,"discipline":DI16,
   "stem":"In a pregnant patient with acute hypoxia requiring intubation, what physiologic change makes desaturation occur faster than in a non-pregnant patient?",
   "answer":"Reduced FRC from upward displacement of the diaphragm by the gravid uterus leads to relatively rapid desaturation during apnea.",
   "rationale":"FRC is the oxygen reservoir during apnea; reduced FRC means less oxygen available during the intubation attempt.",
   "bloom":"analyze",
   "source":[{"book":"Miller/Baby Miller","page":815}],
   "confusable_with":""},
  {"id":f"{S16}-3","topic":T16,"domain":D16,"discipline":DI16,
   "stem":"In an ILD patient with unexplained nocturnal desaturation and daytime somnolence, what co-morbidity should be screened for?",
   "answer":"Obstructive sleep apnea: complicates up to two-thirds of ILD patients, causing nocturnal hypoxia, poor sleep quality, and exacerbation of pulmonary hypertension.",
   "rationale":"OSA and ILD frequently co-exist; CPAP treatment of OSA can improve daytime function and prevent pulmonary hypertension progression.",
   "bloom":"apply",
   "source":[{"book":"StatPearls: StatPearls   Non IPF Interstitial Lung Diseases","page":20}],
   "confusable_with":""},
  {"id":f"{S16}-4","topic":T16,"domain":D16,"discipline":DI16,
   "stem":"In ARDS management, what two parameters define the lung-protective ventilation strategy for hypoxia?",
   "answer":"Tidal volume ≤6 mL/kg predicted body weight AND plateau pressure <30 cm H2O.",
   "rationale":"These parameters prevent VILI (ventilator-induced lung injury) by avoiding alveolar overdistension and high driving pressures.",
   "bloom":"recall",
   "source":[{"book":"StatPearls: StatPearls   Lactic Acidosis","page":8}],
   "confusable_with":""},
  {"id":f"{S16}-5","topic":T16,"domain":D16,"discipline":DI16,
   "stem":"A patient has hypoxia with a PaO2:FiO2 ratio of 250. How is this classified, and what does the term 'acute lung injury' require?",
   "answer":"PaO2:FiO2 ≤300 = acute lung injury; PaO2:FiO2 <200 with bilateral infiltrates and no cardiac cause = ARDS.",
   "rationale":"Berlin criteria define ARDS severity by PaO2:FiO2 ratio; the threshold guides escalation to prone positioning and other rescue therapies.",
   "bloom":"recall",
   "source":[{"book":"Morgan & Mikhail","page":2130}],
   "confusable_with":""},
  {"id":f"{S16}-6","topic":T16,"domain":D16,"discipline":DI16,
   "stem":"What is the maximum duration that 100% oxygen is generally considered safe in clinical practice, and why is prolonged high FiO2 dangerous?",
   "answer":"100% O2 for up to 10–20 hours is generally considered safe; FiO2 >50–60% for longer periods risks pulmonary O2 toxicity from reactive oxygen species.",
   "rationale":"Reactive oxygen metabolites (superoxide, hydroxyl ions, hydrogen peroxide) damage DNA, proteins, and lipid membranes, causing pulmonary toxicity.",
   "bloom":"recall",
   "source":[{"book":"Morgan & Mikhail","page":2176}],
   "confusable_with":""},
]

# ─── ITEM 17: Approach to Seizure ────────────────────────────────────────
T17 = "Approach to Seizure"
D17 = "Internal medicine: on-call & cross-cover (approach to the acutely changing ward patient)"
DI17 = "medicine"
S17 = slug(T17)
# Chunks for item 17 are mostly off-topic (regional anesthesia, PONV, pediatric congenital).
# Use only what is genuinely relevant: cerebral autoregulation context and general seizure workup.
catalog += [
  {"id":f"{S17}-1","topic":T17,"domain":D17,"discipline":DI17,
   "stem":"A patient develops a generalized tonic-clonic seizure on the ward. What is the first priority in management?",
   "answer":"Protect the airway and ensure patient safety; position laterally (recovery position), time the seizure, and administer benzodiazepine if seizure persists >5 minutes.",
   "rationale":"Most seizures self-terminate within 1–2 minutes; airway protection and timing guide the decision to intervene pharmacologically.",
   "bloom":"apply",
   "source":[{"book":"MGH Housestaff Manual","page":23}],
   "confusable_with":""},
  {"id":f"{S17}-2","topic":T17,"domain":D17,"discipline":DI17,
   "stem":"A patient has a seizure following elective surgery. What is the most important immediate metabolic check?",
   "answer":"Check blood glucose immediately; hypoglycemia is the most rapidly reversible cause of seizure and must be excluded at once.",
   "rationale":"Glucose is the brain's primary fuel; hypoglycemia-induced seizures are completely reversible with prompt glucose administration.",
   "bloom":"apply",
   "source":[{"book":"Morgan & Mikhail","page":351}],
   "confusable_with":""},
  {"id":f"{S17}-3","topic":T17,"domain":D17,"discipline":DI17,
   "stem":"Seizure activity is listed in anesthesia references as suppressible by barbiturates. In what specific context are barbiturates used to control seizures intraoperatively?",
   "answer":"Barbiturates suppress seizure activity and reduce ICP; they are used during neurosurgery for cerebral protection and to suppress EEG seizure activity to the burst-suppression endpoint.",
   "rationale":"Maximal CMRO2 reduction with barbiturates correlates with burst suppression on EEG; this endpoint indicates maximum reduction of metabolic demand.",
   "bloom":"recall",
   "source":[{"book":"Miller/Baby Miller","page":139}],
   "confusable_with":""},
  {"id":f"{S17}-4","topic":T17,"domain":D17,"discipline":DI17,
   "stem":"A patient is found to have seizure activity on EEG but no clinical convulsions (non-convulsive status epilepticus). In what setting must seizures be considered even without motor manifestations?",
   "answer":"In patients with altered mental status or unexplained coma, non-convulsive status epilepticus must be considered; EEG is indicated when seizures are suspected.",
   "rationale":"NCSE can be the cause of unexplained AMS; continuous EEG monitoring is required for diagnosis since clinical examination alone is unreliable.",
   "bloom":"analyze",
   "source":[{"book":"StatPearls: StatPearls   Syncope  Evaluation and Management","page":4}],
   "confusable_with":""},
  {"id":f"{S17}-5","topic":T17,"domain":D17,"discipline":DI17,
   "stem":"Which anesthetic agent has pro-convulsant activity at subanesthetic doses and should be used cautiously in patients with epilepsy?",
   "answer":"Enflurane (and to a lesser extent methohexital) can have pro-convulsant activity; ketamine and sevoflurane are generally safer choices in epilepsy.",
   "rationale":"Some anesthetics lower seizure threshold at certain concentrations; selection matters in epilepsy patients or those with prior seizure history.",
   "bloom":"recall",
   "source":[{"book":"Miller/Baby Miller","page":139}],
   "confusable_with":""},
]

# ─── ITEM 18: Approach to Sepsis on the Wards ────────────────────────────
T18 = "Approach to Sepsis on the Wards"
D18 = "Internal medicine: on-call & cross-cover (approach to the acutely changing ward patient)"
DI18 = "medicine"
S18 = slug(T18)
catalog += [
  {"id":f"{S18}-1","topic":T18,"domain":D18,"discipline":DI18,
   "stem":"What does the qSOFA score assess, and what is its role in identifying sepsis on the wards?",
   "answer":"qSOFA uses altered mental status (GCS), respiratory rate ≥22, and SBP ≤100; ≥2 points identifies high-risk patients outside ICU for further evaluation.",
   "rationale":"qSOFA emphasizes organ dysfunction (the third international consensus definition of sepsis deemphasizes SIRS in favor of organ dysfunction).",
   "bloom":"recall",
   "source":[{"book":"Morgan & Mikhail","page":2153}],
   "confusable_with":"SIRS criteria"},
  {"id":f"{S18}-2","topic":T18,"domain":D18,"discipline":DI18,
   "stem":"In suspected sepsis, antibiotic therapy should be initiated when in relation to cultures?",
   "answer":"Obtain adequate cultures (blood x2, urine, wounds, sputum) FIRST, then initiate antibiotics; combination therapy with two or more antibiotics is generally indicated pending sensitivities.",
   "rationale":"Culture-first ensures causative organisms are identified; delayed cultures after antibiotics reduces yield and limits pathogen-directed therapy.",
   "bloom":"apply",
   "source":[{"book":"Morgan & Mikhail","page":2155}],
   "confusable_with":""},
  {"id":f"{S18}-3","topic":T18,"domain":D18,"discipline":DI18,
   "stem":"In sepsis-associated ARDS (PaO2:FiO2 <200), what is the target for tidal volume ventilation?",
   "answer":"Tidal volume 4–8 mL/kg predicted body weight with plateau pressure <30 cm H2O (lung-protective ventilation).",
   "rationale":"ARDS from sepsis causes heterogeneous lung injury; baby-lung concept mandates small tidal volumes to avoid VILI in the still-aerated regions.",
   "bloom":"recall",
   "source":[{"book":"Society Guideline","page":39}],
   "confusable_with":""},
  {"id":f"{S18}-4","topic":T18,"domain":D18,"discipline":DI18,
   "stem":"Septic shock can develop ARDS. At what PaO2:FiO2 ratio does increased permeability edema meet the threshold for ARDS versus acute lung injury?",
   "answer":"PaO2:FiO2 ratio <200 = ARDS (severe permeability edema); ratio ≤300 = acute lung injury.",
   "rationale":"ARDS is the severe end of the permeability edema spectrum; the threshold guides escalation to prone positioning and neuromuscular blockade.",
   "bloom":"recall",
   "source":[{"book":"Morgan & Mikhail","page":2130}],
   "confusable_with":""},
  {"id":f"{S18}-5","topic":T18,"domain":D18,"discipline":DI18,
   "stem":"In immunocompromised patients with sepsis, what should guide empiric antibiotic selection?",
   "answer":"Empiric antibiotic therapy in immunocompromised patients should target pathogens associated with the specific immune defect (e.g., PCP in HIV with low CD4, fungal in prolonged neutropenia).",
   "rationale":"Immune defects create predictable vulnerability patterns; organism-specific empiric therapy improves outcomes compared to generic broad-spectrum coverage.",
   "bloom":"apply",
   "source":[{"book":"Morgan & Mikhail","page":2155}],
   "confusable_with":""},
  {"id":f"{S18}-6","topic":T18,"domain":D18,"discipline":DI18,
   "stem":"What potential harm should be considered when administering supplemental oxygen above 50–60% FiO2 for longer periods in a septic patient with respiratory failure?",
   "answer":"Pulmonary oxygen toxicity from reactive oxygen species (superoxide, hydroxyl radicals, hydrogen peroxide) causes alveolar and parenchymal damage with prolonged high FiO2.",
   "rationale":"High FiO2 generates toxic oxygen metabolites; titrate to lowest FiO2 achieving adequate SpO2 (≥92–95%) to minimize oxidative lung injury.",
   "bloom":"apply",
   "source":[{"book":"Morgan & Mikhail","page":2176}],
   "confusable_with":""},
]

print(f"Items 0-18 built: {len(catalog)} entries so far")

with open('data/kp_catalog_part1_interim.json', 'w', encoding='utf-8') as f:
    json.dump(catalog, f, ensure_ascii=False, indent=2)
print("Interim file written.")
