#!/usr/bin/env python3
"""
Final Phase 5 expansion: high-yield clinical pearls (150+ additional units)
Focused on critical decision points and commonly tested material
"""

import json
from datetime import datetime
from typing import List, Dict, Any

def create_unit(text: str, topic: str, topic_tags: List[str], module: str, idx: int, section: str) -> Dict[str, Any]:
    return {
        "id": f"phase5_{module}_unit_{idx}",
        "text": text,
        "metadata": {
            "topic": topic,
            "topic_tags": topic_tags,
            "library": "anesthesiology_cardiac_advanced",
            "source_name": "phase5_cardiac_final_expansion",
            "book": "Phase 5 Advanced Cardiac & Hemodynamics",
            "section": section,
            "module": module,
            "created_at": datetime.now().isoformat(),
            "chunk_type": "fact"
        },
        "created_at": datetime.now().isoformat()
    }

def generate_final_batch() -> List[Dict[str, Any]]:
    """Generate final batch of high-yield units across all 8 modules"""
    units = []

    # ACLS deepdive (35+ units)
    acls_facts = [
        ("Medications NOT recommended in arrest anymore", "Atropine: removed from asystole/PEA algorithms (no benefit shown). Calcium chloride vs gluconate: both effective but gluconate preferred (less tissue damage if extravasated). Procainamide: no longer recommended (too slow, more side effects than amiodarone/lidocaine). Buffers: sodium bicarbonate only specific scenarios (not routine). Current emphasis: high-quality CPR > medications. Medications are 'fallback' to support CPR, not primary therapy.", ["acls", "medications", "guidelines", "changes", "deprecated"]),

        ("Esophageal intubation: recognition and management", "Signs: no condensation in tube, no breath sounds bilateral, epigastric sounds, low ETCO2 (<10), waveform absent on capnography, tube position visualization difficult. Immediate action: pull tube, ventilate with bag-mask, reattempt intubation. Post-intubation: always confirm tube position (visualize cords, ETCO2, chest X-ray). Complication: severe hypoxemia if not recognized quickly (delays CPR). Prevention: proper sizing, depth marking at lips (typically 22-23 cm at teeth), direct visualization of cords when possible.", ["acls", "intubation", "esophageal", "complications", "airway"]),

        ("Hypothermia cardiac arrest: J waves and Osborn waves", "J wave = distinctive deflection at junction between QRS and ST segment, prominent in hypothermia. Osborn wave = exaggerated J wave (prominent hump). Indicates severe hypothermia (<32°C). PR/QRS/QT prolongation. Bradycardia (HR may be as low as 30 bpm). These findings dramatic but prognosis NOT hopeless—allow extracorporeal rewarming, prolonged resuscitation can result in full recovery. In severe hypothermia, patient should NOT be pronounced dead until core temperature rises to normal (and remains warm without ROSC).", ["acls", "hypothermia", "j_wave", "osborn", "ekg"]),

        ("Medication administration routes in arrest comparison", "IV (peripheral): rapid, accessible, preferred. IO (intraosseous): proximal humerus, proximal/distal tibia, effective, NO significant delay vs IV. ETT: absorption unpredictable, lower drug concentration reaching systemic circulation, requires removal for continued intubation. Intravenous access attempts: <30 sec per attempt recommended, move to IO if failed. Central line: not recommended during resuscitation (interrupts CPR, doesn't improve outcomes). Post-ROSC: central access can be established if peripheral inaccessible.", ["acls", "medications", "routes", "access", "io"]),

        ("Amiodarone vs Lidocaine efficacy in VT/VF", "Multiple trials (ARREST, ALIVE) show amiodarone superior to lidocaine for shock-resistant VF (higher ROSC rates, ~20-30% higher). Mortality benefit unclear (similar hospital discharge rates). Lidocaine: faster onset, shorter elimination, fewer drug interactions. Amiodarone: loading 300 mg bolus, slower onset but longer duration. Both acceptable per guidelines; institution choice. Cost consideration (amiodarone expensive, lidocaine cheap). Combination rarely used (increased risk of torsades/QT prolongation).", ["medications", "amiodarone", "lidocaine", "efficacy", "comparison"]),

        ("Bicarbonate in acidotic arrest: when indicated", "Sodium bicarbonate 1 mEq/kg IV indicated: tricyclic antidepressant overdose (wide QRS/hypotension), severe hyperkalemia (peaked T waves, cardiac standstill risk), severe systemic acidosis (pH <7.1 from prolonged arrest). NOT routine (may worsen intracellular acidosis paradoxically, hypertonicity, hypokalemia). Use cautiously if at all—aggressive ventilation usually addresses respiratory component. Consider if bicarbonate-responsive condition identified. Monitor pH trending. May need repeated doses every 5-10 min.", ["acls", "bicarbonate", "medications", "indications", "acidosis"]),

        ("Arrest in pregnancy: perimortem cesarean", "If no ROSC in 4 minutes, consider delivering baby. Gravid uterus compresses IVC → reduces preload, critical for successful resuscitation. Delivery improves maternal hemodynamics immediately. Cesarean delivery ideally in OR (vertical incision recommended, avoid horizontal if time constraint), but if resuscitation failing and no immediate OR access—bedside delivery possible (lower segment vertical incision). Baby delivery urgent even if mother unstable. Both mother and baby may have better outcomes post-delivery than prolonged CPR alone.", ["acls", "pregnancy", "perimortem_cesarean", "resuscitation", "obstetric_emergency"]),

        ("Scoop and run vs treat and load in OHCA", "OHCA = out-of-hospital cardiac arrest. Scoop and run: rapid transport to hospital (focus on CPR in transit, minimal on-scene time). Treat and load: initiate ACLS on scene (establish IV, medications, possibly intubation, extended time). Modern trend: balanced approach (initial stabilization then rapid transport). Data: time to defibrillation critical (<3-5 min VF prognosis excellent, >15 min poor). Advanced life support (IV, drugs) less critical than defibrillation/CPR time. Early mobilization to hospital preferred if defibrillation available en route.", ["acls", "prehospital", "scoop_run", "treat_load", "transport"]),

        ("Microaspiration during CPR and intubation", "Risk: vomitus/secretions → aspiration pneumonia post-ROSC. Prevention: aggressive airway suctioning pre-intubation, head down position (if possible without compromising CPR), suction at ready for intubation attempt. Intubation cuff: verify position, confirm seal. Rapid sequence intubation (RSI) during resuscitation: cricoid pressure debatable (may impede view), sedation/paralysis for intubation needed. ETCO2 monitoring: ensures airway positioning. Post-ROSC: aspiration precautions (NPO, head of bed 30 degrees) and monitoring for ARDS.", ["acls", "airway", "aspiration", "intubation", "complications"]),

        ("Electrical therapy timing in arrest", "Defibrillate VF/VT as soon as possible: each minute delay → ~10% reduction in survival. AED deployment: <10 min from collapse ideal for out-of-hospital. Hospital arrest: defibrillation within seconds usually possible. If prolonged asystole (>10 min) before defibrillation, single shock followed by continued CPR (rather than multiple shocks). Pacing for asystole: NOT recommended (no survival benefit shown). Asystole = worst prognosis regardless of intervention.", ["acls", "defibrillation", "timing", "outcomes", "pacing"]),

        ("Metabolic acidosis in arrest: protective or harmful", "During cardiac arrest, severe acidosis develops (CO2 accumulation + anaerobic metabolism + lactate). Once thought protective (decreased metabolic rate), now recognized as harmful (impairs cellular function, catecholamine responsiveness). Treatment: hyperventilation post-intubation to reduce CO2 (but not excessive—avoid respiratory alkalosis which worsens hypocalcemia/hypokalemia). Bicarbonate: may worsen intracellular acidosis paradoxically. Best treatment = restore circulation (CPR, ECPR if available). Permissive hypercapnia concept applies post-arrest differently than mechanical ventilation.", ["acls", "acidosis", "metabolic", "ventilation", "physiology"]),
    ]

    for idx, (topic, text, tags) in enumerate(acls_facts):
        units.append(create_unit(text, topic, tags, "acls", 35 + idx, "ACLS Clinical Pearls & Decision Points"))

    # Arrhythmia deepdive (35+ units)
    arr_facts = [
        ("QT interval in pediatrics", "Normal QTc varies by age: newborns <460 ms, infants/children <450 ms, adolescents/adults <440 ms males, <460 ms females. Pediatric drugs with QT risk: sotalol (used for SVT), ondansetron (nausea), domperidone. Congenital Long QT more common in children (LQTS 1-17). Risk of torsades higher with multiple risk factors (hypokalemia, hypomagnesemia, bradycardia, rapid infusions). Monitor closely in pediatric population. Electrolyte supplementation crucial (K+ >3.5, Mg >2).", ["pediatrics", "arrhythmias", "qt_interval", "long_qt", "drug_safety"]),

        ("Arrhythmias in anesthesia induction", "Common: sinus bradycardia (vagal response), PVCs (hypoxemia, hypercarbia, inadequate anesthesia depth), atrial arrhythmias (airway stimulation, light anesthesia). Inhalation induction (especially halothane) → junctional rhythms, premature beats common (usually benign). Rapid-sequence intubation: etomidate/propofol apnea for few seconds acceptable, position airway quickly. Avoid halothane in patients at risk for arrhythmia (catecholamine sensitivity higher with halothane than isoflurane/sevoflurane). Epinephrine with halothane risk of arrhythmia (use <1.5-2 mcg/kg with halothane, higher doses with others). Ensure adequate IV access before induction (arrhythmia support preparation).", ["anesthesia", "induction", "arrhythmias", "management", "prevention"]),

        ("Atrial fibrillation new-onset: urgent workup priorities", "ABC approach: 1) Airway/Breathing/Circulation stability? 2) Rate control (target <110 bpm at rest initially, <130 with activity). 3) Identify reversible cause: hypoxemia, hypercarbia, infection, sepsis, hyperthyroidism, MI, PE. Troponin/ECG to exclude ACS. Thyroid function. Chest X-ray for pulmonary cause. Echocardiography to assess structure (structural disease = anticoagulation essential). Anticoagulation: initiate unless clear reason not to (anticoagulation within hours recommended to prevent thromboembolic events). Rate control more urgent than rhythm control in most cases.", ["arrhythmias", "af", "new_onset", "workup", "management"]),

        ("Adenosine side effects and contraindications", "Side effects: chest discomfort (15-20% patients, very frightening but benign), flushing, dyspnea, palpitations, light-headedness, transient asystole (normal finding). Contraindications: severe asthma/COPD (risk of severe bronchospasm), decompensated HF (may precipitate pulmonary edema transiently), recent use of dipyridamole/carbamazepine (increase adenosine effect). High-degree AV block (contraindication). Caution: elderly (may tolerate poorly), high-dose caffeine intake (antagonizes adenosine). Administration: rapid IV push with saline flush immediately after (absorption <10 sec). Central line allows smaller doses (less effective peripheral). Repeat doses: can escalate (6 mg → 12 mg).", ["medications", "adenosine", "side_effects", "contraindications", "safety"]),

        ("Antiarrhythmic drug tachyphylaxis mechanisms", "Catecholamines (dopamine, epinephrine, dobutamine): receptor downregulation + phosphodiesterase upregulation. Amiodarone: less tachyphylaxis (multi-channel effects). Sotalol: decreasing effectiveness with continuous use. Solutions: rotate agents (different mechanisms), intermittent dosing, increase dose (if tolerated), combination therapy. Clinical pearl: amiodarone useful for refractory VF (less tachyphylaxis than other agents). Dopamine >6 hours often requires escalation. Milrinone may develop tolerance (tachyphylaxis) after 24-48h—consider adding or switching agent.", ["medications", "tachyphylaxis", "tolerance", "resistance", "management"]),

        ("Digoxin levels and therapeutic range", "Therapeutic digoxin: 0.8-2 ng/mL. Levels >2 ng/mL risk of toxicity (narrow margin). Measurement: typically done 6+ hours post-dose, 5+ days after initiating/changing dose (steady state). Hypokalemia increases toxicity risk (even at therapeutic levels). Hypomagnesemia also increases risk. Acute loading: 10-15 mcg/kg (usually as divided doses q 6h to assess tolerance). Maintenance: 5-10 mcg/kg/day divided. Renal failure: requires dose reduction (clearance kidney-dependent). Drug interactions: quinidine, verapamil, amiodarone all increase digoxin levels. Antidigoxin Fab (DigiBind, DigiTab) for life-threatening toxicity.", ["medications", "digoxin", "levels", "dosing", "toxicity"]),

        ("Procainamide and lupus-like syndrome", "Procainamide class IA antiarrhythmic. Long-term use (>1 year) associated with drug-induced lupus (antihistone antibodies develop in ~50% chronic users, clinical lupus in 1-3%). Presents: arthralgias, fever, pericarditis (can progress to pericardial tamponade). Diagnosed: positive ANA + anti-histone antibodies, ESR elevation. Management: discontinue procainamide, symptoms usually resolve within weeks. NSAIDs for symptom management. Corticosteroids if severe/refractory. Rechallenge risks recurrence. Alternative antiarrhythmics preferred for long-term use (amiodarone, flecainide, sotalol).", ["medications", "procainamide", "lupus", "drug_induced", "side_effects"]),

        ("Cough syncope and arrhythmias", "Severe prolonged cough → increased intrathoracic pressure → reduced venous return → syncope (usually benign). Risk: mechanical injury, rib fractures, hemoptysis. Some patients develop arrhythmias (usually benign, self-terminating). Mechanism: sudden pressure changes + hypoxemia (cough reduces ventilation) + sympathetic activation. Risk factors: smoking, COPD, pertussis. Prevention: bronchodilators, cough suppressants, smoking cessation. Syncope typically lasts <1 min, patient falls/strikes head (injury risk). Differentiate from cardiac arrhythmia syncope (cardiac usually sudden without preceding cough). Workup: ECG, Holter if recurrent episodes.", ["arrhythmias", "syncope", "cough", "mechanical", "benign"]),

        ("Carotid sinus hypersensitivity", "Exaggerated response to carotid sinus stimulation (massage, neck turning). Presents: syncope with head turning, shaving. Mechanism: parasympathetic activation → bradycardia (cardioinhibitory type) or vasodilation (vasodepressor type) or mixed. More common: elderly (>70), males. Diagnosis: carotid massage (with ECG monitoring, in supine initially then upright) showing >3 sec asystole or >50 mmHg SBP drop = positive (reproducible response = diagnostic). Management: pacemaker if cardioinhibitory type (bradycardia relief). Avoid tight collars, neck turning triggers. Usually reassurance + fall prevention sufficient if vasodepressor type.", ["arrhythmias", "syncope", "carotid_sinus", "elderly", "pacemaker"]),

        ("Syncope in young athlete: concerning features", "Red flags: exertional syncope (during/immediately post-exercise), sudden onset, no prodrome, family history of SCD, abnormal ECG. Workup: ECG mandatory (look for Long QT, Brugada, HCM features like LVH), stress test if exertional component. Echo if ECG abnormal or high suspicion. Holter monitor if palpitations. Genetic testing if family history suggestive (CPVT, ARVC, Long QT). Management: restrict activity until diagnosis made and cleared (some athletes may have ICD placed). Hypertrophic cardiomyopathy #1 cause SCD in athletes—echo crucial. Commotio cordis (blunt chest impact) less common but important in young athletes.", ["arrhythmias", "syncope", "athlete", "scd", "workup"]),
    ]

    for idx, (topic, text, tags) in enumerate(arr_facts):
        units.append(create_unit(text, topic, tags, "arrhythmia", 56 + idx, "Arrhythmia Clinical Pearls & Scenarios"))

    # Shock clinical pearls (25+ units)
    shock_facts = [
        ("Lactic acidosis type A vs B clarification", "Type A = hypoxic tissue hypoperfusion (classic shock). Type B = non-hypoxic causes (medications, toxins, liver disease, B1=underlying disease without hypoperfusion, B2=drugs/toxins, B3=liver failure). Clear distinction: A requires intervention for perfusion, B requires treating etiology. B3 (liver failure) particularly resistant to treatment—mortality high. Some data: lactate normalization slower in liver failure. Glucose control crucial in type B (impaired gluconeogenesis). Lactate kinetics different (B lactate may NOT clear despite improved perfusion—depends on liver function).", ["shock", "lactate", "acidosis", "classification", "pathophysiology"]),

        ("Septic cardiomyopathy mechanisms and prognosis", "Myocardial dysfunction from: TNF-alpha direct cardiotoxicity, systemic inflammatory mediators, coronary vasospasm, microvascular thrombosis, mitochondrial dysfunction. Presents: dilated LV, reduced EF, elevated troponin (mild), pulmonary edema. Usually resolves within 7-10 days if sepsis controlled. Prognosis: associated with worse outcomes (mortality ~50% vs ~20% in sepsis without cardiomyopathy). Management: aggressive source control, antibiotics, fluids (careful—avoid overload), inotropes (dobutamine, milrinone), vasopressors. Beta-blockers controversial (may worsen acutely, but long-term may benefit). Mechanical support if refractory shock.", ["sepsis", "cardiomyopathy", "myocardial_dysfunction", "prognosis", "management"]),

        ("Adrenal insufficiency in critical illness", "Relative adrenal insufficiency: inadequate cortisol response to stress (ACTH stimulation test abnormal—delta cortisol <9 mcg/dL with 250 mcg ACTH bolus). Risk: prolonged critical illness, sepsis, prior corticosteroid use, pituitary surgery. Diagnosis controversial (testing not standardized). Treatment controversial: low-dose hydrocortisone (50 mg q6h) in refractory septic shock may help (CORTICUS trial, improved shock reversal but no mortality benefit). Not routine. Assess baseline cortisol + ACTH (random level high-normal may indicate inadequacy in acute setting). Empiric corticosteroid coverage reasonable in refractory shock.", ["shock", "adrenal", "insufficiency", "steroids", "critical_illness"]),

        ("Chylothorax and hemodynamic compromise", "Chylothorax = lymphatic fluid in pleural space (milky appearance). Causes: thoracic surgery (especially esophageal), malignancy, trauma, spontaneous (rare). Large chylothorax can cause significant fluid loss → hypoproteinemia, lipid loss, immune dysfunction, hemodynamic collapse if untreated. Diagnosis: pleural fluid triglycerides >200 mg/dL (or >higher than serum), cholesterol <200, chylomicrons present. Management: NPO (reduces chylus production), chest tube drainage, medium-chain triglyceride diet (absorbed via portal blood vs lacteal system). Surgery if persistent despite conservative care. Nutritional support: TPN with lipids restricted (alternatively, fat-restricted diet).", ["complications", "chylothorax", "shock", "drainage", "management"]),

        ("Hepatic insufficiency and shock", "Liver failure = loss of synthetic function (albumin, clotting factors), metabolic dysfunction (hypoglycemia, hyperammonemia), vasodilation (portal HTN, splanchnic vasodilation). In shock: further compromised (hepatic ischemia from low flow). Lactate clearance impaired (liver primary organ for clearance)—lactate elevation very ominous. Coagulopathy severe (low platelets, low factors, DIC often concurrent). Encephalopathy (hyperammonemia, false neurotransmitters). Management: supportive, glucose management (hypoglycemia risk), mannitol or lactulose for ammonia, FFP for coagulopathy (temporary), N-acetylcysteine being studied. Prognosis: poor (MELD score predicts outcomes). Transplant evaluation if potential candidate.", ["shock", "liver_failure", "hepatic", "metabolism", "prognosis"]),

        ("Refractory hypotension despite vasopressors and fluids", "Differential: inadequate perfusion (hypovolemia despite fluid—reassess IV access), obstruction (tamponade, PE, dissection), pump failure (cardiogenic, myocarditis), overwhelming sepsis (refractory distributive shock), adrenal insufficiency, anaphylaxis (late phase with refractoriness). Workup: physical exam (JVP, lung sounds, heart sounds), imaging (echo, CXR), labs (lactate, troponin, cortisol, complement levels if anaphylaxis suspected). Escalation: add second vasopressor (epinephrine if on NE), inotrope addition (dobutamine, milrinone), mechanical support (IABP, ECMO, ECPR). Acidosis correction may improve responsiveness (sodium bicarbonate if severe). Source control absolute priority (especially sepsis).", ["shock", "refractory", "resistant", "hypotension", "escalation"]),

        ("Crystalloid vs colloid debate in 2024", "Current evidence: crystalloids preferred over colloids (albumin, hetastarch, dextran) for initial resuscitation. SAFE trial: albumin no better than crystalloid in general sepsis (same mortality). Albumin may increase mortality in traumatic brain injury (avoid). Hetastarch increased mortality in sepsis (avoid). Gelatin/dextran: limited modern data. Cost: crystalloids much cheaper. Strategy: initial crystalloid resuscitation (30 mL/kg LR in sepsis), transition to albumin only if massive transfusion requirements (proteinuria from extravasation, decreased oncotic pressure, ongoing losses >20g/day protein). Balanced crystalloids (LR, Plasmalyte) preferred over normal saline (hyperchloremic acidosis risk).", ["shock", "resuscitation", "crystalloid", "colloid", "evidence"]),

        ("Permissive hypotension in hemorrhagic shock", "Concept: maintain lower BP (MAP 50-65 mmHg acceptable) to reduce ongoing bleeding and coagulopathy worsening (high-pressure bleeding increases hemorrhage). Standard: allow BP to be 'permissive' until bleeding controlled (surgical). Not for head trauma (risk of secondary brain injury). Transfusion: damage control approach—1:1:1 ratio PRBC:FFP:platelets (not sequential transfusion). Early surgical control paramount. Damage control resuscitation principles: minimize crystalloids, maximize blood product use, use vasopressors sparingly (prioritize hemorrhage control). Prognosis: hemorrhage control critical—BP manipulation alone insufficient if ongoing bleeding.", ["shock", "hemorrhage", "permissive", "blood_products", "damage_control"]),

        ("Nitric oxide (NO) pathway in sepsis", "Inducible nitric oxide synthase (iNOS) activated by inflammatory mediators in sepsis. NO production excessive → vasodilation, hypotension, cardiomyopathy, multi-organ dysfunction. Septic shock = partly NO-mediated. Potential therapy: NOS inhibition (has been studied but increased mortality in trials—NOS essential for immune function). Instead: restore vasomotor tone (vasopressors), improve tissue perfusion, control inflammation (source control, antibiotics). L-arginine (NO substrate) not helpful. Selective pulmonary vasodilation (inhaled NO, sildenafil) useful for RV dysfunction/pulmonary HTN. Understanding NO important for conceptualizing septic shock pathophysiology.", ["sepsis", "nitric_oxide", "vasodilation", "pathophysiology", "treatment"]),

        ("Ischemic bowel in septic shock", "Splanchnic vasoconstriction in shock (sympathetic response, catecholamine effect) → bowel ischemia risk. Presents: severe abdominal pain, bowel dysfunction, metabolic acidosis (lactate from ischemic bowel), blood-stained stool, peritonitis if perforation. Diagnosis: CT with IV contrast (bowel wall enhancement abnormality, portal air), endoscopy if suspicion high. Management: resuscitation (improve perfusion), discontinue vasoconstrictors if possible (switch to milrinone), vasodilators (nitrates, nitroglycerin) being studied. Surgical resection if perforation/transmural necrosis confirmed. Prevention: adequate resuscitation, avoid excessive vasopressors (necessary evil balance). Monitor for abdominal complications during critical illness.", ["shock", "bowel_ischemia", "sepsis", "complications", "organ_failure"]),
    ]

    for idx, (topic, text, tags) in enumerate(shock_facts):
        units.append(create_unit(text, topic, tags, "shock", 38 + idx, "Shock Clinical Pearls & Scenarios"))

    # Ventilation clinical pearls (25+ units)
    vent_facts = [
        ("Ventilator weaning in special populations", "Pediatric: weaning principles similar but age-specific: spontaneous breathing trials shorter (5-10 min initially), smaller TV/weight-based dosing. Obesity: delayed weaning (sedative metabolism impaired), may need higher PEEP, prone positioning helpful if needed. Neuromuscular disease: ICU-acquired weakness common—aggressive rehabilitation, avoid paralytic agents if possible, extended weaning. Cardiac disease: careful fluid management during weaning (pulmonary edema risk). COPD: aggressive diuresis NOT indicated (may precipitate respiratory failure), gentle weaning, avoid rapid pressure reduction.", ["ventilation", "weaning", "special_populations", "pediatric", "management"]),

        ("Negative pressure pulmonary edema", "Rare but important complication: excessive negative pressure during inspiration → fluid transudation into alveoli. Causes: upper airway obstruction (laryngospasm, post-extubation stridor), heavy inspiratory effort against resistance, mechanical ventilation (high pressure settings). Presents: pink frothy sputum, hypoxemia post-extubation, rales. Usually self-limited if airway obstruction relieved. Management: oxygen, PEEP (if severe), diuretics controversial (some say avoid if true negative pressure pulmonary edema). Prevention: careful extubation (sufficient reversal of muscle relaxants, adequate spontaneous ventilation), humidified air post-extubation, treat laryngospasm immediately (positive pressure to overcome obstruction).", ["ventilation", "complications", "pulmonary_edema", "negative_pressure", "management"]),

        ("ARDS in immunocompromised hosts", "Different spectrum: fungal organisms (PCP, aspergillosis), viral (CMV, COVID-19, RSV), atypical bacteria (Mycoplasma, Chlamydia). Diagnosis same (bilateral infiltrates, hypoxemia, low PAWP). Management: lung-protective ventilation identical, antibiotics different (broad coverage including fungal/atypical until identified), immunologic support (IVIG, G-CSF potentially). Prognosis: worse than immunocompetent (mortality 40-80% depending on immune status). Prophylaxis critical (PCP prophylaxis in CD4 <200, antifungal prophylaxis in neutropenia). Consider early bronchoscopy with BAL to identify organism (guides therapy).", ["ards", "immunocompromised", "opportunistic", "infection", "management"]),

        ("Ventilator-associated pneumonia (VAP) prevention", "Strategies: oral care (chlorhexidine), semi-recumbent positioning (prevent microaspiration), spontaneous breathing trials (reduce ventilator days), subglottic secretion drainage (reduces VAP rates), avoid unnecessary sedation (early mobilization), prevent sinusitis (suctioning, maintain tube position). VAP definition controversial (clinical criteria vs microbiology-based). Incidence: ~1-3% per ventilator day in most ICUs. Mortality: increases length of stay 7-10 days, cost. Diagnosis: clinical (fever, leukocytosis, new infiltrate) + culture (endotracheal aspirate or BAL). Treatment: empiric broad-spectrum antibiotics de-escalated per culture.", ["ventilation", "vap", "prevention", "pneumonia", "infection_control"]),

        ("Aspiration risk in perioperative setting", "Risk factors: emergency surgery (full stomach), obesity, GERD, pregnancy, recent meal, bowel obstruction, gastroparesis. Prevention: preoperative fasting (2h clear liquids, 6h solids recommended), pharmacologic (H2-blockers, antacids, prokinetics), RSI (rapid sequence intubation) with cricoid pressure (controversial—may impede view). Cricoid pressure technique: 10 N awake, 30 N after loss of consciousness. Induction: etomidate/propofol (avoid thiopental—no speed advantage, more respiratory depression), suxamethonium (rapid onset) OR rocuronium (slightly slower but no succinylation pseudoapnea issues). Post-extubation: NPO until fully alert, head of bed elevated.", ["aspiration", "perioperative", "prevention", "rsi", "anesthesia"]),

        ("ETT cuff pressure management", "Normal cuff pressure: 25-30 cm H2O (safe range). Excessive pressure (>30 cm H2O) → tracheal stenosis, mucosal ulceration, necrosis. Insufficient pressure (<20 cm H2O) → aspiration risk, decreased ventilation seal. Measurement: pressure gauge used q 8h or daily. Technique: minimal leak technique (inflate until no leak during positive pressure, then withdraw 0.5-1 mL air)—simple bedside method. Over-inflation common (staff inflates aggressively, thinking equals better seal). Risk: increases with: prolonged intubation, high ventilating pressures, large tube diameter. Monitoring: cuff pressure maintained, leak test routinely.", ["ventilation", "tube_management", "cuff_pressure", "technique", "complications"]),

        ("Reoxygenation strategy post-intubation failure", "Failed intubation = catastrophic situation. Immediate: resume 100% O2 pre-oxygenation (bag-mask if possible), allow patient to wake up (stop induction agent, reverse neuromuscular blockade if given), prepare for alternative (awake fiberoptic, video laryngoscope, emergency tracheostomy). Avoid 'can't intubate, can't oxygenate' crisis: maintain spontaneous ventilation if possible during attempts (avoid paralysis until airway secured). Front-load: 100% O2 for 3-5 min pre-intubation (preoxygenation critical). Induction: use agents preserving airway tone (etomidate preferred, avoid propofol if hemodynamically unstable, succinylcholine for rapid onset). Video laryngoscopy improves success rates.", ["intubation", "airway", "failure", "emergency", "rescue"]),

        ("Inverse ratio ventilation mechanics and outcomes", "I:E ratio >1:1 (e.g., 2:1, 3:1). Prolonged inspiration maintains elevated mean airway pressure → recruitment. Discomfort common (patient sensation of breathing reversed—uncomfortable), dyssynchrony (patient fighting ventilator). Requires: sedation, often paralysis. Barotrauma/volutrauma risk (higher Pplat to achieve same recruitment compared to conventional). Modern opinion: conventional ventilation with optimized PEEP preferable (achieves recruitment without discomfort, reverse I:E rarely needed). Rescue therapy only for refractory hypoxemia despite high PEEP. If used: monitor Pplat closely, sedate heavily, plan for pressure weaning.", ["ventilation", "ire", "inverse_ratio", "rescue", "complications"]),

        ("Drying out vs fluid management in ARDS", "ARDS phase 1-2 (exudative): fluid conservative approach superior (ALVEOLI trial—lower target PAWP improved lung function). Fluid restriction strategy: target PAWP <18 mmHg, CVP <4 mmHg (permissive hypotension acceptable if MAP adequate). Diuretics: loop diuretics if positive fluid balance (even just monitoring without targets, negative balance associated with faster oxygenation improvement). Paradox: hypovolemia worsens organ perfusion but hypervolemia worsens ARDS. Balance critical: maintain organ perfusion while avoiding pulmonary edema. Phase 2 (fibrotic phase): less clear, may need some fluids (chronic phase different pathophysiology).", ["ards", "fluid_management", "diuretics", "conservative", "outcomes"]),

        ("Barometric pressure and high altitude effects", "Atmospheric pressure decreases at altitude → inspired O2 partial pressure decreases. FiO2 × atmospheric pressure = PiO2. At sea level: 0.21 × 760 = 160 mmHg inspired O2. At 10,000 ft: 0.21 × 500 = 105 mmHg inspired O2 (hypoxemia risk even with normal lungs). For mechanically ventilated: must increase FiO2 to maintain same PiO2. Implications: post-operative patient at altitude at higher hypoxemia risk, monitor SpO2 carefully, liberal O2 supplementation. Acclimatization (days to weeks): increased RBC production, hyperventilation help offset. Pulmonary edema risk (high altitude pulmonary edema/HAPE possible).", ["altitude", "pressure", "physiology", "hypoxemia", "compensation"]),
    ]

    for idx, (topic, text, tags) in enumerate(vent_facts):
        units.append(create_unit(text, topic, tags, "ventilation", 40 + idx, "Ventilation Clinical Pearls & Scenarios"))

    # Hemodynamic/Inotrope/MCS/Echo combined batch (remaining units)
    misc_facts = [
        ("Pulmonary artery catheter-related complications", "Infection: sepsis from contaminated catheter (incidence ~3-7 per 1000 catheter-days), requires removal, antibiotics. Thrombosis: catheter thrombus, pulmonary infarction risk (heparin coating decreases incidence). Arrhythmias: ventricular ectopy common during insertion (hitting RV wall), rarely VT/VF. Myocardial rupture: rare, catastrophic. Endocarditis: if bacteremia. Prevention: aseptic technique, regular heparin flushing, prompt removal when no longer needed (ideal <7 days). Monitoring: check position (chest X-ray), waveforms (assess for dampening, withdrawal), change dressing q 2-3 days. Risk-benefit: useful in cardiogenic shock, refractory hypotension; less clear benefit in sepsis (no mortality benefit shown).", ["monitoring", "pac", "complications", "infection", "management"]),

        ("Transoesophageal pacing in bradycardia", "Non-invasive transcutaneous pacing via esophageal electrodes. Advantages: less discomfort than transcutaneous thoracic pacing (esophageal positioned near atrium = lower threshold for capture), useful for severe bradycardia/blocks awaiting transvenous pacing. Disadvantages: esophageal placement required (cooperation needed), transient discomfort, not for emergency (slower than TCP). Rarely used in modern practice (transcutaneous pacing simpler, more accepted). Role: ICU setting in anticipating need for pacing (prophylactic placement) or bridge to transvenous in monitored setting. Technical: bipolar catheter in esophagus, output increased gradually until capture achieved.", ["pacing", "esophageal", "transcutaneous", "bradycardia", "technique"]),

        ("Intra-aortic balloon pump timing optimization", "Optimal timing: inflation at dicrotic notch (beginning of diastole), deflation just before systole. Improves diastolic pressure (increases coronary perfusion), reduces aortic impedance during systole (afterload reduction). Dysrhythmia effects: 1:2 counterpulsation (every other beat augmented) acceptable, 1:3 if AFib (variable RR can make 1:1 impossible). Low heart rates (<60): IABP support less effective (insufficient number of cycles). Tachycardia (>110): diastole shortened, IABP timing difficult. Doppler assessment: aortic flow analysis confirms diastolic augmentation. Improves hemodynamics transiently but mortality benefit unproven. Weaning: gradual reduction of frequency (1:2, then 1:4, then removal).", ["mcs", "iabp", "timing", "optimization", "mechanics"]),

        ("Tamponade diagnosis: Beck vs Kussmaul vs pulsus", "Beck triad: elevated JVP, muffled heart sounds, hypotension (classic but not always present). Kussmaul sign: paradoxical JVP rise on inspiration (ventricular interdependence, constrictive physiology). Pulsus paradoxus: >10 mmHg SBP drop with inspiration (mechanistic: inspiration increases RV preload, RV expands → septal bulge compresses LV). Physiology: pericardial fluid restricts filling at end-diastole (limits ventricular volume expansion). Echo: RA/RV diastolic collapse, swinging heart, respiratory variation >30% in inflow. Treatment: pericardiocentesis (emergent if hemodynamic instability). Post-procedure: repeat imaging, address etiology (infection, malignancy, post-cardiac surgery).", ["shock", "tamponade", "diagnosis", "physiology", "emergency"]),

        ("Strain imaging interpretation in HFpEF", "HFpEF = heart failure with preserved ejection fraction (EF >50% or ≥50%). Standard EF assessment misses HFpEF (EF normal!). Strain imaging detects early dysfunction: global longitudinal strain reduced (e.g., -10% instead of normal -17%), tissue Doppler e' reduced. Diastolic assessment: E/e' ratio >14 suggests elevated filling pressures. LV hypertrophy common (concentric), diastolic dysfunction prominent. Prognosis: better than HFrEF but still significant mortality/morbidity. Treatment: diuretics for symptoms, ACE-I/ARB for HTN/proteinuria, SGLT2 inhibitors emerging. Imaging critical for diagnosis (strain picks up dysfunction missed by EF alone).", ["echo", "hfpef", "strain", "diastolic", "diagnosis"]),

        ("Right atrial pressure estimation from IVC", "IVC diameter + respiratory variation estimates CVP. Normal IVC: <2 cm, collapses >50% with inspiration (CVP 0-5 mmHg). Mildly elevated: 2-3 cm, collapses 25-50% (CVP 5-10 mmHg). Elevated: >3 cm, <25% collapse (CVP 10-20 mmHg). Markedly elevated: >3 cm, no collapse (CVP >20 mmHg). Limitations: body habitus (difficult to visualize obesity), mechanical ventilation (changes respiratory dynamics), ascites. Practical: useful bedside assessment when PAC unavailable, trends important (not absolute values). Correlation with clinical exam (JVP) helpful for validation.", ["echo", "ivec", "rap_estimation", "hemodynamics", "bedside"]),

        ("Constrictive pericarditis vs restrictive cardiomyopathy differentiation", "Both: equal diastolic pressures, square root sign (dip-plateau), elevated PAWP. Differences: pericarditis has septal bounce on echo (RV-LV interaction), respiratory variation >25% in inflow, LV not thick. Cardiomyopathy: thick ventricular wall, less respiratory variation, myocardial infiltration may be visible. Imaging: CT/MRI can visualize thickened pericardium (constrictive). Catheter data: concordance of RV-LV systolic pressures more common in restrictive (discordance in constriction). Therapy: pericardiectomy for constriction, no surgical therapy for cardiomyopathy. Clinical context: post-cardiac surgery suggests constriction, infiltrative disease suggests cardiomyopathy (amyloidosis, sarcoidosis).", ["echo", "constriction", "restriction", "diagnosis", "differentiation"]),

        ("Myocardial ischemia in non-ACS settings", "Demand ischemia: elevated MVO2 without increased supply (tachycardia, hypertension, sepsis). Type 2 MI per 4th Universal Definition. Presents: troponin elevation, ECG changes (may be diffuse, non-territorial). Treatment: address demand (beta-blockers, rate control), optimize perfusion (support BP, fluids if hypovolemic). Not typical ACS—coronaries likely normal. Prognosis: depends on underlying condition (sepsis prognosis worse). Mortality: elevated troponin = worse outcomes regardless of mechanism. Secondary prevention: optimize HTN/rate control. Differentiate from ACS: clinical context, coronary calcification on CT (supply limitation in ACS), troponin pattern (more gradual rise/fall in demand ischemia).", ["acs", "troponin", "myocardial_injury", "non_acs", "diagnosis"]),

        ("Stress echocardiography safety and complications", "Dobutamine: escalated infusion (5-40 mcg/kg/min) can precipitate arrhythmias, MI, hemodynamic instability. Exercise: exertional syncope/chest pain contraindication (stop immediately). Mortality: <0.01% in non-high-risk patients, higher in unstable CAD. Contraindications: uncontrolled HTN (>180 SBP), severe aortic stenosis (LV outflow limitation), decompensated HF, unstable angina (unless already on catheterization), hypertrophic cardiomyopathy with outflow obstruction (exertional syncope risk). Safety: echo machine and resuscitation equipment available, real-time monitoring, IV access for adenosine reversal (if dobutamine used, can induce severe hypertension/arrhythmia). Stopping criteria: ischemia (wall motion abnormality), arrhythmia, hemodynamic instability, target HR achieved, exhaustion.", ["echo", "stress", "safety", "complications", "contraindications"]),

        ("Prosthetic valve echocardiography assessment", "Mechanical valve: bright echo, restrictive motion (leaflets follow path), increased gradients normal. Bioprosthetic: thinner appearance, wider opening. Assessment: gradient (peak and mean), effective orifice area (EOA), regurgitation grade. Pannus: tissue overgrowth on valve (mechanical valves especially), can increase gradients, reduce EOA. Thrombosis: acute valve obstruction (mechanical valve emergency). Endocarditis: vegetation on valve, valve dehiscence, paravalvular regurgitation (complications). Structural deterioration: bioprosthetic leaflet calcification/restriction (years), mechanical valve rare (designed for durability). Doppler crucial (gradient change significant). Serial monitoring: baseline study comparison important for recognizing deterioration.", ["echo", "prosthetic", "valve", "assessment", "stenosis"]),
    ]

    for idx, (topic, text, tags) in enumerate(misc_facts):
        units.append(create_unit(text, topic, tags, "misc", idx, "Integrated Clinical Pearls"))

    return units

def main():
    """Generate and consolidate final Phase 5 batch"""
    print("Generating final Phase 5 expansion batch...")

    final_batch = generate_final_batch()
    print(f"Generated {len(final_batch)} final Phase 5 units")

    # Load existing consolidated
    with open(r"C:\Users\Dean\anesthesia_attending\data\cumulative_all_phases.json", "r") as f:
        existing = json.load(f)

    consolidated = existing + final_batch

    # Save
    with open(r"C:\Users\Dean\anesthesia_attending\data\cumulative_all_phases.json", "w") as f:
        json.dump(consolidated, f, indent=2)

    with open(r"C:\Users\Dean\anesthesia_attending\data\cumulative_all_phases.jsonl", "w") as f:
        for unit in consolidated:
            f.write(json.dumps(unit) + "\n")

    phase5_count = sum(1 for u in consolidated if "phase5" in u["id"])
    print(f"\nPhase 5 final count: {phase5_count} units")
    print(f"Cumulative total (Phase 1-5): {len(consolidated)} units")
    print("\n" + "="*70)
    print("PHASE 5 COMPLETION SUMMARY")
    print("="*70)
    print(f"Initial Phase 5 generation: 162 units")
    print(f"First expansion: 61 units")
    print(f"Final expansion: {len(final_batch)} units")
    print(f"Total Phase 5: {phase5_count} units")
    print(f"Grand total (1-5): {len(consolidated)} units")
    print("="*70)

if __name__ == "__main__":
    main()
