import json

out = []

# 236: Heparin-Induced Thrombocytopenia (HIT) & Cardiac Surgery
t = 'Heparin-Induced Thrombocytopenia (HIT) & Cardiac Surgery'
dom = 'Cardiovascular & cardiac anesthesia (CABG, valvular, cardiopulmonary bypass, TEE basics, cardiac physiology, hemodynamic & vasoactive management, ICDs/pacemakers)'
disc = 'anesthesia'
out += [
    {'id':'hit-cardiac-d1','topic':t,'domain':dom,'discipline':disc,'stem':'A patient with a history of HIT requires cardiac surgery necessitating anticoagulation. What antibodies are responsible for HIT and what is the mechanism of thrombocytopenia?','answer':'HIT is caused by heparin-dependent anti-platelet factor 4 (PF4) antibodies; these IgG antibodies form immune complexes that activate platelets, causing platelet aggregation, thrombocytopenia, and paradoxical thromboembolism.','rationale':'Platelet activation via FcgammaRIIA receptors leads to consumption (thrombocytopenia) and thrombosis simultaneously, creating the paradox of low platelets with high clot risk.','bloom':'recall','source':[{'book':'Morgan & Mikhail','page':740}],'confusable_with':'immune thrombocytopenic purpura (no thrombosis; different antibody target)'},
    {'id':'hit-cardiac-d2','topic':t,'domain':dom,'discipline':disc,'stem':'A patient with remote history of HIT and no detectable antibodies requires urgent cardiac surgery with CPB. What anticoagulation strategy is preferred?','answer':'If HIT antibodies are undetectable on current testing, unfractionated heparin may be used for CPB; if antibodies are present or history is recent, alternative anticoagulants such as bivalirudin or argatroban should be used.','rationale':'HIT antibodies are typically transient; if absent on preoperative testing the risk of re-exposure is low, but ongoing HIT with detectable antibodies contraindicates heparin use.','bloom':'apply','source':[{'book':'Morgan & Mikhail','page':740}],'confusable_with':'using LMWH for CPB (LMWH also cross-reacts with HIT antibodies and cannot be used)'},
    {'id':'hit-cardiac-d3','topic':t,'domain':dom,'discipline':disc,'stem':'In thrombocytopenia management, what platelet count thresholds define mild, moderate, and severe thrombocytopenia and at what count does spontaneous bleeding risk increase?','answer':'Mild 100-150k; moderate 50-99k; severe <50k. Spontaneous bleeding risk increases at <10k; surgical/active bleed risk increases at <50k; mild trauma risk at <30k.','rationale':'Risk stratification guides transfusion decisions and timing of procedures; these thresholds help distinguish safe versus hazardous procedural platelet counts.','bloom':'recall','source':[{'book':'MGH Housestaff Manual','page':139}],'confusable_with':'HIT platelet count (typically 50-100k range, but the pathological concern is thrombosis not bleeding)'},
    {'id':'hit-cardiac-d4','topic':t,'domain':dom,'discipline':disc,'stem':'What is the significance of a 4T score of 4-5 in a patient without a clear indication for therapeutic anticoagulation?','answer':'An intermediate 4T score (4-5) warrants stopping heparin and initiating alternative anticoagulant prophylaxis while awaiting confirmatory testing; therapeutic anticoagulation should be added if thrombosis is confirmed or bleeding risk is low.','rationale':'The 4T score (thrombocytopenia degree, timing, thrombosis, alternative cause) stratifies HIT probability; intermediate scores require empiric management while lab confirmation is pending.','bloom':'apply','source':[{'book':'StatPearls: StatPearls   Heparin induced thrombocytopenia (HIT)','page':5}],'confusable_with':'low 4T score 0-3 (can continue heparin; alternative diagnosis more likely)'},
    {'id':'hit-cardiac-d5','topic':t,'domain':dom,'discipline':disc,'stem':'Low-dose subcutaneous heparin prophylaxis (5000 units SC) is given preoperatively. Is this a contraindication to neuraxial anesthesia?','answer':'Low-dose SC heparin prophylaxis (5000 units) is NOT a contraindication to neuraxial anesthesia; guidelines suggest neuraxial anesthesia should occur 4-6 hours after the last dose.','rationale':'The small subcutaneous dose produces minimal systemic anticoagulation; a 4-6 hour interval allows heparin to be largely metabolized before needle placement.','bloom':'apply','source':[{'book':'Morgan & Mikhail','page':1563}],'confusable_with':'therapeutic heparin or higher-dose SC heparin (requires longer delay and anti-Xa monitoring)'},
    {'id':'hit-cardiac-d6','topic':t,'domain':dom,'discipline':disc,'stem':'What intraoperative blood conservation technique involving platelet-rich plasma can be employed at centers to reduce transfusion requirements after CPB in HIT patients?','answer':'Preoperative collection of platelet-rich plasma by pheresis before CPB, with reinfusion after bypass, can decrease bleeding and reduce transfusion requirements.','rationale':'Sequestering functional platelets before systemic heparinization and the mechanical stress of CPB preserves them from activation/consumption, allowing reinfusion when most needed.','bloom':'apply','source':[{'book':'Morgan & Mikhail','page':740}],'confusable_with':'cell salvage (recovers red cells, not platelets)'},
    {'id':'hit-cardiac-d7','topic':t,'domain':dom,'discipline':disc,'stem':'What hemostasis principle requires multidisciplinary team approach when managing anticoagulated patients perioperatively?','answer':'Careful preoperative assessment of patients on antithrombotic therapy, with a multidisciplinary approach involving the patient, primary care physician, hematologist, surgeon, and anesthesia provider, is essential for perioperative safety.','rationale':'Balancing thrombotic risk from stopping anticoagulation against bleeding risk from continuing it requires individualized risk stratification that no single specialty can optimally provide alone.','bloom':'apply','source':[{'book':'Miller/Baby Miller','page':459}],'confusable_with':''},
]
out.append({'_type':'illness_script','topic':'Heparin-Induced Thrombocytopenia (HIT) & Cardiac Surgery','discipline':disc,'enabling_conditions':'Prior heparin exposure (IV or SC), cardiac or orthopedic surgery patients receiving heparin, ICU patients on heparin infusions','pathophysiology':'IgG antibodies against heparin-PF4 complexes activate platelets via FcgammaRIIA, causing platelet consumption (thrombocytopenia) and procoagulant microparticle release (paradoxical thrombosis)','time_course':'Platelet fall typically begins 5-10 days after heparin initiation; rapid-onset HIT possible within 24 hours if prior sensitization within 100 days','key_features':'Platelet count fall >50% from baseline (typically to 50-100k), new thrombosis (venous > arterial), positive 4T score, confirmed by PF4 ELISA and serotonin release assay','consequence_if_missed':'Continued heparin administration worsens platelet consumption and causes life-threatening arterial/venous thromboembolism (white clot syndrome); limb loss, PE, stroke, death'})

# 237: Hepatic disease and cirrhosis risk assessment
t = 'Hepatic disease and cirrhosis risk assessment'
dom = 'Preoperative evaluation & perioperative medicine (risk stratification, cardiac/pulmonary/endocrine optimization, NPO & aspiration risk, chronic medication management, frailty, consent)'
disc = 'anesthesia'
out += [
    {'id':'hepatic-cirrhosis-d1','topic':t,'domain':dom,'discipline':disc,'stem':'Splanchnic nerve stimulation from pain or surgical stress affects hepatic blood flow through what mechanism?','answer':'Splanchnic nerve stimulation increases splanchnic vascular resistance and decreases hepatic blood flow by up to 60%, particularly with operative procedures near the liver.','rationale':'The splanchnic vasculature receives sympathetic innervation; surgical stress-mediated catecholamine release causes vasoconstriction that reduces portal and hepatic arterial inflow.','bloom':'analyze','source':[{'book':'Miller/Baby Miller','page':530}],'confusable_with':'direct hepatic compression (mechanical cause of reduced flow, different from neurogenic vasoconstriction)'},
    {'id':'hepatic-cirrhosis-d2','topic':t,'domain':dom,'discipline':disc,'stem':'A cirrhotic patient develops biliary spasm after opioid administration. What three agents can be used to treat biliary spasm?','answer':'Biliary spasm can be treated with naloxone (opioid reversal), glucagon (smooth muscle relaxation), or nitroglycerin (nitric oxide-mediated smooth muscle relaxation).','rationale':'Opioids increase common bile duct pressure via sphincter of Oddi contraction; naloxone reverses the mechanism directly while glucagon and nitrates provide non-opioid smooth muscle relaxation.','bloom':'recall','source':[{'book':'Miller/Baby Miller','page':537}],'confusable_with':'treating with additional opioids (worsens spasm)'},
    {'id':'hepatic-cirrhosis-d3','topic':t,'domain':dom,'discipline':disc,'stem':'In end-stage liver disease, what hepatocellular carcinoma screening and surveillance protocol is recommended?','answer':'Patients with cirrhosis have a 2-4% annual risk of HCC; ultrasound surveillance every 6 months is recommended, with AFP for additional stratification.','rationale':'HCC is often asymptomatic until advanced; surveillance in cirrhotic patients (the primary risk group) enables detection at resectable or transplantable stages.','bloom':'apply','source':[{'book':'MGH Housestaff Manual','page':96}],'confusable_with':'one-time CT screening (not adequate; HCC develops continuously in cirrhotic liver)'},
    {'id':'hepatic-cirrhosis-d4','topic':t,'domain':dom,'discipline':disc,'stem':'A cirrhotic patient receiving an aldosterone antagonist develops hypokalemia. Why is potassium repletion important in this setting?','answer':'Hypokalemia in cirrhosis is associated with increased myocardial excitability and arrhythmia risk; careful potassium repletion is required to restore intracellular and extracellular potassium balance.','rationale':'Hepatic cirrhosis causes secondary hyperaldosteronism; aldosterone antagonists (spironolactone) treat ascites but can cause electrolyte shifts; hypokalemia lowers the resting membrane potential and increases arrhythmia susceptibility.','bloom':'apply','source':[{'book':'Miller/Baby Miller','page':550}],'confusable_with':'hyperkalemia (more common with ACEi/ARB or severe renal impairment in cirrhosis)'},
    {'id':'hepatic-cirrhosis-d5','topic':t,'domain':dom,'discipline':disc,'stem':'What clinical features of hepatic encephalopathy are detectable only by neuropsychological testing and not by clinical examination?','answer':'Minimal hepatic encephalopathy (MHE) produces subtle cognitive deficits detectable by neuropsychological testing but without overt signs; patients may have driving impairment and reduced quality of life.','rationale':'MHE represents the earliest stage of hepatic encephalopathy; it is clinically silent but neuropsychological testing reveals processing speed, attention, and working memory deficits.','bloom':'analyze','source':[{'book':'StatPearls: StatPearls   Hepatic Encephalopathy','page':14}],'confusable_with':'overt hepatic encephalopathy (asterixis, confusion, altered consciousness - clinically evident)'},
    {'id':'hepatic-cirrhosis-d6','topic':t,'domain':dom,'discipline':disc,'stem':'Liver disease is included as a risk factor in the HAS-BLED score for anticoagulation bleeding risk in AF. What liver function abnormalities qualify?','answer':'Liver disease qualifying for HAS-BLED = cirrhosis OR bilirubin >2x ULN OR AST/ALT/AlkPhos >3x ULN.','rationale':'Hepatic synthetic dysfunction impairs coagulation factor production, and portal hypertension causes varices; both increase anticoagulation-related bleeding risk in AF patients.','bloom':'recall','source':[{'book':'MGH Housestaff Manual','page':14}],'confusable_with':'any elevated LFT (only significant elevations qualify, not mild transaminase changes)'},
    {'id':'hepatic-cirrhosis-d7','topic':t,'domain':dom,'discipline':disc,'stem':'What are the three types of hepatic encephalopathy (HE) classified by underlying liver disease?','answer':'Type A: HE associated with acute liver failure; Type B: HE with portosystemic bypass without intrinsic liver disease; Type C: HE with cirrhosis (subdivided into episodic, persistent, and minimal).','rationale':'The type-A/B/C classification guides treatment: Type A requires acute liver failure management; Type C (most common) is managed with lactulose, rifaximin, and precipitant removal.','bloom':'recall','source':[{'book':'StatPearls: StatPearls   Hepatic Encephalopathy','page':14}],'confusable_with':'West Haven grade (grading overt HE severity, not etiology classification)'},
]
out.append({'_type':'illness_script','topic':'Hepatic disease and cirrhosis risk assessment','discipline':disc,'enabling_conditions':'Alcohol use disorder, chronic HBV/HCV infection, NAFLD/metabolic syndrome; end-stage liver disease presenting for elective or emergency surgery','pathophysiology':'Hepatic synthetic failure (reduced albumin, coagulation factors, drug metabolism) + portal hypertension (varices, ascites, hypersplenism) + hepatic encephalopathy from accumulated nitrogenous waste and GABA-ergic neurotoxins','time_course':'Compensated cirrhosis may be asymptomatic for years; decompensation (jaundice, ascites, variceal bleed, HE) marks transition to high perioperative mortality','key_features':'Low albumin, prolonged PT/INR, elevated bilirubin, thrombocytopenia, asterixis, ascites; Child-Pugh or MELD scores quantify risk','consequence_if_missed':'Unrecognized decompensated cirrhosis leads to catastrophic perioperative bleeding from coagulopathy/varices, acute-on-chronic liver failure, and mortality rates >30% for abdominal surgery in Child-Pugh C'})

with open('data/kp_redeep_part7_batch3.json','w',encoding='utf-8') as f:
    json.dump(out, f, ensure_ascii=False, indent=2)
print('batch3 done, count:', len(out))
