#!/usr/bin/env python3
"""Phase 2 GI bleeding knowledge base: upper & lower, diagnosis, management."""

import json
from datetime import datetime
from pathlib import Path

PHASE2_GI_BLEEDING_UNITS = [
    # UPPER GI BLEED BASICS (15 units)
    {"topic": "Upper GI Bleed (UGIB) Epidemiology and Presentation", "subtopic": "ugib_basics", "content": "UGIB: bleeding proximal to ligament of Treitz (esophagus, stomach, duodenum, proximal jejunum). Incidence 50-100 per 100,000 annually. Mortality 5-15% (higher in elderly, comorbidities). Presenting as hematemesis (bright red or coffee ground), melena (black tarry stools, suggests proximal source), or positive nasogastric tube aspirate. Severity: vital sign abnormalities (tachycardia, hypotension), altered mental status indicate significant blood loss.", "tags": ["ugib", "epidemiology"], "library": "intern_year_medicine"},
    {"topic": "Peptic Ulcer Disease (PUD) - Risk Factors and Pathophysiology", "subtopic": "ugib_etiology", "content": "PUD: gastric or duodenal ulcers (20-30% of UGIB). Risk factors: H. pylori infection (90% risk if colonized), NSAIDs (20-30% long-term users), stress ulcers (surgery, sepsis, mechanical ventilation), PPI use (rare). Pathophysiology: mucosal erosion >2mm, through submucosa into mucosa. Presents with epigastric pain (may be absent in elderly), GI bleed, perforation (pain, free air, peritonitis). Diagnosis: EGD with ulcer visualization. Duodenal ulcers more common than gastric, less likely to malignancy.", "tags": ["ugib", "pud"], "library": "intern_year_medicine"},
    {"topic": "Variceal Bleeding in Cirrhosis - Pathophysiology and Outcomes", "subtopic": "ugib_varices", "content": "Variceal bleeding: occurs if portal pressure gradient >12 mmHg (hepatic encephalopathy/portal vein gradient measurement). Incidence in cirrhosis: 5-15% yearly if varices present. Mortality: 20-50% first bleed if untreated, 15% with treatment. Presentation: massive hematemesis, hypotension, shock (often rapid exsanguination). Risk factors: Child-Pugh score, bilirubin, INR, variceal size, red signs on endoscopy. Prognosis: depends on liver synthetic function, etiology (variceal bleeding worse than non-variceal in cirrhosis).", "tags": ["ugib", "varices", "cirrhosis"], "library": "intern_year_medicine"},
    {"topic": "Esophagitis, Mallory-Weiss Tear, Boerhaave Syndrome", "subtopic": "ugib_etiology", "content": "Esophagitis: inflammation from reflux (GERD), caustic ingestion, infection (CMV/HSV in immunocompromised). Presents with dysphagia, chest pain. Mallory-Weiss tear: mucosal laceration at GE junction from forceful vomiting (especially alcohol). Usually self-limited bleeding, 10-15% need intervention. Boerhaave syndrome: full-thickness esophageal rupture (forceful vomiting/straining). Presents with sudden chest pain, subcutaneous emphysema, mediastinitis, sepsis. Mortality 10-30% even with surgery; diagnosis with contrast esophagography. Requires emergency surgery.", "tags": ["ugib", "esophageal"], "library": "intern_year_medicine"},
    {"topic": "Gastric Cancer and Portal Hypertensive Gastropathy", "subtopic": "ugib_etiology", "content": "Gastric cancer: can present as UGIB. Risk: H. pylori, smoking, family history. Diagnosis: EGD with biopsy of gastric ulcer/mass. Portal hypertensive gastropathy: gastric mucosal ectasia in portal hypertension, can bleed. Antral predominance typical. Diagnosis: endoscopy appearance. Treatment differs from varices (less variceal banding effective). Beta-blockers for primary/secondary prophylaxis. Gastric cancer managed with surgery/oncology consultation.", "tags": ["ugib", "cancer", "portal_htn"], "library": "intern_year_medicine"},
    {"topic": "UGIB Initial Management - Resuscitation and Stabilization", "subtopic": "ugib_management", "content": "Initial UGIB management: place 2 large-bore IVs, type and cross, CBC/CMP/coagulation, lactate. Supplemental O2 if hypoxic. NPO status. Continuous cardiac monitoring. Contact GI for urgent endoscopy (within 24 hours standard, <1 hour if variceal/massive). Nasogastric tube (check for blood, helps confirm UGIB location). Pharmacotherapy: PPI bolus 80mg IV, then infusion 8 mg/hr for PUD. Octreotide 50 mcg IV bolus, then 50 mcg/hr infusion for suspected variceal (start before endoscopy if likely). Correct coagulopathy if INR >1.5, platelet <50k.", "tags": ["ugib", "management", "acute"], "library": "intern_year_medicine"},
    {"topic": "Glasgow-Blatchford Score vs AIMS65 for UGIB Risk Stratification", "subtopic": "ugib_risk_stratification", "content": "Glasgow-Blatchford: predicts need for intervention in UGIB (0-23 points, higher = higher risk). Components: age, sex, shock (pulse, SBP), comorbidity, bleeding (Hgb, melena). Score 0: <5% need intervention; can discharge without endoscopy (selected patients). AIMS65: mortality prediction (age ≥65, INR >1.5, mental status altered, SBP <100, endoscopic findings). Score 0: low mortality (<1%); score >2: high mortality (>20%). Both useful for risk stratification but don't replace clinical judgment. Endoscopy still gold standard for diagnosis/treatment.", "tags": ["ugib", "risk_stratification"], "library": "intern_year_medicine"},
    {"topic": "Proton Pump Inhibitor (PPI) Therapy in UGIB", "subtopic": "ugib_treatment", "content": "PPI for PUD bleeding: omeprazole 80mg IV bolus, then 8 mg/hr continuous infusion x 72 hours, then PO dose (optimal regimen). High-dose IV PPI reduces rebleeding (5-10% vs 15-20% if not treated), mortality. Duration: continue IV 72h post-endoscopy if PUD visualized, then switch to PO daily x 4 weeks minimum. Confirm H. pylori status; treat if positive (7-14 day triple/quadruple therapy). Stop NSAIDs if possible. Recheck H. pylori eradication 4 weeks post-treatment (confirm success). PPIs generally safe; long-term use risks: hypomagnesemia, C. difficile, vitamin B12 deficiency.", "tags": ["ugib", "treatment", "ppi"], "library": "intern_year_medicine"},
    {"topic": "Octreotide and Antibiotics in Variceal Bleeding", "subtopic": "ugib_varices", "content": "Octreotide (somatostatin analog): reduces portal pressure, controls variceal bleeding in 80% cases. Dosing: 50 mcg IV bolus, then 50 mcg/hr continuous infusion x 2-5 days. Start BEFORE endoscopy if variceal bleeding suspected. Antibiotics in variceal bleeding: ceftriaxone 1g IV daily (preferred) or norfloxacin 400mg PO BID x 7 days. Reduces bacterial infection (SBP, bacteremia), mortality 20-30%. Mechanism: gut sterilization, reduced translocation. Must start with octreotide/endoscopic therapy, not antibiotics alone.", "tags": ["ugib", "varices", "treatment"], "library": "intern_year_medicine"},
    {"topic": "Endoscopic Hemostasis Techniques - Injection, Thermal, Banding", "subtopic": "ugib_endoscopy", "content": "Endoscopic hemostasis (gold standard for UGIB management): (1) Injection: epinephrine 1:10,000 (4-10 mL submucosal injection around bleeding vessel), followed by sclerosant (sodium tetradecyl sulfate) or cyanoacrylate. (2) Thermal: electrocautery (bipolar or heater probe), argon plasma coagulation (APC). (3) Mechanical: variceal banding (elastic bands around varices), clips. Success rate 90-95% for PUD, 80-90% for varices. Rebleeding: 10-30% if PUD, 30-50% if varices (may need repeat endoscopy). Two-third of ulcers have visible vessel or clot; these need treatment (active bleeding vs oozing). Clean-base ulcers: low rebleeding risk, no intervention.", "tags": ["ugib", "endoscopy", "hemostasis"], "library": "intern_year_medicine"},
    {"topic": "Rebleeding Risk Stratification and Surgical Consult Indications", "subtopic": "ugib_management", "content": "Rebleeding risk factors: large ulcer (>2cm), location (posterior duodenal = high risk, gastric body/fundus = high risk), visible vessel/active bleeding, hemodynamic instability. Surgical consultation if: failure of endoscopic hemostasis (second attempt if first fails, 80% success; >2 failed attempts = surgical consideration), massive transfusion requirement (>6 units/8 hours), hemodynamic instability despite resuscitation, perforation suspected. Surgical options: antrectomy ± vagotomy (PUD), oversewing vessel ± transfusion, partial gastrectomy (gastric cancer). Mortality surgery 10-30%.", "tags": ["ugib", "management", "surgery"], "library": "intern_year_medicine"},
    {"topic": "Transfusion Strategy in UGIB - Restrictive vs Liberal", "subtopic": "ugib_management", "content": "Restrictive transfusion strategy: transfuse PRBCs target Hgb 7-9 g/dL (not 10 g/dL as historically). Benefits: reduce transfusion volume, fewer complications (infection, ARDS, volume overload), lower mortality in some trials. Apply in stable patients; transfuse more liberally if: active bleeding, cardiac disease, ongoing hemorrhage, Hgb <7. Fresh frozen plasma (FFP): only if INR >1.5 (NOT for Hgb <10 alone). Platelets if <50k and actively bleeding. Avoid coagulopathy over-correction (increases thrombotic risk). Consider massive transfusion protocol if >4 units RBC/hour (include FFP, platelets in 1:1:1 ratio).", "tags": ["ugib", "transfusion"], "library": "intern_year_medicine"},
    {"topic": "TIPS (Transjugular Intrahepatic Portosystemic Shunt) Indications", "subtopic": "ugib_varices", "content": "TIPS: radiologic procedure creating shunt between portal vein and hepatic vein to reduce portal pressure. Indications in variceal bleeding: refractory bleeding (failure of variceal banding + octreotide + antibiotics, <20% of cases), as bridge to transplant, prophylaxis for recurrent bleeding despite banding. Timing: within 24-48 hours of failed endoscopy. Contraindications: encephalopathy (worsens with TIPS), right heart failure, portal vein thrombosis. Complications: shunt thrombosis (40% by 1 year, treated with thrombolysis/revision), encephalopathy (30%), hepatic decompensation. Reduces mortality vs repeat bleeds but transplantation ultimately definitive for decompensated cirrhosis.", "tags": ["ugib", "varices", "tips"], "library": "intern_year_medicine"},

    # LOWER GI BLEED (12 units)
    {"topic": "Lower GI Bleed (LGIB) Epidemiology and Etiologies", "subtopic": "lgib_basics", "content": "LGIB: bleeding distal to ligament of Treitz (colon, rectum). Incidence 20-30 per 100,000 annually. Mortality 2-4%. Etiologies: diverticulosis (30-40%), internal hemorrhoids (15-25%), angiodysplasia (5-10%), IBD (Crohn's, UC, 5-10%), ischemic colitis (5%), infectious colitis (C. difficile, etc, 3-5%). Presentation: bright red blood per rectum (hematochezia) or maroon stools. 90% LGIB self-limited; 15% require intervention (emergency endoscopy/colonoscopy/angiography).", "tags": ["lgib", "epidemiology"], "library": "intern_year_medicine"},
    {"topic": "Diverticulosis and Diverticulitis - Distinction and Management", "subtopic": "lgib_etiology", "content": "Diverticulosis: outpouchings of colon mucosa (especially sigmoid, low-fiber diet risk). Most asymptomatic; 10-20% develop diverticulitis (inflammation/microperforation). Presentation in diverticulitis: LLQ pain, fever, diarrhea, leukocytosis. Diverticular bleeding: painless, brisk (bright red or maroon), usually self-limited. Diagnosis: colonoscopy (shows diverticula, rules out other causes), CT if perforation suspected (free air, pericolonic stranding). Management: no specific treatment for uncomplicated diverticulosis (no prophylactic antibiotics recommended); diverticulitis = antibiotics ± percutaneous drainage if abscess; avoid colonoscopy during active inflammation (perforation risk).", "tags": ["lgib", "diverticulosis"], "library": "intern_year_medicine"},
    {"topic": "Inflammatory Bowel Disease (IBD) - Crohn's vs Ulcerative Colitis", "subtopic": "lgib_etiology", "content": "Crohn's disease: transmural inflammation (any part GI tract, 40% small bowel), cobblestone appearance, skip lesions, fistulas/strictures. Ulcerative colitis: mucosal/submucosal inflammation (colon/rectum only), continuous involvement, pseudopolyps. Both can present with GI bleed (usually chronic rather than massive). Extraintestinal manifestations: joint pain, uveitis, erythema nodosum, primary sclerosing cholangitis. Diagnosis: endoscopy + biopsy (granulomas in Crohn's, crypt distortion UC). Management: corticosteroids, aminosalicylates (mesalamine), immune modulators (azathioprine, 6-MP), anti-TNF biologics (infliximab, adalimumab), surgical resection if refractory.", "tags": ["lgib", "ibd"], "library": "intern_year_medicine"},
    {"topic": "Angiodysplasia (Vascular Malformations) - Recognition and Treatment", "subtopic": "lgib_etiology", "content": "Angiodysplasia: small submucosal vascular malformations, right colon predominance. Risk: advanced age, aortic stenosis, renal failure (uremic toxins damage vessels). Presents with chronic GI bleeding (may cause iron-deficiency anemia, obscure GI bleed if small). Diagnosis: colonoscopy (appears as spider-web vessels, cherry-red lesions) or capsule endoscopy. Endoscopic hemostasis: argon plasma coagulation (APC), electrocautery, injection, clips. Angiographic embolization if endoscopy fails. Prone to recurrence; may require repeat interventions. Chronic anticoagulation increases bleeding risk.", "tags": ["lgib", "angiodysplasia"], "library": "intern_year_medicine"},
    {"topic": "Ischemic Colitis - Pathophysiology and Clinical Presentation", "subtopic": "lgib_etiology", "content": "Ischemic colitis: reduced colonic blood flow (usually right or left colon, sparing rectum which has dual blood supply). Risk: age >60, cardiovascular disease, hypotension, arrhythmias, hypercoagulable state. Presentation: acute abdominal pain, bloody diarrhea, fever. Mild-moderate: mucosal ulceration; severe: transmural necrosis (perforation risk). Diagnosis: colonoscopy (pale, cyanotic mucosa, ulcers), CT (thumbprinting sign, wall thickening). Management: supportive (IV fluids, antibiotics if septic), NPO, surgery if perforation/peritonitis. Prognosis: 80% improve with supportive care; 20% progress to fulminant disease/death.", "tags": ["lgib", "ischemic_colitis"], "library": "intern_year_medicine"},
    {"topic": "Infectious Colitis - C. difficile and Other Pathogens", "subtopic": "lgib_etiology", "content": "C. difficile: leading cause antibiotic-associated colitis; toxins A/B damage mucosa, 5-10% develop toxic megacolon/perforation. Risk: antibiotics, age >65, immunosuppression, hospitalization. Presentation: watery diarrhea, abdominal pain, fever, leukocytosis, elevated creatinine. Diagnosis: stool PCR for toxin genes (most sensitive), or toxin enzyme immunoassay. Management: stop offending antibiotic if possible, metronidazole 500mg TID x 10 days (mild-moderate), vancomycin 125mg QID x 10 days (severe: Cr >1.5x baseline, WBC >15k, severe colitis). Fidaxocin if recurrent (lower relapse). Avoid antiperistaltic agents (increase toxic megacolon risk).", "tags": ["lgib", "cdiff"], "library": "intern_year_medicine"},
    {"topic": "Internal and External Hemorrhoids - Distinction and Management", "subtopic": "lgib_etiology", "content": "Internal hemorrhoids: above dentate line, painless (visceral innervation), bright red blood on paper/toilet, may prolapse. External hemorrhoids: below dentate line, painful (somatic innervation), visible/palpable. Diagnosis: visual inspection, anoscopy (internal), digital rectal exam (external). Management: conservative = high-fiber diet, stool softeners, sitz baths. Procedures: rubber-band ligation (internal), sclerotherapy, coagulation. Surgery (hemorrhoidectomy) reserved for refractory cases. Complications: thrombosis (painful, treat with surgical drainage if severe/painful), bleeding (usually self-limited). Not life-threatening but most common cause LGIB.", "tags": ["lgib", "hemorrhoids"], "library": "intern_year_medicine"},
    {"topic": "Meckel's Diverticulum - Classic Presentation and Diagnosis", "subtopic": "lgib_etiology", "content": "Meckel's diverticulum: remnant of vitelline duct (embryologic structure), present in 2% population. Rule of 2's: 2% prevalence, 2 feet from ileocecal valve, 2 inches long, 2% symptomatic. Symptoms: painless GI bleed (bright red, brisk), intestinal obstruction, intussusception, diverticulitis (mimics appendicitis). Contains ectopic tissue: 50% gastric mucosa (produces acid causing ileal ulceration/bleeding). Diagnosis: Meckel scan (technetium-99m pertechnetate binds to gastric mucosa), CT enterography, capsule endoscopy (variable sensitivity). Treatment: surgical resection if symptomatic or symptomatic potential. Bleeding risk highest in children/young adults.", "tags": ["lgib", "meckel"], "library": "intern_year_medicine"},
    {"topic": "Colonoscopy in LGIB - Indications and Timing", "subtopic": "lgib_diagnosis", "content": "Colonoscopy: gold standard for LGIB diagnosis (90% localize source). Indications: active/recent hematochezia, iron-deficiency anemia, positive FOBT. Timing: urgent (<24 hours) if hemodynamically unstable/high-risk bleeding (variceal equivalent in lower GI = diverticulosis/angiodysplasia in elderly); elective (within 1 week) if stable, minor bleeding. Preparation: bowel prep (GoLYTELY, MiraLAX) critical for visualization. Hemostasis: APC, electrocautery, injection, clips as for UGIB. Success rate: 80-90% of bleeding sources identified and treated. Risks: perforation (0.1%), bleeding complication (0.1%), aspiration.", "tags": ["lgib", "diagnosis", "colonoscopy"], "library": "intern_year_medicine"},
    {"topic": "Capsule Endoscopy and Enterography for Obscure GI Bleeding", "subtopic": "lgib_diagnosis", "content": "Obscure GI bleeding: bleeding without identified source on EGD/colonoscopy. Incidence 5-10% LGIB. Capsule endoscopy: wireless camera pill ingested, transmits images. Sensitivity 50-75% for small bowel bleeding (better than push enteroscopy). Limitations: cannot obtain biopsy/perform hemostasis, retained capsule risk if stricture. Video capsule endoscopy can identify angiodysplasia, Meckel's diverticulum, small bowel Crohn's. Enterography: CT or MR enterography shows anatomy, can miss small lesions <2cm. Angiography: if active bleeding (>2 mL/min), can localize and treat (embolization). Capsule endoscopy first-line for obscure LGIB after normal colonoscopy.", "tags": ["lgib", "diagnosis", "obscure"], "library": "intern_year_medicine"},
    {"topic": "Anticoagulation Reversal in GI Bleeding", "subtopic": "gi_bleeding_anticoagulation", "content": "GI bleeding in anticoagulated patients: increase mortality/complications. Management: resuscitate, obtain hemostasis endoscopically. Reverse anticoagulation if major bleed: warfarin = FFP/PCC + vitamin K (see UGIB section), DOACs = idarucizumab (dabigatran) or andexanet (apixaban/rivaroxaban) if available, LMWH = protamine if recent dose. Risk-benefit: reversing anticoagulation = thrombotic event risk (stroke, MI, PE if original indication was afib/VTE). Hold anticoagulation temporarily (3-5 days) if minor bleed; restart once hemostasis achieved. Discuss with anticoagulation/cardiology team for long-term plan (may resume on different agent/higher dose PPI).", "tags": ["gi_bleeding", "anticoagulation"], "library": "intern_year_medicine"},
    {"topic": "Post-Polypectomy Hemorrhage - Prevention and Management", "subtopic": "gi_bleeding_complications", "content": "Post-polypectomy hemorrhage: can occur immediately (<24 hours, usually during procedure) or delayed (>24 hours post-polypectomy). Incidence: 1-3% (higher with large polyps, anticoagulation, certain polyp types). Delayed bleeding: patient presents with hematochezia 3-7 days post-procedure. Risk factors: anticoagulation, large polyp (>2cm), antiplatelet therapy. Prevention: pre-procedure clips (prophylactic hemoclips), submucosal epinephrine injection, hot-snare for large polyps. Management: urgent colonoscopy for delayed bleed, repeat endoscopic hemostasis (clips, injection, thermal), transfusion support if needed. Surgery rare (<5%). Resumption of anticoagulation: delayed 5-7 days if minor bleeding, longer if major.", "tags": ["gi_bleeding", "complications"], "library": "intern_year_medicine"},
]

def main():
    output_dir = Path("C:/Users/Dean/anesthesia_attending/data")
    output_file = output_dir / "phase2_gi_bleeding_chunks.json"
    output_dir.mkdir(parents=True, exist_ok=True)

    for idx, unit in enumerate(PHASE2_GI_BLEEDING_UNITS):
        unit["id"] = f"phase2_gi_bleeding_unit_{idx}"
        if "library" not in unit:
            unit["library"] = "intern_year_medicine"
        unit["created_at"] = datetime.now().isoformat()

    with open(output_file, "w") as f:
        for unit in PHASE2_GI_BLEEDING_UNITS:
            f.write(json.dumps(unit) + "\n")

    print(f"Generated {len(PHASE2_GI_BLEEDING_UNITS)} GI bleeding knowledge units")
    print(f"Output: {output_file}")
    return len(PHASE2_GI_BLEEDING_UNITS)

if __name__ == "__main__":
    main()
