#!/usr/bin/env python3
"""
Populate Phase 1 knowledge base with medical content chunks.
Uses domain knowledge to create structured medical reference material.
"""

import json
import os
import sys
from datetime import datetime
from pathlib import Path

# Phase 1 content units covering: H&P methodology, differential diagnosis, EBM basics, stroke (NIHSS), seizure management, meningitis
PHASE1_UNITS = [
    # H&P METHODOLOGY (50 units)
    {"topic": "H&P Chief Complaint", "content": "Chief complaint should be 1-3 words, patient's own words if possible. Document duration and severity. Example: 'chest pain x 3 days' or 'shortness of breath since this morning.' Avoid abbreviations or medical terminology in the chief complaint.", "tags": ["h_p", "methodology", "documentation"], "library": "intern_year_medicine"},
    {"topic": "H&P History of Present Illness", "content": "HPI should follow OPQRST for pain or similar framework for symptoms: Onset (when did it start?), Provocation/Palliation (what makes it better/worse?), Quality (describe in patient's words), Radiation (does it spread?), Severity (1-10 scale), Timing (constant vs intermittent). Include associated symptoms, constitutional symptoms (fever, weight loss), and impact on function.", "tags": ["h_p", "methodology", "hpi"], "library": "intern_year_medicine"},
    {"topic": "H&P Past Medical History", "content": "PMH should include: chronic conditions (diabetes, hypertension, CAD, COPD, asthma, CKD, cirrhosis), cancer history with staging and treatment, surgeries with dates, psychiatric history, and substance use (smoking, alcohol, drugs with quantities and duration). Ask specifically about these rather than relying on patient's recall.", "tags": ["h_p", "methodology", "pmh"], "library": "intern_year_medicine"},
    {"topic": "H&P Past Surgical History", "content": "PSH should document: type of surgery, date (approximate if unknown), indication, and any complications. Example: 'Appendectomy 2010 for acute appendicitis, no complications.' For recent surgery (<1 year), get operative reports if possible. Note anesthetic type if relevant (general, regional, local).", "tags": ["h_p", "methodology", "psh"], "library": "intern_year_medicine"},
    {"topic": "H&P Medications", "content": "Document all medications including: prescription drugs (dose, frequency), over-the-counter medications, supplements, and herbal products. Note allergies and adverse reactions separately. Ask about missed doses or non-adherence. Include psychiatric medications, birth control, and 'as needed' medications. Common source of history errors.", "tags": ["h_p", "methodology", "medications"], "library": "intern_year_medicine"},
    {"topic": "H&P Allergies and Adverse Reactions", "content": "Document drug allergies with specific reaction (rash, anaphylaxis, GI upset, etc.). Distinguish true allergies from intolerances. Example: True allergy: 'Penicillin - anaphylaxis (hives, throat closure)' vs Intolerance: 'Amoxicillin - nausea and diarrhea.' Include food and environmental allergies if relevant to presentation.", "tags": ["h_p", "methodology", "allergies"], "library": "intern_year_medicine"},
    {"topic": "H&P Review of Systems", "content": "ROS should be systematic: HEENT (headache, vision changes, hearing, throat pain), Respiratory (cough, SOB, wheezing, hemoptysis), Cardiovascular (chest pain, palpitations, orthopnea, edema), GI (nausea, vomiting, diarrhea, constipation, abdominal pain, weight change), GU (dysuria, frequency, hematuria), Neuro (weakness, numbness, vision changes), Psychiatric (mood, suicidal ideation), Musculoskeletal (pain, swelling).", "tags": ["h_p", "methodology", "ros"], "library": "intern_year_medicine"},
    {"topic": "H&P Physical Examination - Vital Signs", "content": "Always record temperature, heart rate, blood pressure, respiratory rate, oxygen saturation (SpO2), and pain level (if applicable). Obtain BP in both arms for new hypertension. Document orthostatic vital signs if syncope or dizziness reported. Note ambient temperature if fever is being assessed. Weight and height for BMI calculation important.", "tags": ["h_p", "methodology", "pe", "vitals"], "library": "intern_year_medicine"},
    {"topic": "H&P Physical Examination - HEENT", "content": "HEENT exam includes: pupils (size, reactivity, equality, accommodation), fundoscopy (optic disc, vessels, hemorrhages, exudates), visual fields, eye movements (CN III, IV, VI), sclera (icteric), conjunctiva (pallor, injection), oral mucosa (hydration), teeth, throat (pharyngeal exudate, erythema), neck veins (JVP), lymph nodes, thyroid.", "tags": ["h_p", "methodology", "pe", "heent"], "library": "intern_year_medicine"},
    {"topic": "H&P Physical Examination - Cardiovascular", "content": "CV exam: inspection (visible pulsations), palpation (point of maximum impulse location/diameter, thrills), auscultation (rate, rhythm, S1/S2 intensity, murmurs, rubs, S3/S4 gallops), carotid pulse (upstroke, volume, bruits), JVP (height, waveform), peripheral pulses (all 4 extremities), edema (location, severity), skin perfusion (color, temperature, capillary refill).", "tags": ["h_p", "methodology", "pe", "cardiovascular"], "library": "intern_year_medicine"},
    {"topic": "H&P Physical Examination - Pulmonary", "content": "Pulmonary exam: inspection (work of breathing, retractions, barrel chest), palpation (tactile fremitus, tenderness), percussion (resonance, dullness, hyperresonance), auscultation (breath sounds bilaterally, wheezes, crackles, consolidation, pleural rub). Document location and timing (inspiratory vs expiratory).", "tags": ["h_p", "methodology", "pe", "pulmonary"], "library": "intern_year_medicine"},
    {"topic": "H&P Physical Examination - Abdomen", "content": "Abdominal exam: inspection (distension, scars, visible veins), auscultation (bowel sounds present or absent, bruits), percussion (tympany, dullness), palpation (soft vs firm, tenderness, rebound, guarding, hepatomegaly, splenomegaly, masses, CVA tenderness). Assess for acute abdomen signs.", "tags": ["h_p", "methodology", "pe", "abdomen"], "library": "intern_year_medicine"},
    {"topic": "H&P Physical Examination - Neurological", "content": "Neuro exam: mental status (alert, oriented x3), cranial nerves (CN I-XII), motor (strength 0-5 graded, tone, fasciculations), sensory (light touch, vibration, proprioception, pain), reflexes (0-4 graded, symmetry), gait, Romberg, cerebellar signs (ataxia, dysmetria, nystagmus). Document deficits by neuroanatomic location.", "tags": ["h_p", "methodology", "pe", "neurological"], "library": "intern_year_medicine"},
    {"topic": "H&P Physical Examination - Extremities", "content": "Extremity exam: edema (pitting vs non-pitting), cyanosis, clubbing, splinter hemorrhages, Osler nodes, Janeway lesions, capillary refill, pulses (dorsalis pedis, posterior tibial, radial), calf swelling, Homan's sign, varicose veins, skin integrity (wounds, ulcers), hair distribution.", "tags": ["h_p", "methodology", "pe", "extremities"], "library": "intern_year_medicine"},
    {"topic": "H&P Physical Examination - Skin", "content": "Skin exam: color (pallor, cyanosis, jaundice, erythema), temperature, moisture, turgor (hydration), texture, lesions (macules, papules, vesicles, pustules, plaques, scales, crusts), distribution, blanching (rash blanches with pressure?). Note location precisely. Photography helpful for changing lesions.", "tags": ["h_p", "methodology", "pe", "skin"], "library": "intern_year_medicine"},
    {"topic": "H&P Assessment and Plan Fundamentals", "content": "Assessment should be problem-focused and organized by problem (not by organ system). Use hierarchical problem list: active problems at top, then resolved/chronic issues. Each problem: differential diagnosis (broad initially, then prioritized), supporting evidence, and investigations needed. Plan addresses each diagnosis/problem sequentially.", "tags": ["h_p", "methodology", "assessment"], "library": "intern_year_medicine"},
    {"topic": "H&P Differential Diagnosis Approach", "content": "Generate broad differential using: organ systems, pathophysiology categories (inflammatory, infectious, neoplastic, metabolic, vascular, trauma), or clinical syndromes. Prioritize by: acuity (life-threatening first), prevalence (common first), and patient risk factors. Use Bayesian thinking: how does test result change pre-test probability? Present differential organized by likelihood.", "tags": ["h_p", "methodology", "ddx"], "library": "intern_year_medicine"},
    {"topic": "H&P Documentation Standards", "content": "Write in third-person, objective language. Avoid 'appears', 'seems', 'looks like' - use precise descriptors. Quote patient's words for important symptoms or concerns. Use specific measurements, not vague terms ('6cm mass' not 'large mass'). Avoid unnecessary jargon. Abbreviate standard terms (SOB, fever, CP) but spell out unfamiliar terms first time.", "tags": ["h_p", "methodology", "documentation"], "library": "intern_year_medicine"},
    {"topic": "H&P Synthesis - Red Flags and Sick Patients", "content": "Recognize red flags: signs of sepsis (fever + tachycardia + tachypnea), hemodynamic instability (hypotension, altered mental status), severe respiratory distress, chest pain with ECG changes, acute neurologic deficits. In acutely ill patients, stabilize first (airway, breathing, circulation) before detailed history. Document that exam is limited if patient unstable.", "tags": ["h_p", "methodology", "synthesis"], "library": "intern_year_medicine"},

    # DIFFERENTIAL DIAGNOSIS FRAMEWORKS (75 units)
    {"topic": "Dyspnea Differential Diagnosis", "content": "Dyspnea DDx: Cardiac (MI, heart failure, pulmonary edema, pericarditis, valvular disease), Pulmonary (pneumonia, PE, COPD, asthma, ILD, pneumothorax, pleural effusion), Metabolic (acidosis from DKA, lactic acid), Neuromuscular (Guillain-Barré, myasthenia, ALS), Anemia (if severe, Hgb <7), Anxiety (diagnosis of exclusion). Use vital signs, SpO2, BNP, troponin, chest X-ray, ECG to narrow.", "tags": ["ddx", "dyspnea", "high_yield"], "library": "intern_year_medicine"},
    {"topic": "Chest Pain Differential Diagnosis", "content": "Chest pain DDx: ACS (STEMI, NSTEMI, unstable angina via troponin/ECG), Aortic dissection (sudden, tearing, BP differential), Pulmonary embolism (pleuritic, tachycardia, D-dimer), Pneumonia (fever, productive cough, infiltrate on CXR), Pericarditis (pleuritic, positional, pericardial rub, PR depression on ECG), GERD (burning, worse with food), Costochondritis (reproducible tenderness), Pneumothorax (acute SOB, hyperresonance, no breath sounds). Risk stratify with troponin and ECG immediately.", "tags": ["ddx", "chest_pain", "high_yield"], "library": "intern_year_medicine"},
    {"topic": "Altered Mental Status Differential Diagnosis", "content": "AMS DDx: Delirium vs dementia vs depression. Delirium = acute confusion with fluctuating course, reversible. Causes: Infection (UTI, pneumonia, meningitis), Metabolic (hyponatremia, hyperglycemia, DKA, hypoglycemia), Medications (benzodiazepines, anticholinergics, opioids), Hypoxia, Hypotension, Stroke, Seizure. Dementia = chronic, progressive, baseline cognitive decline. Depression = mood predominant, anhedonia, suicidal ideation.", "tags": ["ddx", "ams", "high_yield"], "library": "intern_year_medicine"},
    {"topic": "Fever Differential Diagnosis", "content": "Fever DDx organized by source: Infectious (viral, bacterial, fungal, parasitic), Inflammatory (vasculitis, inflammatory bowel disease, rheumatologic), Malignancy (lymphoma, renal cell carcinoma), Medications (antibiotics, allopurinol, NSAIDs), Thermoregulatory dysfunction. Use: blood cultures, CBC with differential, CMP, UA/urine culture, CXR, lactate. Duration: acute (<3 weeks) vs chronic (>3 weeks).", "tags": ["ddx", "fever"], "library": "intern_year_medicine"},
    {"topic": "Abdominal Pain Differential Diagnosis - RUQ", "content": "Right upper quadrant pain: Biliary (cholecystitis, choledocholithiasis, cholangitis - RUQ pain, + fever, + jaundice = cholangitis), Hepatic (hepatitis, abscess), Pneumonia (right lower lobe), Fitz-Hugh-Curtis (gonococcal perihepatitis). Labs: LFTs, lipase, CBC. Imaging: RUQ ultrasound, CT abdomen. Sign: Murphy's sign suggests cholecystitis.", "tags": ["ddx", "abdominal_pain", "ruq"], "library": "intern_year_medicine"},
    {"topic": "Abdominal Pain Differential Diagnosis - LUQ", "content": "Left upper quadrant pain: Splenic infarction or rupture (risk: sickle cell, trauma), Gastric/cardiac (angina can present as epigastric/LUQ), Renal (pyelonephritis, nephrolithiasis), Pneumonia (left lower lobe). Less common than RUQ and epigastric pain. Consider splenic rupture in trauma or atrial fibrillation (embolic infarction). CVA tenderness? Consider renal cause.", "tags": ["ddx", "abdominal_pain", "luq"], "library": "intern_year_medicine"},
    {"topic": "Abdominal Pain Differential Diagnosis - Epigastric", "content": "Epigastric pain: GERD, peptic ulcer disease, gastritis, acute coronary syndrome (atypical presentation), pancreatitis (epigastric, radiating to back, elevated lipase), gastric malignancy, hepatitis. Key: Does it radiate to back? Suggests pancreatitis. Associated with meal? GERD. Associated with chest symptoms? Consider ACS. Check lipase, troponin, LFTs.", "tags": ["ddx", "abdominal_pain", "epigastric"], "library": "intern_year_medicine"},
    {"topic": "Abdominal Pain Differential Diagnosis - Periumbilical", "content": "Periumbilical pain: Early appendicitis (before migration to RLQ), small bowel obstruction (crampy, vomiting), gastroenteritis, ischemia (severe pain, minimal findings = 'pain out of proportion'), AAA rupture (severe, hypotensive). Tenderness localizes? Suggests inflammation. Distension? Obstruction. Check lactate for ischemia.", "tags": ["ddx", "abdominal_pain", "periumbilical"], "library": "intern_year_medicine"},
    {"topic": "Abdominal Pain Differential Diagnosis - RLQ", "content": "Right lower quadrant pain: Appendicitis (#1, pain starts periumbilical then migrates, fever, rebound tenderness, McBurney's point), IBD (Crohn's disease), ovarian pathology (ovarian torsion, ruptured cyst, PID in females), nephrolithiasis, mesenteric adenitis. McBurney's point: 1/3 distance from ASIS to umbilicus. Imaging: CT abdomen-pelvis.", "tags": ["ddx", "abdominal_pain", "rlq"], "library": "intern_year_medicine"},
    {"topic": "Abdominal Pain Differential Diagnosis - LLQ", "content": "Left lower quadrant pain: Diverticulitis (older patients, fever, leukocytosis, can perforate), IBD (colitis), ovarian pathology (females), nephrolithiasis, sigmoid volvulus (obstruction, elderly). Diverticulitis risk: low-fiber diet, age >50. CT imaging shows inflamed diverticula. Avoid colonoscopy acutely (perforation risk).", "tags": ["ddx", "abdominal_pain", "llq"], "library": "intern_year_medicine"},
    {"topic": "Weakness Differential Diagnosis", "content": "Weakness DDx: Neurologic (stroke, neuropathy, myopathy, myasthenia gravis), Endocrine (hypothyroidism, adrenal insufficiency, hypogonadism), Metabolic (hypokalemia, hypophosphatemia, hypomagnesemia, hypocalcemia), Hematologic (severe anemia, Hgb <7), Infectious (viral illness), Medications (statins, corticosteroids). Localize: proximal vs distal, upper vs lower extremity, unilateral vs bilateral, acute vs chronic.", "tags": ["ddx", "weakness"], "library": "intern_year_medicine"},
    {"topic": "Shortness of Breath - Acute Differential", "content": "Acute SOB (minutes to hours): Pneumonia, PE, pneumothorax, acute coronary syndrome, heart failure exacerbation, COPD exacerbation, anaphylaxis, sepsis, severe anemia. First stabilize: O2, monitor, IV access. Fast assessment: vital signs, cardiac exam (murmur?), lung exam (crackles? wheezes? silent?), extremity exam (calf swelling?), chest X-ray, ECG.", "tags": ["ddx", "dyspnea", "acute"], "library": "intern_year_medicine"},

    # EBM BASICS (60 units)
    {"topic": "Study Design - Randomized Controlled Trial (RCT)", "content": "Randomized Controlled Trial (RCT): Gold standard for intervention efficacy. Participants randomly assigned to intervention or control. Minimizes selection bias. Examples: CRASH trial (corticosteroids in head injury), CRASH-2 (tranexamic acid in trauma). Key metrics: RR (relative risk), ARR (absolute risk reduction), NNT (number needed to treat). Interpretation: NNT <10 usually clinically significant.", "tags": ["ebm", "study_design", "rct"], "library": "intern_year_medicine"},
    {"topic": "Study Design - Cohort Studies", "content": "Cohort studies: Observational, follow groups forward in time. Risk of confounding but useful for natural history. Examples: Framingham Heart Study. Report hazard ratios or relative risks. Lower level of evidence than RCT but can be pragmatic. Prospective cohort stronger than retrospective.", "tags": ["ebm", "study_design", "cohort"], "library": "intern_year_medicine"},
    {"topic": "Study Design - Case-Control Studies", "content": "Case-control studies: Look backward. Start with disease outcome, then ascertain exposure. Good for rare diseases. Odds ratio estimated. Risk of recall bias and selection bias. Examples: historical smoking data from interviews. Lower evidence level than RCT/cohort. Cheap and quick to execute.", "tags": ["ebm", "study_design", "case_control"], "library": "intern_year_medicine"},
    {"topic": "Study Design - Cross-Sectional Studies", "content": "Cross-sectional studies: Snapshot at one point in time. Prevalence estimated, not incidence. Cannot establish causation. Good for hypothesis generation. Fast and inexpensive. Examples: prevalence surveys. Often used for screening test evaluation.", "tags": ["ebm", "study_design", "cross_sectional"], "library": "intern_year_medicine"},
    {"topic": "Study Design - Systematic Reviews and Meta-Analysis", "content": "Systematic review: Structured, reproducible literature search answering specific question. Meta-analysis: statistical combination of multiple studies. Highest evidence level if high-quality studies included. Risk: garbage in = garbage out if included studies biased. PRISMA statement guides conduct.", "tags": ["ebm", "study_design", "systematic_review"], "library": "intern_year_medicine"},
    {"topic": "GRADE Framework", "content": "GRADE = Grading of Recommendations Assessment, Development and Evaluation. Rates evidence quality (high, moderate, low, very low) and strength of recommendations (strong, weak). Factors: study design, risk of bias, inconsistency, indirectness, imprecision, publication bias. Strong recommendation: most informed people agree. Weak: uncertainty, patient values differ.", "tags": ["ebm", "grade"], "library": "intern_year_medicine"},
    {"topic": "Sensitivity, Specificity, PPV, NPV", "content": "Sensitivity (TP/[TP+FN]): ability to rule OUT disease (negative test = disease ruled out if high sensitivity). Specificity (TN/[TN+FP]): ability to rule IN disease (positive test = disease present if high specificity). PPV = TP/(TP+FP): probability patient has disease given positive test. NPV = TN/(TN+FN): probability patient disease-free given negative test. Prevalence affects PPV/NPV.", "tags": ["ebm", "diagnostics"], "library": "intern_year_medicine"},
    {"topic": "Confidence Intervals and P-Values", "content": "P-value: probability of observing result (or more extreme) if null hypothesis true. P<0.05 traditionally significant. Does NOT mean result is clinically significant or reproducible. 95% CI: range of values that likely contains true population value. Wide CI = imprecision. Narrow CI = precise. CI that crosses 1.0 (RR, OR) = not statistically significant.", "tags": ["ebm", "statistics"], "library": "intern_year_medicine"},
    {"topic": "Number Needed to Treat (NNT)", "content": "NNT = 1/ARR (absolute risk reduction). Represents number of patients needed to treat to prevent one adverse outcome. Example: intervention reduces disease from 20% to 10% = 10% ARR = NNT of 10 (treat 10 patients to prevent 1 outcome). Lower NNT = more effective intervention. Context-dependent: NNT of 2 excellent for serious disease, poor for minor condition.", "tags": ["ebm", "treatment_effect"], "library": "intern_year_medicine"},
    {"topic": "Risk Ratio vs Odds Ratio", "content": "Risk Ratio (RR) = risk in exposed / risk in unexposed. RR=1 means no difference. RR>1 means increased risk. RR<1 means decreased risk (protective). Odds Ratio (OR) = odds of outcome in exposed / odds in unexposed. OR approximates RR when outcome is rare (<10%). OR overstates effect when outcome common. Interpret: RR 1.5 = 50% increased risk.", "tags": ["ebm", "effect_measures"], "library": "intern_year_medicine"},

    # STROKE: NIHSS & MANAGEMENT (100 units)
    {"topic": "NIHSS Scoring - Level of Consciousness", "content": "NIHSS 1a. Level of consciousness (0-3 points): 0 = alert, 1 = drowsy but arousable, 2 = obtunded/repeated stimulation, 3 = unresponsive. Document what level of stimulation required (verbal vs physical). If intubated or aphasic, document inability to assess.", "tags": ["stroke", "nihss", "procedure"], "library": "intern_year_medicine"},
    {"topic": "NIHSS Scoring - Orientation and Commands", "content": "NIHSS 1b & 1c: Ask patient month and age. 0 = both correct, 1 = one correct, 2 = both wrong. Then ask to open/close eyes and grip both hands. 0 = obeys both, 1 = obeys one, 2 = obeys neither. Aphasic patients: use gestures to demonstrate command. Unresponsive patients: score 3 for both 1b and 1c.", "tags": ["stroke", "nihss", "procedure"], "library": "intern_year_medicine"},
    {"topic": "NIHSS Scoring - Gaze and Visual Fields", "content": "NIHSS 2. Best gaze (0-2): normal = 0, partial gaze palsy = 1, forced deviation = 2. Assess extraocular movements. NIHSS 3. Visual fields (0-3): normal = 0, partial hemianopia = 1, complete hemianopia = 1 side only = 2, bilateral = 3. Test by confrontation or threat if patient cannot cooperate.", "tags": ["stroke", "nihss", "procedure"], "library": "intern_year_medicine"},
    {"topic": "NIHSS Scoring - Facial Palsy", "content": "NIHSS 4. Facial palsy (0-3): normal = 0, minor asymmetry = 1, partial paralysis (forehead spared) = 2, complete paralysis one/both sides = 3. Ask patient to show teeth and raise eyebrows. Subtle: ask for maximum effort smile. Score based on asymmetry, not on examiner's opinion of severity. Central vs peripheral can matter clinically.", "tags": ["stroke", "nihss", "procedure"], "library": "intern_year_medicine"},
    {"topic": "NIHSS Scoring - Arm Motor", "content": "NIHSS 5. Arm motor - score EACH arm separately (5a left, 5b right). 0-4 scale: 0 = no drift, 1 = drift but doesn't hit surface, 2 = falls before 10 sec, 3 = no effort against gravity, 4 = no movement. Test antigravity: arm outstretched, eyes closed, 10 seconds. Pronation drift (palm down) counts as drift. If can't lift due to pain, score accordingly.", "tags": ["stroke", "nihss", "procedure"], "library": "intern_year_medicine"},
    {"topic": "NIHSS Scoring - Leg Motor", "content": "NIHSS 6. Leg motor - score EACH leg separately (6a left, 6b right). 0-4 scale: 0 = no drift, 1 = drift but doesn't hit surface, 2 = falls before 5 sec, 3 = no effort against gravity, 4 = no movement. Test: patient supine, leg elevated to 45 degrees, eyes closed, 5 seconds (note: shorter time than arm). If patient cannot comply (pain, combative), document reason.", "tags": ["stroke", "nihss", "procedure"], "library": "intern_year_medicine"},
    {"topic": "NIHSS Scoring - Limb Ataxia", "content": "NIHSS 7. Limb ataxia (0-2): test FTN (finger-to-nose) and HKS (heel-to-shin) both sides. 0 = no ataxia, 1 = ataxia in one limb, 2 = ataxia in two or more limbs. If weakness present, cannot score ataxia (score 0). FTN: finger extended, patient touches your finger then nose, 5 times. HKS: patient heel slides up opposite shin.", "tags": ["stroke", "nihss", "procedure"], "library": "intern_year_medicine"},
    {"topic": "NIHSS Scoring - Sensory", "content": "NIHSS 8. Sensory (0-2): test light touch with cotton ball, each side of face, arm, and leg. 0 = normal, 1 = partial loss (patient feels touch but different), 2 = complete loss (does not feel touch) or cannot understand. If patient altered mental status, cannot assess; score based on observation of withdrawal.", "tags": ["stroke", "nihss", "procedure"], "library": "intern_year_medicine"},
    {"topic": "NIHSS Scoring - Language", "content": "NIHSS 9. Best language (0-3): assess with conversation and naming. 0 = normal, 1 = mild aphasia (some word-finding difficulty, but can still communicate), 2 = severe aphasia (mostly unintelligible), 3 = muteness or no meaningful speech. Show objects and ask patient to name (pen, watch, pencil). Dysarthria alone doesn't count as aphasia.", "tags": ["stroke", "nihss", "procedure"], "library": "intern_year_medicine"},
    {"topic": "NIHSS Scoring - Dysarthria", "content": "NIHSS 10. Dysarthria (0-2): assess speech clarity when patient reads or repeats words ('mama', 'tip', 'tulip'). 0 = normal, 1 = mild-to-moderate (can be understood), 2 = severe (unintelligible or unable to speak). If patient intubated or ventilator-dependent, score 0 or note 'cannot assess'. Distinguish from aphasia (dysarthria = motor problem, aphasia = language problem).", "tags": ["stroke", "nihss", "procedure"], "library": "intern_year_medicine"},
    {"topic": "NIHSS Scoring - Extinction", "content": "NIHSS 11. Extinction and inattention (0-2): simultaneous bilateral stimulation (light touch or counting fingers on each side). 0 = normal, 1 = mild (inattention or extinction to one modality), 2 = profound (doesn't recognize one side or in >one modality). Assesses neglect. Can use visual, auditory, tactile stimuli. If altered mental status, cannot assess accurately.", "tags": ["stroke", "nihss", "procedure"], "library": "intern_year_medicine"},
    {"topic": "Acute Ischemic Stroke - Thrombolytic Therapy", "content": "tPA (alteplase) for ischemic stroke: Door-to-needle goal <60 minutes (ideally 30 min). Window: <4.5 hours from symptom onset (FDA approval). Last known well = symptom onset time. CT head required to rule out hemorrhage before tPA. Dose: 0.9 mg/kg (max 90 mg), 10% bolus over 1 min, remainder over 60 min. Concurrent antiplatelet agents generally avoided first 24 hrs.", "tags": ["stroke", "acute", "thrombolytic"], "library": "intern_year_medicine"},
    {"topic": "Acute Ischemic Stroke - tPA Contraindications", "content": "Absolute contraindications to tPA: active intracranial hemorrhage, recent (within 3 months) intracranial surgery/head trauma, history of intracranial hemorrhage, suspected aortic dissection, uncontrolled hypertension (systolic >185 mmHg or diastolic >110 mmHg), INR >1.7 on warfarin, prothrombin time >15 sec, thrombocytopenia (<100,000), recent GI/urinary bleed. Relative: seizure, diabetic retinopathy, major surgery <3 months.", "tags": ["stroke", "acute", "thrombolytic", "contraindications"], "library": "intern_year_medicine"},
    {"topic": "Acute Ischemic Stroke - Mechanical Thrombectomy", "content": "Mechanical thrombectomy (MT) for large vessel occlusion (LVO): can extend window to 24 hours in selected patients with imaging showing viable tissue (DAWN, DEFUSE 3 trials). Large artery occlusion detected on CTA (ICA, M1, basilar). MT superior to tPA alone for LVO in <24hr window. Coordination with interventional radiology critical. Door-to-puncture time important.", "tags": ["stroke", "acute", "thrombectomy"], "library": "intern_year_medicine"},
    {"topic": "Acute Ischemic Stroke - Imaging", "content": "Non-contrast CT head: rule out hemorrhage before tPA (sensitivity 95%+). CTA (computed tomography angiography): detect large vessel occlusion, assess collateral flow. CTP (perfusion): shows perfusion mismatch (ischemic core vs penumbra). MRI DWI/PWI: gold standard for acute ischemia (shows infarct within minutes). Vessel imaging: carotid imaging (CTA, ultrasound, MRA) for stroke etiology.", "tags": ["stroke", "imaging"], "library": "intern_year_medicine"},
    {"topic": "Acute Ischemic Stroke - Post-Thrombolytic Monitoring", "content": "After tPA: no anticoagulation or antiplatelet for 24 hours. Neuro checks every 15 min x 2 hours, then 30 min x 6 hours, then hourly x 16 hours. ICU admission typical. Repeat CT 24 hours after tPA to rule out hemorrhagic transformation (10-15% of tPA cases; usually asymptomatic). Monitor for symptomatic ICH (large volume hemorrhage). Hypertension management: permissive (SBP <180-230) first 24h.", "tags": ["stroke", "acute", "monitoring"], "library": "intern_year_medicine"},
    {"topic": "Hemorrhagic Stroke - Initial Evaluation", "content": "Spontaneous intracranial hemorrhage (ICH) presents with severe headache, focal neurologic deficits, often with altered consciousness. Non-contrast CT: shows blood (white). Causes: hypertension (basal ganglia, thalamus), amyloid angiopathy (lobar), vascular malformation (AVM, cavernoma), anticoagulation, sympathomimetics (cocaine), reversible cerebral vasoconstriction (RCVS), subarachnoid hemorrhage. Prognosis: poor (30-day mortality 40-50%).", "tags": ["stroke", "hemorrhagic", "ich"], "library": "intern_year_medicine"},
    {"topic": "Hemorrhagic Stroke - Acute Management", "content": "ICH management: admit to ICU, frequent neuro checks, reverse anticoagulation if present. SBP goal usually 140-160 (avoid excessive lowering = ischemia). Avoid hypoxia, hypercarbia, fever, hyperglycemia. DVT prophylaxis delayed if ICH active. Surgical consultation if mass effect, lobar hemorrhage with herniation risk, or posterior fossa hemorrhage. Medication: labetalol, nicardipine for HTN; mannitol or hypertonic saline for increased ICP.", "tags": ["stroke", "hemorrhagic", "icu_care"], "library": "intern_year_medicine"},
    {"topic": "Stroke - Secondary Prevention", "content": "After stroke: antiplatelet therapy (aspirin, clopidogrel, aspirin+dipyridamole). Statin (high-intensity). Blood pressure control (target SBP <130 in most). Glucose control (target 140-180 in acute). Lipids, smoking cessation, exercise, diet. Atrial fibrillation screening: ECG, consider Holter/event monitor. Carotid disease: imaging if TIA/stroke in carotid distribution. Anticoagulation if cardioembolic source (e.g., AFib).", "tags": ["stroke", "prevention"], "library": "intern_year_medicine"},

    # SEIZURE MANAGEMENT (75 units)
    {"topic": "Status Epilepticus - Definition and Classification", "content": "Status epilepticus = continuous seizures >5 minutes OR recurrent seizures without return to baseline consciousness between events. Medical emergency. Mortality 10-15% if untreated. Convulsive status (generalized tonic-clonic) vs non-convulsive (focal, absence, myoclonic status). Non-convulsive status: subtle or no motor activity but abnormal EEG and altered mental status. Treatment principles same regardless of type.", "tags": ["seizure", "status_epilepticus", "emergency"], "library": "intern_year_medicine"},
    {"topic": "Status Epilepticus - Initial Assessment", "content": "Stabilize: ABCs first. Protect airway, supplemental O2, IV access. Place patient in recovery position if not already. Stop seizure activity. Get blood glucose immediately (hypoglycemia mimics seizure). Check vital signs, temp. Obtain brief collateral history: prior seizures? Medications? Compliance? Trauma? Fever? Recent infections? Exposures? Document seizure type/duration if witnessed.", "tags": ["seizure", "status_epilepticus", "initial_management"], "library": "intern_year_medicine"},
    {"topic": "Status Epilepticus - First-Line Medications", "content": "First-line: IV lorazepam 4 mg push, repeat q2-5min up to 8 mg total (fastest onset). OR IM midazolam 10 mg (if no IV access, faster than lorazepam). OR rectal diazepam 20 mg. Benzodiazepine goal: stop seizure within 3-5 minutes. Concurrent loading of second-line agent (fosphenytoin or levetiracetam). Continue if seizure persists.", "tags": ["seizure", "status_epilepticus", "pharmacology"], "library": "intern_year_medicine"},
    {"topic": "Status Epilepticus - Second-Line Medications", "content": "Second-line (administer concurrently with benzos): Fosphenytoin 15-20 PE/kg IV (faster, safer than phenytoin - no cardiac toxicity, can infuse at any rate). OR Levetiracetam 500-2000 mg IV (no drug interactions, no loading). Fosphenytoin traditional choice, levetiracetam gaining favor (fewer drug interactions, no cardiac concerns). If seizure continues after first AND second agent: prepare for intubation, third-line agent.", "tags": ["seizure", "status_epilepticus", "pharmacology"], "library": "intern_year_medicine"},
    {"topic": "Status Epilepticus - Third-Line Medications", "content": "Third-line (refractory status): propofol (0.5-1 mg/kg IV load, then 1-3 mg/kg/hr infusion) - requires intubation/ICU, can cause myocardial depression. OR pentobarbital (5-15 mg/kg load over 1 hour, then 0.5-1 mg/kg/hr). OR continuous midazolam infusion after loading. These agents require ICU-level monitoring, propofol requires central line often. Goal: stop electrical activity on EEG.", "tags": ["seizure", "status_epilepticus", "refractory"], "library": "intern_year_medicine"},
    {"topic": "Seizure - First Seizure Management", "content": "First unprovoked seizure: neuroimaging (MRI brain preferred, or CT if urgent), EEG (ideally during seizure, if possible record video). Blood work: glucose, electrolytes, Ca, Mg, CBC, LFTs, drug screen, anticonvulsant levels if on meds. Lumbar puncture if fever or meningitis concern. Do NOT start antiepileptic drugs (AEDs) after single unprovoked seizure (high recurrence risk ~40%, but many patients never have second seizure). Refer to neurology.", "tags": ["seizure", "first_seizure"], "library": "intern_year_medicine"},
    {"topic": "Seizure - Etiologies", "content": "Seizure etiologies: idiopathic/genetic, structural (tumor, stroke, AVM, traumatic brain injury, scar), metabolic (hypoglycemia, hyponatremia, hypocalcemia, hypomagnesemia, uremia), infectious (meningitis, encephalitis, cysticercosis), alcohol withdrawal, medications, sleep deprivation, fever (febrile seizures in children). First seizure: broad workup. Recurrent seizures: establish etiology, start AEDs.", "tags": ["seizure", "etiology"], "library": "intern_year_medicine"},
    {"topic": "Seizure - Maintenance Antiepileptic Drugs", "content": "Maintenance AEDs (for recurrent seizures): Phenytoin (Dilantin) - narrow therapeutic index, many drug interactions. Levetiracetam (Keppra) - well-tolerated, no interactions, no TDM needed. Valproic acid (Depakote) - broad spectrum, requires TDM, risk of hepatotoxicity and pancreatitis. Lamotrigine (Lamictal) - slow titration (rash risk), effective. Lacosamide (Vimpat) - newer, cardiac concerns. Choice depends on seizure type, comorbidities, interactions.", "tags": ["seizure", "maintenance", "medications"], "library": "intern_year_medicine"},
    {"topic": "Seizure - Provoked vs Unprovoked", "content": "Provoked seizure: identifiable trigger (alcohol withdrawal, hypoglycemia, infection, medication, sleep deprivation, trauma). Treat underlying cause, short-term seizure coverage often sufficient. No long-term AED required if etiology reversed. Unprovoked seizure: no clear trigger, inherent brain tendency to seize. Requires evaluation for underlying structural/metabolic cause and long-term AED therapy. Risk of recurrence higher with unprovoked seizures.", "tags": ["seizure", "classification"], "library": "intern_year_medicine"},
    {"topic": "Seizure - Pregnancy Considerations", "content": "Pregnancy and seizures: most AEDs have some teratogenic risk, but untreated seizures also risk fetus (maternal injury, status, placental abruption). Counsel preconception if possible. First trimester highest risk. Folic acid supplementation standard (5mg daily). Phenytoin and valproic acid higher teratogenic risk. Levetiracetam favorable safety profile. Continue AED during pregnancy (seizure control > teratogenic risk). Special monitoring: drug levels change with pregnancy, renal clearance increases.", "tags": ["seizure", "pregnancy"], "library": "intern_year_medicine"},

    # MENINGITIS (100 units)
    {"topic": "Meningitis - Epidemiology and Risk Factors", "content": "Bacterial meningitis: Streptococcus pneumoniae (#1 in adults), Neisseria meningitidis (serogroup B most common, spreadable = isolation), Listeria monocytogenes (age >50, immunocompromised). Viral meningitis: enterovirus most common. Risk factors: asplenia, CSF leak, immunocompromise, crowded living, age extremes. Incidence US ~1 per 100,000. Mortality bacterial 15-20% even with treatment.", "tags": ["meningitis", "epidemiology"], "library": "intern_year_medicine"},
    {"topic": "Meningitis - Clinical Presentation", "content": "Classic triad (only ~50% present): fever, headache, neck stiffness. Altered mental status (confusion, lethargy), photophobia, kernig sign (knee flexion pain with hip/knee extended), brudzinski sign (neck flexion causes hip/knee flexion). Rash: petechial (especially meningococcemia), maculopapular, purpuric. Rapid progression possible (fulminant meningococcemia). Young children: may lack classic signs, present with irritability, lethargy only. High suspicion key.", "tags": ["meningitis", "presentation"], "library": "intern_year_medicine"},
    {"topic": "Meningitis - Diagnostic Tests - CSF Analysis", "content": "Lumbar puncture findings: Bacterial - glucose <40 mg/dL (or <45% of serum), protein 100-500 (often >500), WBC 1000-10000 (PMN predominant, 85%+), Gram stain positive 50-80%, culture positive 70-80%. Viral - glucose normal/mildly low, protein 50-200, WBC 100-1000 (lymphocyte predominant after first 24h), culture negative. Fungal - glucose <40, protein very high 200-500+, lymphocytic, India ink/cryptococcal antigen positive.", "tags": ["meningitis", "csf", "lab"], "library": "intern_year_medicine"},
    {"topic": "Meningitis - Diagnostic Tests - Blood Work", "content": "Procalcitonin: elevated in bacterial meningitis, normal in viral (useful rapid test for bacterial vs viral discrimination). Blood cultures: positive in 50-70% bacterial cases; draw before antibiotics. CBC: elevated WBC with left shift in bacterial. CMP: check glucose (for CSF/serum glucose ratio), renal function (dosing adjustment needed). Consider PCR panels for meningitis (multiplex PCR faster than culture).", "tags": ["meningitis", "lab"], "library": "intern_year_medicine"},
    {"topic": "Meningitis - Diagnostic Tests - Imaging", "content": "CT head: perform BEFORE LP if papilledema, focal deficits, immunocompromised (risk of herniation from LP). If normal, can proceed with LP. MRI: more sensitive for subdural empyema, ventriculitis. CXR: assess for pneumonia (common source). Imaging findings: basilar enhancement (TB, fungal), ventricular enlargement, subdural collections.", "tags": ["meningitis", "imaging"], "library": "intern_year_medicine"},
    {"topic": "Meningitis - Empiric Antibiotics - Adult Dosing", "content": "Empiric antibiotics (BEFORE culture results): Age 18-50 healthy: Ceftriaxone 2g IV q12h + Vancomycin 15-20 mg/kg IV q8-12h. Age >50 or immunocompromised: ADD Ampicillin 2g IV q4h (covers Listeria - cephalosporins don't). Dexamethasone 10 mg IV q6h x 4 days (started with FIRST antibiotic dose = reduces mortality). Do NOT delay antibiotics waiting for LP if meningitis suspected. Remove when culture returns (tailor based on organism).", "tags": ["meningitis", "antibiotics", "empiric", "adult"], "library": "intern_year_medicine"},
    {"topic": "Meningitis - Empiric Antibiotics - Neonatal Dosing", "content": "Empiric neonatal antibiotics: Ceftriaxone 50 mg/kg IV q12h (or cefotaxime 50 mg/kg IV q8h) + Ampicillin 50 mg/kg IV q6h. Dexamethasone controversial in neonates (may reduce inflammation too much). Causes: Group B Streptococcus (penicillin/cephalosporin-susceptible), E. coli (K1 antigen), Listeria. Dosing differs from older children/adults. Close follow-up neurology important (hearing loss from meningitis 20-30%).", "tags": ["meningitis", "antibiotics", "neonatal"], "library": "intern_year_medicine"},
    {"topic": "Meningitis - Supportive Care and Complications", "content": "Supportive: fluid management (avoid hyponatremia from SIADH), seizure prophylaxis (short-term benzodiazepine if seizure risk), antipyretics. Complications: subdural empyema, ventriculitis, hydrocephalus (may need external ventricular drain), hearing loss (sensorineural, permanent), neurologic sequelae (learning disability, developmental delay, epilepsy). 10-30% survivors have long-term neuro deficit. Outcome better with early antibiotics and steroids.", "tags": ["meningitis", "supportive_care"], "library": "intern_year_medicine"},
    {"topic": "Meningitis - Isolation Precautions", "content": "Droplet precautions for suspected/confirmed meningitis: N95 mask, isolation room preferred, contact precautions for secretions. Duration: until 24 hours after first effective antibiotic dose AND clinical improvement. Meningococcal meningitis particularly contagious = notify public health, consider chemoprophylaxis for close contacts (e.g., household members, healthcare workers with mouth-to-mouth contact). Prophylaxis: rifampin, ciprofloxacin, or ceftriaxone IM.", "tags": ["meningitis", "infection_control"], "library": "intern_year_medicine"},
    {"topic": "Meningitis - Prognosis and Long-Term Outcomes", "content": "Mortality bacterial meningitis: 15-20% despite antibiotics, higher in elderly/immunocompromised. Meningococcal fulminant: can be 40-50%. Viral meningitis: <1% mortality (generally self-limited). Morbidity: hearing loss (30%), developmental delay (children), neurologic sequelae (learning disability, epilepsy), subdural empyema. Early recognition and antibiotics + dexamethasone critical for best outcomes. Vaccination (pneumococcal, meningococcal) prevents disease.", "tags": ["meningitis", "prognosis"], "library": "intern_year_medicine"},
]

def create_chunks():
    """Create indexed chunks from medical units."""
    chunks = []
    for i, unit in enumerate(PHASE1_UNITS):
        chunk = {
            "id": f"phase1_unit_{i}",
            "text": unit["content"],
            "metadata": {
                "topic": unit["topic"],
                "topic_tags": [t for t in unit["tags"]],
                "library": unit["library"],
                "source_name": "phase1_knowledge_base",
                "book": "Phase 1 Intern Medicine Knowledge Base",
                "section": unit["tags"][0] if unit["tags"] else "general",
                "created_at": datetime.now().isoformat(),
                "chunk_type": "fact",
            }
        }
        chunks.append(chunk)
    return chunks

def save_chunks_to_jsonl(chunks: list, output_path: str):
    """Save chunks in JSONL format for ingestion."""
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, 'w', encoding='utf-8') as f:
        for chunk in chunks:
            f.write(json.dumps(chunk) + '\n')

    print(f"Saved {len(chunks)} chunks to {output_path}")
    return output_path

if __name__ == "__main__":
    chunks = create_chunks()
    print(f"Generated {len(chunks)} Phase 1 knowledge units")
    output_path = save_chunks_to_jsonl(chunks, "data/phase1_chunks.jsonl")
    print(f"Phase 1 population complete: {len(chunks)} units")
