#!/usr/bin/env python3
"""Phase 2 COPD/Asthma knowledge base: pathophysiology, exacerbations, management."""
import json
from datetime import datetime
from pathlib import Path

PHASE2_COPD_ASTHMA_UNITS = [
    {"topic": "COPD Definition and Pathophysiology", "subtopic": "copd_basics", "content": "COPD: progressive airflow obstruction due to emphysema (alveolar destruction) and chronic bronchitis (airway inflammation). Diagnosis: FEV1/FVC <0.70 on spirometry post-bronchodilator. Risk: smoking (85%), alpha-1 antitrypsin deficiency, air pollution. GOLD staging (A-D): based on FEV1 % predicted and exacerbation frequency. Pathophysiology: oxidative stress, inflammation, parenchymal destruction, airway collapse on expiration (air trapping). Hypoxemia, hypercapnia (type 2 respiratory failure) in advanced disease.", "tags": ["copd", "basics"], "library": "intern_year_medicine"},
    {"topic": "Asthma Phenotypes and Classification", "subtopic": "asthma_basics", "content": "Asthma: reversible airflow obstruction, bronchial hyperresponsiveness. Phenotypes: allergic (IgE-mediated, atopy history), non-allergic (occupational, irritants), exercise-induced, aspirin-exacerbated (NSAID sensitivity). Severity: intermittent, mild persistent, moderate persistent, severe persistent. Diagnosis: spirometry (FEV1 improvement >12% post-bronchodilator), PEF variability, positive bronchial challenge. Triggers: allergens, cold air, exercise, respiratory infections, stress, GERD.", "tags": ["asthma", "basics"], "library": "intern_year_medicine"},
    {"topic": "Acute COPD Exacerbation - Triggers and Presentation", "subtopic": "copd_exacerbation", "content": "COPD exacerbation: worsening dyspnea, increased sputum, color change (suggests infection), ±chest discomfort. Triggers: infection (50-75%, bacterial/viral), pollutants, non-adherence, cardiac causes (pulmonary edema mimics). Presenting: tachypnea, tachycardia, accessory muscle use, wheezing/decreased air movement, cyanosis in severe cases. Hypoxemia, hypercapnia (respiratory acidosis), elevated lactate if severe. Chest X-ray: rule out pneumonia, pneumothorax, cardiac disease.", "tags": ["copd", "exacerbation"], "library": "intern_year_medicine"},
    {"topic": "Acute Asthma Exacerbation - Severity Assessment", "subtopic": "asthma_exacerbation", "content": "Asthma exacerbation severity: mild (PEF >70% predicted, accessory muscle use absent/mild, speech normal), moderate (PEF 40-70%, accessory muscle use present, speech interrupted), severe (PEF <40%, severe accessory muscle use, speaks in words/phrases). Danger signs: no wheezing (severe airway obstruction, silent chest), altered mental status (CO2 narcosis), peak flow <25% predicted. SpO2 <90% concerning. Triggers: allergens, infections, exercise, stress, medication non-adherence, cold/dry air. Differential: anaphylaxis, PE, pneumothorax, vocal cord dysfunction.", "tags": ["asthma", "exacerbation", "severity"], "library": "intern_year_medicine"},
    {"topic": "Bronchodilators - Beta-2 Agonists and Anticholinergics", "subtopic": "copd_asthma_treatment", "content": "Beta-2 agonists (albuterol, levalbuterol): rapid bronchodilation via smooth muscle relaxation. Short-acting (SABA, albuterol) onset 5 min, duration 4-6 hours, used as rescue. Long-acting (LABA, salmeterol, formoterol) 12-24 hour duration, maintenance therapy. Anticholinergics (ipratropium, tiotropium): block vagal cholinergic stimulation. LAMA (long-acting muscarinic agonist) maintenance, SAMA (short-acting) rescue. Combination therapy (SABA + SAMA) often used in exacerbations. Side effects: tachycardia, tremor (beta-2), dry mouth (anticholinergic). LABA monotherapy should not be used in asthma (mortality risk).", "tags": ["copd", "asthma", "bronchodilators"], "library": "intern_year_medicine"},
    {"topic": "Systemic Corticosteroids - Dosing and Tapering", "subtopic": "copd_asthma_treatment", "content": "Corticosteroids (prednisone, methylprednisolone): anti-inflammatory, reduce airway edema. Acute exacerbation: prednisone 40-60 mg daily x 5-7 days (no taper needed if <2 weeks), or methylprednisolone 125 mg IV q6h x 3 days. High-dose short-duration preferred over long course/taper. Benefits: reduced hospitalization, improved FEV1, reduced exacerbation relapse. Side effects: hyperglycemia, mood changes, GI upset. Long-term: increased infection, osteoporosis, adrenal suppression risk. Inhaled ICS (fluticasone, budesonide) maintenance therapy without systemic side effects.", "tags": ["copd", "asthma", "corticosteroids"], "library": "intern_year_medicine"},
    {"topic": "Magnesium Sulfate in Severe Asthma", "subtopic": "asthma_treatment", "content": "IV magnesium sulfate: smooth muscle relaxant, used in severe asthma exacerbation (PEF <40% predicted, poor response to initial bronchodilators). Dosing: 2g IV over 20 minutes, may repeat. Mechanism: calcium antagonist, enhances beta-2 response. Efficacy debated; some trials show benefit, others don't. Consider in life-threatening asthma (with albuterol, anticholinergics, steroids). Side effects: flushing, hypotension, hypermagnesemia (check Mg level). Contraindications: renal insufficiency, hypocalcemia.", "tags": ["asthma", "treatment", "magnesium"], "library": "intern_year_medicine"},
    {"topic": "Leukotriene Inhibitors and IgE Monoclonal Antibodies", "subtopic": "asthma_treatment", "content": "Leukotriene receptor antagonists (montelukast, zafirlukast): block cysteinyl-leukotriene effects (bronchospasm, mucus, inflammation). Used for mild persistent asthma, exercise-induced, allergic rhinitis. Efficacy modest vs ICS/LABA. Neuropsychiatric warning (rare). Omalizumab: anti-IgE monoclonal antibody, blocks mast cell/basophil IgE-mediated activation. Used for moderate-severe allergic asthma (IgE 30-700 IU/mL). SC injection monthly. Expensive, requires monitoring (anaphylaxis risk). Both steroid-sparing agents but no mortality benefit.", "tags": ["asthma", "treatment", "biologics"], "library": "intern_year_medicine"},
    {"topic": "Non-invasive Ventilation (BiPAP) - COPD Exacerbation", "subtopic": "copd_treatment", "content": "BiPAP (bilevel positive airway pressure): non-invasive positive pressure ventilation, reduces need for intubation in COPD exacerbation with hypercapnic respiratory failure (pH <7.35, pCO2 >45). Settings: IPAP 8-12 cmH2O (inspiratory), EPAP 3-5 cmH2O (expiratory). Improves CO2 clearance via increased minute ventilation. Success 50-80% if started early (tiring patient = intubation indication). Contraindications: altered mental status (aspiration risk), respiratory muscle fatigue, active GI bleed, facial/airway trauma. Comfort critical; ramp settings, frequent patient reassurance.", "tags": ["copd", "treatment", "niv"], "library": "intern_year_medicine"},
    {"topic": "Theophylline - Limited Modern Use and Toxicity", "subtopic": "copd_treatment", "content": "Theophylline: methylxanthine bronchodilator, weak beta-2 agonist, phosphodiesterase inhibitor, diuretic. Narrow therapeutic window (10-20 mcg/mL), susceptible to drug interactions (CYP1A2, CYP3A4). Side effects: nausea, vomiting, arrhythmias, seizures (toxicity). Toxicity risk with: hepatic disease, heart failure, concurrent drugs, smoking cessation (levels rise). Limited role; avoided in acute exacerbation (unpredictable absorption/toxicity). Minimal efficacy vs modern bronchodilators. Largely replaced by long-acting bronchodilators. May have role in nocturnal COPD symptoms (long-acting form).", "tags": ["copd", "treatment", "theophylline"], "library": "intern_year_medicine"},
    {"topic": "Intubation Indications in COPD/Asthma Exacerbation", "subtopic": "copd_asthma_treatment", "content": "Indications for intubation in COPD/asthma: altered mental status (can't protect airway), severe respiratory distress despite aggressive therapy, apnea/respiratory arrest, fatigue (can't sustain ventilation), worsening blood gas (rising pCO2, falling pH), hypoxemia refractory to supplemental O2, hemodynamic instability. Avoid delaying intubation (causes cardiac arrest); earlier intervention better in severe/unstable patients. Permissive hypercapnia acceptable post-intubation (avoid barotrauma). Sedation/paralysis needed. Weaning: assess readiness daily (decreased sedation, improving gas exchange, tolerating lower ventilator support).", "tags": ["copd", "asthma", "intubation"], "library": "intern_year_medicine"},
    {"topic": "Oxygen Therapy - Targets and Complications", "subtopic": "copd_asthma_treatment", "content": "Oxygen therapy: goal SpO2 88-92% in COPD (avoid high SpO2 = CO2 retention via Haldane effect), 94-98% in asthma. Long-term home O2: improves survival if used ≥15 hours/day (NOTT, MRC trials), especially resting hypoxemia (PaO2 <55 mmHg or SaO2 <88%). Supplemental O2 in exacerbations: titrate to SpO2 target, monitor ABG for hypercapnia. Complications: CO2 retention (reduced hypoxic ventilatory drive in COPD), absorption atelectasis, dry airway secretions (humidify). Mask/nasal cannula tolerance important for adherence.", "tags": ["copd", "asthma", "oxygen"], "library": "intern_year_medicine"},
    {"topic": "Discharge Criteria and Pulmonary Rehabilitation", "subtopic": "copd_asthma_aftercare", "content": "Discharge criteria from exacerbation: improved lung function, able to eat/drink, stable vitals, on target O2, medication instructions understood, reliable follow-up arranged. Pulmonary rehabilitation (exercise training, education, psychosocial support) post-exacerbation improves functional capacity, reduces readmissions 30-40%. Components: aerobic exercise (walking, cycling), resistance training, breathing techniques, education (inhaler technique, smoking cessation, medication adherence), psychological support. Benefits last 6-12 months; ongoing maintenance helpful. Smoking cessation critical; pharmacotherapy (varenicline, bupropion) improves cessation rates.", "tags": ["copd", "asthma", "rehabilitation"], "library": "intern_year_medicine"},
    {"topic": "Vaccination in COPD - Pneumococcal and Influenza", "subtopic": "copd_prevention", "content": "Vaccinations in COPD: pneumococcal (PCV13 then PPSV23 after 1 year, then PPSV23 every 5 years), influenza annual. Reduces hospitalization/mortality 50%+. Influenza vaccine LAIV contraindicated in COPD (COPD = chronic lung disease). Tdap booster (whooping cough = severe in COPD). RSV vaccine now available (AREXVY, ABRYSVO) for adults ≥60; reduces RSV-associated LRTD. COVID-19 vaccination critical (severe disease risk in COPD). Discuss benefits/risks per patient risk profile.", "tags": ["copd", "prevention", "vaccination"], "library": "intern_year_medicine"},
    {"topic": "Differential Diagnosis - Not All Dyspnea is COPD/Asthma", "subtopic": "copd_asthma_ddx", "content": "Common mimics of COPD/asthma exacerbation: PE (tachycardia, hypoxemia, unilateral leg swelling, D-dimer elevation), pneumonia (fever, infiltrate, productive cough), pneumothorax (acute onset, hyperresonance, absent breath sounds), acute heart failure (orthopnea, JVP elevation, S3 gallop, crackles), acute coronary syndrome (chest pain, ECG changes, troponin elevation), anaphylaxis (urticaria, angioedema, hypotension, stridor). History, examination, CXR, ECG, troponin help differentiate. COPD/asthma diagnosis not sufficient without excluding dangerous mimics.", "tags": ["copd", "asthma", "ddx"], "library": "intern_year_medicine"},
]

def main():
    output_dir = Path("C:/Users/Dean/anesthesia_attending/data")
    output_file = output_dir / "phase2_copd_asthma_chunks.json"
    output_dir.mkdir(parents=True, exist_ok=True)

    for idx, unit in enumerate(PHASE2_COPD_ASTHMA_UNITS):
        unit["id"] = f"phase2_copd_asthma_unit_{idx}"
        if "library" not in unit:
            unit["library"] = "intern_year_medicine"
        unit["created_at"] = datetime.now().isoformat()

    with open(output_file, "w") as f:
        for unit in PHASE2_COPD_ASTHMA_UNITS:
            f.write(json.dumps(unit) + "\n")

    print(f"Generated {len(PHASE2_COPD_ASTHMA_UNITS)} COPD/asthma knowledge units")
    return len(PHASE2_COPD_ASTHMA_UNITS)

if __name__ == "__main__":
    main()
