#!/usr/bin/env python3
"""
Populate Phase 2 pneumonia knowledge base with medical content chunks.
Covers CAP, HAP, VAP, antibiotic stewardship, severity scoring, complications.
"""

import json
import os
from datetime import datetime
from pathlib import Path

PHASE2_PNEUMONIA_UNITS = [
    # CAP DEFINITION & EPIDEMIOLOGY (8 units)
    {"topic": "Community-Acquired Pneumonia (CAP) - Definition", "subtopic": "pneumonia_basics", "content": "CAP = pneumonia in non-hospitalized patient (or <48h after admission). Incidence 5-7 per 1000 adults/year. Mortality 1% outpatient, 5-7% hospitalized, 30-40% ICU. Most common: bacterial (S. pneumoniae, H. influenzae, M. catarrhalis) vs viral (RSV, influenza, rhinovirus) vs atypical (Legionella, Mycoplasma, Chlamydia).", "tags": ["pneumonia", "cap", "epidemiology", "high_yield"], "library": "intern_year_medicine"},
    {"topic": "CAP - Risk Factors and Patient Assessment", "subtopic": "pneumonia_basics", "content": "CAP risk factors: age >65, smoking, alcohol, immunosuppression (HIV, steroids, biologics), diabetes, renal/liver disease, COPD, cardiovascular disease, recent viral illness. Initial assessment: vital signs (fever? tachycardia? tachypnea? hypoxia?), toxic appearance, comorbidities, functional status for outpatient vs inpatient decision.", "tags": ["pneumonia", "cap", "risk_factors"], "library": "intern_year_medicine"},
    {"topic": "CAP - Presentation and Clinical Features", "subtopic": "pneumonia_basics", "content": "CAP classic: cough (productive or dry), fever, dyspnea. Atypical presentations: elderly may lack fever, altered mental status instead; immunocompromised may be afebrile. Associated: pleuritic chest pain, rigors, malaise. Exam: fever, tachycardia, consolidation (tactile fremitus, dullness to percussion, egophony), crackles. Severity varies from mild outpatient to fulminant sepsis.", "tags": ["pneumonia", "cap", "presentation"], "library": "intern_year_medicine"},
    {"topic": "CAP - Chest X-ray Findings", "subtopic": "pneumonia_imaging", "content": "CXR: lobar consolidation (focal, dense), bronchopneumonia (patchy infiltrates), interstitial pattern (viral or atypical). Apical-posterior: TB, atypical (Legionella, Mycoplasma). Right lower lobe: most common. Pleural effusion suggests bacterial. Cavitation suggests anaerobes or TB. CXR lags symptoms by days; not required for diagnosis if clinical + sputum Gram stain/culture.", "tags": ["pneumonia", "cap", "imaging"], "library": "intern_year_medicine"},
    {"topic": "CAP - Laboratory Investigations", "subtopic": "pneumonia_diagnosis", "content": "CBC: leukocytosis (>12k) typical, but absent in 10-15%; left shift common. CMP: renal function (creatinine), electrolytes (hyponatremia in severe/Legionella). BUN/Cr ratio elevated = dehydration. Blood cultures x2 before antibiotics if hospitalized (only 10% positive). Sputum Gram stain/culture if productive: identify organism, guide therapy. Lactate if severe/septic.", "tags": ["pneumonia", "cap", "labs"], "library": "intern_year_medicine"},
    {"topic": "CAP - Viral vs Bacterial Distinction", "subtopic": "pneumonia_diagnosis", "content": "Viral pneumonia: bilateral diffuse infiltrates, interstitial pattern, elevated LDH. Bacterial: focal consolidation, pleural effusion more common. Atypical (Legionella, Mycoplasma): can mimic viral. Cold agglutinin positivity (>1:64) suggests Mycoplasma. Nasal swabs/rapid tests for influenza, RSV, COVID helpful. RT-PCR for specific pathogens. Treatment differs: viral = supportive + antivirals if indicated; bacterial = antibiotics.", "tags": ["pneumonia", "cap", "diagnosis"], "library": "intern_year_medicine"},
    {"topic": "CAP - Sputum Gram Stain Interpretation", "subtopic": "pneumonia_diagnosis", "content": "Gram stain guides initial therapy: gram-positive cocci in pairs = Streptococcus pneumoniae (diplococcus). Gram-negative rods = H. influenzae, enteric gram-negatives. Gram-positive rods = anaerobes (if foul sputum/aspiration). Gram-negative coccobacillus = Legionella (but often Gram stain negative, requires special culture). Quality sputum: >25 PMNs, <10 epithelial cells per low power field. Poor quality: repeat or culture without interpretation.", "tags": ["pneumonia", "cap", "microbiology"], "library": "intern_year_medicine"},
    {"topic": "CAP - Atypical Pathogens Overview", "subtopic": "pneumonia_atypical", "content": "Atypical pathogens: Legionella pneumophila, Mycoplasma pneumoniae, Chlamydia pneumoniae, Chlamydia psittaci (psittacosis = bird exposure), Coxiella burnetii (Q fever = farm exposure). Cannot be cultured routinely; require PCR, serology, or special culture. Presentation: constitutional symptoms, GI symptoms, diarrhea more common than typical CAP. Treatment: macrolides (azithromycin) or fluoroquinolones (levofloxacin, moxifloxacin) cover atypicals.", "tags": ["pneumonia", "atypical", "high_yield"], "library": "intern_year_medicine"},

    # CURB-65 SEVERITY SCORING (5 dedicated units)
    {"topic": "CURB-65 Scoring - Component Breakdown", "subtopic": "pneumonia_severity", "content": "CURB-65: Confusion (acute, new mental status change or disorientation), Urea >7 mmol/L (BUN >20 mg/dL), Respiratory rate ≥30/min, Blood pressure (SBP <90 or DBP ≤60), age ≥65 years. Each = 1 point. Total 0-5 points. Predicts 30-day mortality. Risk stratification guides admission, ICU, and monitoring intensity. Simple, bedside tool requiring minimal labs/imaging.", "tags": ["pneumonia", "curb65", "severity_scoring"], "library": "intern_year_medicine"},
    {"topic": "CURB-65 - Risk Stratification by Score", "subtopic": "pneumonia_severity", "content": "CURB-65 score 0-1: outpatient management, low mortality (0-2%). Score 2: consider admission/closer monitoring, mortality 2-3%. Score 3: admission recommended, mortality 13-18%. Score 4-5: ICU/high-acuity care, mortality 40-50%. Negative predictive value >95% for low scores (0-1): safe to discharge if outpatient appropriate. Use with clinical judgment: comorbidities, ability to take oral medications, follow-up access.", "tags": ["pneumonia", "curb65", "admission_criteria", "high_yield"], "library": "intern_year_medicine"},
    {"topic": "CURB-65 - Clinical Application", "subtopic": "pneumonia_severity", "content": "CURB-65 works in ED/hospital settings to risk-stratify. Example: 75-year-old with RR=28, SBP=110, BUN=18, no confusion = 2 points (age + RR) = consider admission. Use alongside PSI (Pneumonia Severity Index) if needed for low-risk confirmation. Limited in immunocompromised, atypical presentations. Not a substitute for clinical judgment.", "tags": ["pneumonia", "curb65", "application"], "library": "intern_year_medicine"},
    {"topic": "CURB-65 - Interpreting 'Confusion' Component", "subtopic": "pneumonia_severity", "content": "Confusion = new acute change in mental status, NOT baseline dementia. Assessed via AMTS (Abbreviated Mental Test Score): age, time, place, person x2. Score 0 = alert/oriented; score ≥1 = confusion (1 point in CURB-65). In elderly baseline confusion, use informant history for acute change. Delirium superimposed on dementia still counts if acute worsening.", "tags": ["pneumonia", "curb65", "confusion"], "library": "intern_year_medicine"},
    {"topic": "CURB-65 - Limitations and Alternatives", "subtopic": "pneumonia_severity", "content": "CURB-65 limitations: doesn't incorporate oxygen levels, doesn't assess sepsis/lactate severity, misses some ICU-bound patients. PSI (Pneumonia Severity Index) more complex but slightly more sensitive for ICU risk. qSOFA (quick SOFA) for sepsis/septic shock: altered mental status + SBP ≤100 + RR ≥22. SOFA for ICU patients. Use CURB-65 as screening; clinical judgment trumps score.", "tags": ["pneumonia", "curb65", "limitations"], "library": "intern_year_medicine"},

    # BACTERIAL CAP - TYPICAL ORGANISMS & TREATMENT (15 units)
    {"topic": "CAP - Streptococcus pneumoniae (Pneumococcus)", "subtopic": "pneumonia_organisms", "content": "Most common bacterial CAP pathogen (~40% of cases). Gram-positive diplococcus. Presents with acute onset fever, productive cough, rigors. Lobar consolidation typical. Blood cultures positive in 25-50% if not pre-treated. Complications: sepsis, meningitis (esp. if petechial rash), endocarditis (if prosthetic valve). Antibiotic resistance increasing (penicillin-resistant strains). Vaccination (PCV13, PPSV23) reduces incidence.", "tags": ["pneumonia", "cap", "pneumococcus", "high_yield"], "library": "intern_year_medicine"},
    {"topic": "CAP - Haemophilus influenzae", "subtopic": "pneumonia_organisms", "content": "Gram-negative coccobacillus. Second most common. More common in COPD patients. Presentation similar to pneumococcus. X-ray: often bilateral, bronchopneumonia pattern. Ampicillin resistance common (30-50% in some regions) via beta-lactamase production. Complications: meningitis (type b, now rare with Hib vaccine), epiglottitis. Hib vaccine routine in childhood, but adult protection wanes.", "tags": ["pneumonia", "cap", "h_influenzae"], "library": "intern_year_medicine"},
    {"topic": "CAP - Moraxella catarrhalis", "subtopic": "pneumonia_organisms", "content": "Gram-negative diplococcus. Common in elderly and COPD. Usually lower lobe involvement. Typically mild-moderate disease, community outpatient pneumonia. Produces beta-lactamase; ampicillin/amoxicillin resistance ~80%. Susceptible to fluoroquinolones, macrolides, beta-lactam/beta-lactamase inhibitors. Less likely to cause bacteremia or invasive disease vs pneumococcus.", "tags": ["pneumonia", "cap", "moraxella"], "library": "intern_year_medicine"},
    {"topic": "CAP - Aspiration Pneumonia and Anaerobes", "subtopic": "pneumonia_aspiration", "content": "Aspiration pneumonia: from oral anaerobes after aspiration (risk: altered mental status, dysphagia, seizures, alcohol abuse). Pathogens: Peptostreptococcus, Prevotella, Fusobacterium, Bacteroides (all anaerobes). Presents subacutely (1-2 weeks), often with foul-smelling sputum/breath. Apical-posterior/superior segment infiltrate (gravity-dependent). Cavitation if delayed treatment. Penicillin V (not G) or clindamycin cover anaerobes.", "tags": ["pneumonia", "aspiration", "anaerobes"], "library": "intern_year_medicine"},
    {"topic": "CAP - Gram-Negative Enteric Organisms", "subtopic": "pneumonia_organisms", "content": "Gram-negative enterics (E. coli, Klebsiella, Proteus, Enterobacter) cause CAP in specific settings: healthcare-associated, severe COPD, recent antibiotics, ICU care. Klebsiella: associated with alcoholism, diabetes, chronic illness; can cavitate (aggressive). Pseudomonas aeruginosa: if COPD with FEV <25%, immunocompromised, recent hospitalizations. Require empiric coverage with fluoroquinolone or cephalosporin if risk factors present.", "tags": ["pneumonia", "cap", "gram_negative"], "library": "intern_year_medicine"},
    {"topic": "CAP - Empiric Antibiotic Therapy - Outpatient", "subtopic": "pneumonia_treatment", "content": "Outpatient CAP (CURB-65 0-1, low risk): first-line = amoxicillin 500mg TID x5 days (covers pneumococcus/H. flu) OR azithromycin 500mg day1, 250mg daily x4 days (covers atypicals too). Alternative if beta-lactam allergy: fluoroquinolone (levofloxacin 750mg daily x5, or moxifloxacin 400mg daily x5) covers both typical and atypical. Doxycycline (tetracycline, 100mg BID) also covers atypicals; avoid in pregnancy. Duration: 5-7 days typical.", "tags": ["pneumonia", "cap", "antibiotics", "treatment"], "library": "intern_year_medicine"},
    {"topic": "CAP - Empiric Antibiotic Therapy - Inpatient Non-ICU", "subtopic": "pneumonia_treatment", "content": "Hospitalized CAP (CURB-65 2-3, moderate-severe): beta-lactam (amoxicillin-clavulanate, ceftriaxone, or cefpodoxime) + macrolide (azithromycin) OR fluoroquinolone (levofloxacin, moxifloxacin) monotherapy. Fluoroquinolone monotherapy reasonable if patient cannot take IV. Beta-lactam + macrolide preferred if pneumococcus suspected and fluoroquinolone resistance risk low. Switching from IV to PO once clinically stable (defervescence, improved oxygenation).", "tags": ["pneumonia", "cap", "antibiotics", "treatment"], "library": "intern_year_medicine"},
    {"topic": "CAP - Empiric Antibiotic Therapy - ICU/Severe", "subtopic": "pneumonia_treatment", "content": "Severe CAP in ICU (CURB-65 4-5, respiratory failure, shock): beta-lactam (ceftriaxone 1-2g IV q12h, or piperacillin-tazobactam 4.5g IV q6h) + fluoroquinolone (levofloxacin 750mg IV daily) OR + macrolide (azithromycin 500mg IV daily). Broad coverage for atypicals and resistant organisms. If Pseudomonas risk (severe COPD FEV <25%, recent antibiotics), use antipseudomonal beta-lactam (piperacillin-tazobactam, cefepime) + fluoroquinolone.", "tags": ["pneumonia", "cap", "antibiotics", "severe"], "library": "intern_year_medicine"},
    {"topic": "CAP - Beta-Lactam vs Fluoroquinolone Controversy", "subtopic": "pneumonia_treatment", "content": "Historical debate: fluoroquinolone monotherapy vs beta-lactam + macrolide. Meta-analyses show no mortality difference when used appropriately. Fluoroquinolone advantages: PO/IV formulations, atypical coverage, better lung penetration, no need for combination. Disadvantages: resistance emerging, Clostridium difficile risk, tendon rupture, QT prolongation. Beta-lactam + macrolide: proven, good outcomes, but more pills/side effects. Practice varies; both reasonable if age-appropriate and allergy status considered.", "tags": ["pneumonia", "cap", "antibiotics", "stewardship"], "library": "intern_year_medicine"},
    {"topic": "CAP - Macrolide Choice: Azithromycin vs Others", "subtopic": "pneumonia_treatment", "content": "Azithromycin 500mg day1, then 250mg daily (Z-pack): covers pneumococcus, H. flu, Moraxella, atypicals (Legionella, Mycoplasma, Chlamydia). GI side effects common (nausea, diarrhea). QT prolongation risk if given with other QT drugs. Erythromycin: older, more GI upset, less often used. Clarithromycin: similar coverage to azithromycin but also metabolizes via CYP3A4 (more drug interactions). Macrolides should not be used alone for CAP in elderly/comorbid (higher failure rates); use with beta-lactam.", "tags": ["pneumonia", "cap", "antibiotics", "macrolides"], "library": "intern_year_medicine"},
    {"topic": "CAP - Duration of Antibiotic Therapy", "subtopic": "pneumonia_treatment", "content": "CAP antibiotic duration: typically 5-7 days total (shorter than historical 10-14 days). Shorter duration (3-5 days) safe if clinically stable, defervescent, able to take PO, adequate follow-up. Avoid prolonged course unless complications (empyema, metastatic infection). Switch to PO once tolerating, clinically improving (within 2-3 days typical). Outpatient: 5-7 days oral. Hospitalized: IV x 2-3 days, then PO x remaining days. Total course = OUTPATIENT duration (5 days) + any IV overlap.", "tags": ["pneumonia", "cap", "antibiotics", "duration"], "library": "intern_year_medicine"},
    {"topic": "CAP - De-escalation and Stewardship", "subtopic": "pneumonia_stewardship", "content": "De-escalation: start broad (empiric), then narrow based on culture/susceptibilities. Example: start ceftriaxone + azithromycin, culture identifies pneumococcus susceptible to penicillin, de-escalate to amoxicillin. Reduces antibiotic exposure, resistance, Clostridioides difficile risk. Monotherapy preferred when possible (e.g., fluoroquinolone monotherapy for CAP in compliant outpatient). Avoid prolonged broad-spectrum therapy. Stop when clinically improved (don't treat until negative cultures).", "tags": ["pneumonia", "antibiotics", "stewardship", "high_yield"], "library": "intern_year_medicine"},

    # LEGIONELLA & MYCOPLASMA PNEUMONIA (6 units)
    {"topic": "Legionella pneumophila - Epidemiology and Risk Factors", "subtopic": "pneumonia_atypical", "content": "Legionella: gram-negative rod, found in water (air conditioning, cooling towers, hot tubs). Risk: age >50, smoking, immunocompromise, chronic lung disease. Mortality 1-5% with treatment, 25% without. Outbreaks rare in developed countries (water treatment better). Non-community source (travel, hotel stay) increases suspicion. Incubation: 2-10 days (longer than typical CAP).", "tags": ["pneumonia", "legionella", "epidemiology"], "library": "intern_year_medicine"},
    {"topic": "Legionella - Clinical Features and Diagnosis", "subtopic": "pneumonia_atypical", "content": "Legionella pneumonia: severe, with prominent constitutional symptoms (malaise, myalgias, headache), fever, GI symptoms (diarrhea, nausea), neurologic symptoms (confusion, lethargy). CXR: often bilateral infiltrates, can cavitate in severe cases. Hyponatremia common (SIADH). Labs: elevated transaminases, elevated LDH. Diagnosis: urine antigen test (rapid, not culture), sputum/BAL culture on special media (BMPA, CYE agar), serology (antibodies). Gram stain negative (poorly stains).", "tags": ["pneumonia", "legionella", "diagnosis"], "library": "intern_year_medicine"},
    {"topic": "Legionella - Treatment", "subtopic": "pneumonia_atypical", "content": "Legionella treatment: fluoroquinolone (levofloxacin 750mg IV/PO daily x 7-10 days) or macrolide (azithromycin 500mg IV daily x 3-5 days, then PO x remaining). Fluoroquinolone preferred (better lung penetration, proven outcomes). Beta-lactams ineffective (not PBP-dependent). Duration: usually 7-10 days for hospitalized patients. ICU support if respiratory failure. Antibiotics should not be delayed waiting for definitive diagnosis if Legionella suspected clinically.", "tags": ["pneumonia", "legionella", "treatment"], "library": "intern_year_medicine"},
    {"topic": "Mycoplasma pneumoniae - Epidemiology", "subtopic": "pneumonia_atypical", "content": "Mycoplasma pneumoniae: atypical bacterium (no cell wall), community-acquired, endemic (seasonal peaks fall/winter). Most common cause of atypical pneumonia. Spreads via respiratory droplets. Incubation 1-3 weeks (longer than bacterial CAP). Often affects young adults and children. Epidemics every 4-7 years. Can be mild self-limited disease to moderate pneumonia. Complications: myositis, myocarditis, neurologic (Guillain-Barré, encephalitis), hemolysis, cold agglutinin disease.", "tags": ["pneumonia", "mycoplasma", "epidemiology"], "library": "intern_year_medicine"},
    {"topic": "Mycoplasma - Clinical Presentation and Diagnosis", "subtopic": "pneumonia_atypical", "content": "Mycoplasma: subacute onset (cough starts dry, may become productive), fever low-grade, systemic symptoms (headache, myalgias, malaise). CXR: interstitial infiltrates, often patchy, bilateral (can look like viral). Normal WBC or mild leukocytosis. Diagnosis: culture difficult/slow (requires special media, 2-3 weeks); serology (fourfold rise in acute/convalescent antibodies), cold agglutinin (>1:64 suggestive), PCR/serology testing (varies by lab). Gram stain negative (no cell wall).", "tags": ["pneumonia", "mycoplasma", "diagnosis"], "library": "intern_year_medicine"},
    {"topic": "Mycoplasma - Treatment and Complications", "subtopic": "pneumonia_atypical", "content": "Mycoplasma treatment: macrolide (azithromycin preferred) or fluoroquinolone or doxycycline (100mg BID x 7-14 days). Mild disease often self-limited; treat to shorten duration and prevent complications. Beta-lactams ineffective (no cell wall target). Duration: 7-10 days typical. Neurologic complications (Guillain-Barré, meningoencephalitis): more supportive care needed, steroids in some cases. Cold agglutinin disease (hemolysis): manage transfusions carefully (warm patient, avoid cold exposure). Myocarditis: monitor troponin, ECG, echo if symptomatic.", "tags": ["pneumonia", "mycoplasma", "treatment"], "library": "intern_year_medicine"},

    # HEALTHCARE-ASSOCIATED PNEUMONIA (HAP, VAP) (8 units)
    {"topic": "Hospital-Acquired Pneumonia (HAP) - Definition and Epidemiology", "subtopic": "pneumonia_hap", "content": "HAP = pneumonia occurring ≥48 hours after hospital admission in non-intubated patient. VAP (ventilator-associated pneumonia) = pneumonia in mechanically ventilated patient (typically ≥48h after intubation, sometimes <48h included if predisposed). HCAP (healthcare-associated CAP) = pneumonia in non-hospitalized but exposed to healthcare (nursing home, dialysis, chemotherapy, prolonged antibiotics, family member with resistant organism). All have higher mortality (15-20% for HAP, 25-50% for VAP) than CAP due to resistant organisms.", "tags": ["pneumonia", "hap", "vap", "epidemiology"], "library": "intern_year_medicine"},
    {"topic": "HAP/VAP - Pathogenic Organisms", "subtopic": "pneumonia_hap", "content": "HAP/VAP organisms: multidrug-resistant gram-negatives (Pseudomonas aeruginosa, Acinetobacter, extended-spectrum beta-lactamase [ESBL] Enterobacteriaceae), methicillin-resistant Staph aureus (MRSA), anaerobes, fungi (Candida if prolonged hospitalization/antibiotics). Risk factors for resistant organisms: prior antibiotics, prolonged hospitalization, ICU stay, mechanical ventilation, underlying disease severity. 50-80% of VAP due to gram-negative rods. Cultures (sputum, BAL, protected brush) guide therapy.", "tags": ["pneumonia", "hap", "microbiology"], "library": "intern_year_medicine"},
    {"topic": "VAP - Diagnosis and Confirmation", "subtopic": "pneumonia_hap", "content": "VAP suspected when: fever, leukocytosis, increased sputum production, worsening oxygenation, new infiltrate on CXR (though infiltrates common in ICU, etiology often unclear). Clinical VAP diagnosis imprecise (sensitivity only 60-80%, specificity 60-70%). Quantitative cultures (BAL >10^4 CFU/mL, PSB >10^3 CFU/mL) more specific but invasive. Routine sputum cultures poor discriminator (colonization vs infection). Procalcitonin elevation supports bacterial etiology. Consider non-infectious causes (aspiration, pulmonary edema, ARDS, atelectasis, PE).", "tags": ["pneumonia", "vap", "diagnosis"], "library": "intern_year_medicine"},
    {"topic": "VAP - Prevention Strategies (Bundle Approach)", "subtopic": "pneumonia_prevention", "content": "VAP prevention bundle: head-of-bed elevation ≥30 degrees, oral care with chlorhexidine, spontaneous breathing trial daily (assess extubation readiness), DVT prophylaxis, stress ulcer prophylaxis, avoid gastric distension, subglottic secretion drainage (special tubes), early ambulation/mobilization. Selective decontamination of digestive tract (SDD) with antibiotics controversial (reduces VAP but may increase resistance). Bundle approach reduces VAP incidence by 30-50%.", "tags": ["pneumonia", "vap", "prevention"], "library": "intern_year_medicine"},
    {"topic": "HAP/VAP - Empiric Antibiotic Therapy", "subtopic": "pneumonia_treatment", "content": "HAP/VAP empiric therapy (pending cultures): broad coverage needed for resistant gram-negatives. Typical regimen: antipseudomonal beta-lactam (piperacillin-tazobactam 4.5g IV q6h, cefepime 1-2g IV q12h, meropenem 1g IV q8h) + fluoroquinolone (levofloxacin 750mg IV daily) OR aminoglycoside (amikacin, tobramycin; dosed once daily, levels monitored). Add vancomycin (15-20 mg/kg IV q8-12h, trough 15-20) if MRSA risk or beta-lactam allergy.", "tags": ["pneumonia", "hap", "antibiotics"], "library": "intern_year_medicine"},
    {"topic": "HAP/VAP - De-escalation and Duration", "subtopic": "pneumonia_treatment", "content": "VAP management: empiric broad therapy, then de-escalate based on cultures/sensitivities within 48-72 hours. Duration: 7-8 days for VAP (non-fermenting gram-negatives like Pseudomonas may benefit from longer courses if slow improvement). HAP: 7 days typical. Document clinical improvement before stopping: resolution of fever, decreasing sputum, improving oxygenation, stabilizing WBC. Longer therapy (14+ days) associated with increased resistance, Clostridioides difficile, candidiasis without mortality benefit.", "tags": ["pneumonia", "hap", "antibiotics", "stewardship"], "library": "intern_year_medicine"},
    {"topic": "VAP - Weaning and Extubation", "subtopic": "pneumonia_management", "content": "VAP management includes aggressive weaning/extubation: daily spontaneous breathing trials (pressure support 7-8 cmH2O, PEEP 5, T-piece trials), assess readiness criteria (adequate oxygenation FiO2 ≤0.40-0.50, PEEP ≤5-8, respiratory rate <35, negative inspiratory force <-20, no sedation). Delay in weaning increases VAP risk, morbidity, mortality. Minimize sedation (daily sedation interruption), mobilization as tolerated. Reintubation risk 10-20%; assess swallow, mental status before extubation.", "tags": ["pneumonia", "vap", "weaning"], "library": "intern_year_medicine"},

    # COMPLICATIONS OF PNEUMONIA (8 units)
    {"topic": "CAP Complications - Sepsis and Septic Shock", "subtopic": "pneumonia_complications", "content": "CAP can progress to sepsis (infection + SIRS: fever/hypothermia, tachycardia, tachypnea, leukocytosis/leukopenia) and septic shock (hypotension requiring vasopressors, end-organ dysfunction, lactate >2). Mortality 20-40% with sepsis, 40-60% with septic shock. Pneumococcal CAP particularly at risk. Management: early recognition, broad antibiotics (<1 hour), fluid resuscitation (30 mL/kg crystalloid), vasopressors (norepinephrine first-line), lactate clearance, source control (consider drainage if indicated).", "tags": ["pneumonia", "complications", "sepsis", "high_yield"], "library": "intern_year_medicine"},
    {"topic": "CAP Complications - Empyema", "subtopic": "pneumonia_complications", "content": "Empyema = pus in pleural space (bacterial pneumonia with effusion). Incidence 5-10% of hospitalized CAP. Presents with prolonged fever despite antibiotics, pleuritic pain, dyspnea. Diagnosis: pleural fluid with pH <7.0, glucose <60, LDH >1000, positive culture, or Gram stain positive. Requires drainage: chest tube/pigtail catheter, or VATS (video-assisted thoracoscopic surgery) if loculated/thick. Antibiotics alone insufficient. Complications: failure to drain = bronchopleural fistula, septic shock, chronic drainage.", "tags": ["pneumonia", "complications", "empyema"], "library": "intern_year_medicine"},
    {"topic": "CAP Complications - Acute Respiratory Distress Syndrome (ARDS)", "subtopic": "pneumonia_complications", "content": "ARDS = bilateral infiltrates, PaO2/FiO2 ratio <300, no evidence of hydrostatic pulmonary edema. Pneumonia (bacterial and viral) is leading cause of ARDS. Pathophysiology: increased capillary permeability, alveolar inflammation, surfactant dysfunction. Mortality 25-50% depending on severity. Management: lung-protective ventilation (low tidal volumes 6-8 mL/kg, permissive hypercapnia, PEEP optimization), proning if severe, fluid restriction after initial resuscitation. Prone positioning reduces mortality if P/F ratio <100 and early treatment.", "tags": ["pneumonia", "complications", "ards"], "library": "intern_year_medicine"},
    {"topic": "CAP Complications - Pneumothorax", "subtopic": "pneumonia_complications", "content": "Spontaneous pneumothorax can occur with bacterial pneumonia (especially staphylococcal, pneumococcal, pneumatosis formation). Presents with acute dyspnea, pleuritic chest pain, hypoxia. Diagnosis: CXR or CT shows collapsed lung, pleural line. Small <2cm at hilum, asymptomatic: observation + supplemental oxygen. Moderate-large or symptomatic: chest tube (pigtail catheter often preferred). Persistent air leak: evaluate for bronchopleural fistula (high-resolution CT). VATS if recurrent or persistent.", "tags": ["pneumonia", "complications", "pneumothorax"], "library": "intern_year_medicine"},
    {"topic": "CAP Complications - Parapneumonic Effusion", "subtopic": "pneumonia_complications", "content": "Parapneumonic effusion = pleural fluid with bacterial CAP but sterile (not empyema). Incidence 20-40% of hospitalized CAP. Fluid characteristics: pH 7.0-7.20, glucose >60, LDH variable, negative cultures. Uncomplicated effusions: usually resolve with antibiotic therapy, no drainage needed. Complicated: pH <7.0, glucose <60, high LDH (risk of progression to empyema); consider drainage if recurrent fevers despite antibiotics. Serial ultrasound/CT to monitor evolution.", "tags": ["pneumonia", "complications", "effusion"], "library": "intern_year_medicine"},
    {"topic": "CAP Complications - Metastatic Infection", "subtopic": "pneumonia_complications", "content": "Hematogenous spread from pneumonia can cause: meningitis (especially pneumococcal, 5-10% of bacteremia), endocarditis (especially if prosthetic valve, IVDU, Group A Streptococcus), septic arthritis, osteomyelitis, brain abscess, splenic/renal infarcts. Signs: persistent fever despite appropriate antibiotics, new cardiac murmur, neck stiffness, focal neurologic deficits. Diagnosis: blood cultures (already drawn), CSF if meningitis suspected, echo if endocarditis, MRI if abscess. Management: longer antibiotic courses (2-4 weeks), imaging, sometimes surgical intervention.", "tags": ["pneumonia", "complications", "metastatic"], "library": "intern_year_medicine"},
    {"topic": "CAP Complications - Myocarditis and Pericarditis", "subtopic": "pneumonia_complications", "content": "Viral pneumonia (influenza, parainfluenza, COVID-19, myocarditis viruses) can cause myocarditis/pericarditis. Bacterial pneumonia less common but can cause postpericardial/post-pneumonic state. Myocarditis: elevated troponin, decreased ejection fraction on echo, arrhythmias, cardiogenic shock. Pericarditis: pleuritic chest pain, friction rub, ECG PR depression, tamponade risk. Management: cardiac monitoring, troponin/BNP, echo, supportive care. Pericardiocentesis if tamponade. Steroids sometimes considered for viral myocarditis (controversial).", "tags": ["pneumonia", "complications", "cardiac"], "library": "intern_year_medicine"},
    {"topic": "CAP Complications - Lung Abscess", "subtopic": "pneumonia_complications", "content": "Lung abscess = localized collection of pus (necrotic lung tissue) due to pneumonia. Risk: aspiration, anaerobic organisms, poor dentition, alcoholism, immunosuppression. Presents with persistent fever, productive cough (sometimes foul-smelling), weight loss. CXR: cavitary lesion with air-fluid level (classic). Diagnosis: CT chest confirms abscess. Cultures: sputum, BAL (anaerobes need special handling). Treatment: prolonged antibiotics (anaerobic coverage: penicillin V + clindamycin, or amoxicillin-clavulanate, or piperacillin-tazobactam), x 2-4 weeks. Percutaneous drainage if large (>4-5cm), non-responsive to antibiotics. Rarely surgical resection.", "tags": ["pneumonia", "complications", "abscess"], "library": "intern_year_medicine"},

    # IMMUNOCOMPROMISED HOST PNEUMONIA (5 units)
    {"topic": "PCP (Pneumocystis jirovecii Pneumonia) - Risk Factors and Presentation", "subtopic": "pneumonia_immunocompromised", "content": "PCP: fungal infection (formerly Pneumocystis carinii). Risk: CD4 <200 cells/μL (AIDS), solid organ transplant, prolonged corticosteroids (>20mg prednisone x >1 month), certain immunosuppressants (TNF-alpha inhibitors, JAK inhibitors). Presentation: subacute (1-4 weeks) dyspnea, dry cough, fever, chest pain. Exam: tachypnea, hypoxia, normal lung sounds initially (later crackles). CXR: bilateral interstitial infiltrates, can be normal early (15-20% of cases). ABG shows hypoxia with large A-a gradient.", "tags": ["pneumonia", "pcp", "hiv"], "library": "intern_year_medicine"},
    {"topic": "PCP - Diagnosis and Treatment", "subtopic": "pneumonia_immunocompromised", "content": "PCP diagnosis: induced sputum (cough induction with hypertonic saline), BAL with DFA stain (polychrome methylene silver or immunofluorescence), PCR testing (most sensitive). Chest imaging: CXR may be normal; CT shows ground-glass opacities. Treatment: TMP-SMX (trimethoprim-sulfamethoxazole) 15mg/kg TMP IV/PO q6h x 14-21 days (first-line). Alternatives: pentamidine, clindamycin + primaquine, atovaquone. Steroids added if PaO2 <70 or A-a gradient >35 (reduces mortality). Prophylaxis: TMP-SMX daily if CD4 <200 (can discontinue if CD4 >200 x 3 months on ART).", "tags": ["pneumonia", "pcp", "treatment"], "library": "intern_year_medicine"},
    {"topic": "CAP in HIV/AIDS - Approach and Opportunistic Infections", "subtopic": "pneumonia_immunocompromised", "content": "Pneumonia in HIV varies by CD4 count: CD4 >200: bacterial CAP similar to immunocompetent. CD4 100-200: PCP, Cryptococcus, TB coinfection increased. CD4 <50: CMV, Mycobacterium avium (MAC), fungal (Histoplasma, Coccidioides). Diagnosis approach: CXR, sputum culture, consider PCR for common organisms, bronchoscopy if CD4 <100 or atypical presentation. Empiric therapy depends on CD4; include TMP-SMX and fluoroquinolone if CD4 <200. Antiretroviral therapy (ART) critical to immune reconstitution; must be managed carefully with IRIS (immune reconstitution inflammatory syndrome).", "tags": ["pneumonia", "hiv", "opportunistic"], "library": "intern_year_medicine"},
    {"topic": "Cytomegalovirus (CMV) Pneumonia", "subtopic": "pneumonia_immunocompromised", "content": "CMV pneumonitis: risk if CD4 <50 or other severe immunosuppression (transplant, high-dose steroids). Presents with dyspnea, hypoxia (often severe, hypoxemia disproportionate to infiltrate), low-grade fever. CXR: diffuse interstitial infiltrates, can appear normal. Diagnosis: CMV PCR blood (high viral load suggests disease), BAL with CMV culture or PCR, histology (inclusion bodies). Difficult to diagnose; high suspicion needed. Treatment: ganciclovir or valganciclovir for 2+ weeks. Cidofovir if ganciclovir-resistant. Mortality high (40-90%) if untreated.", "tags": ["pneumonia", "cmv", "immunocompromised"], "library": "intern_year_medicine"},
    {"topic": "Immunocompromised Host - Prophylaxis Strategies", "subtopic": "pneumonia_prevention", "content": "Opportunistic infection prophylaxis guided by CD4 count: CD4 <200: TMP-SMX (covers PCP, Toxoplasma, some bacteria). CD4 <100: also consider azithromycin (MAC prophylaxis). CD4 <50: also ganciclovir or valganciclovir (CMV). Non-HIV immunocompromised (transplant, TNF inhibitors): TB prophylaxis if LTBI, fungal prophylaxis per risk. Vaccination crucial: PCV13/PPSV23 (if CD4 >200), influenza annual, COVID-19. ART initiation (CD4 <50 recommended urgent). Monitor CD4 recovery on ART; prophylaxis often discontinued when CD4 >200-250 x 3 months.", "tags": ["pneumonia", "prophylaxis", "prevention"], "library": "intern_year_medicine"},

    # ANTIMICROBIAL STEWARDSHIP IN PNEUMONIA (6 units)
    {"topic": "Antibiotic Stewardship - Core Principles in Pneumonia", "subtopic": "pneumonia_stewardship", "content": "Core principles: (1) optimize empiric therapy (narrow when culture results available), (2) avoid unnecessarily broad agents (fluoroquinolones only when indicated, avoid double coverage), (3) shorten duration (5-7 days CAP, 7-8 days VAP, not 10-14 days), (4) switch IV to PO early (oral bioavailability good for many agents), (5) avoid combination therapy unless needed (monotherapy when possible), (6) use local antibiograms to guide empiric choices. Goal: reduce C. difficile, resistance, side effects, costs while maintaining clinical outcomes.", "tags": ["pneumonia", "stewardship", "high_yield"], "library": "intern_year_medicine"},
    {"topic": "De-escalation - From Broad to Narrow Therapy", "subtopic": "pneumonia_stewardship", "content": "De-escalation strategy: (1) start broad empiric therapy based on risk factors, (2) obtain cultures before antibiotics if possible, (3) reassess at 48-72 hours with culture results, (4) narrow therapy to cover identified pathogen(s), (5) discontinue redundant agents, (6) switch broad agents to narrow ones (fluoroquinolone to amoxicillin if susceptible pneumococcus). Example: start piperacillin-tazobactam for VAP, culture shows H. influenzae susceptible to ceftriaxone, de-escalate to ceftriaxone monotherapy. Improves outcomes by reducing toxicity, cost, resistance.", "tags": ["pneumonia", "stewardship", "de_escalation"], "library": "intern_year_medicine"},
    {"topic": "Monotherapy vs Combination Therapy", "subtopic": "pneumonia_stewardship", "content": "Monotherapy preferred when possible (fewer pills, fewer side effects, lower cost). Fluoroquinolone monotherapy adequate for outpatient CAP (covers typical + atypical). Combination (beta-lactam + macrolide) justified if: severe CAP, ICU admission, shock, need atypical coverage, or local resistance patterns suggest combination benefit. VAP often requires combination (broad gram-negative coverage + MRSA if risk). De-escalate to monotherapy once culture shows susceptible pathogen. Avoid unnecessary dual therapy (e.g., two beta-lactams) unless specific indication (inadequate coverage, resistance).", "tags": ["pneumonia", "stewardship", "monotherapy"], "library": "intern_year_medicine"},
    {"topic": "Clinical Stability Criteria and Antibiotic Discontinuation", "subtopic": "pneumonia_stewardship", "content": "Clinical stability (can discontinue or step-down antibiotics when): (1) defervescence ≥24-48 hours, (2) no acute respiratory distress, (3) improved oxygenation, (4) oral intake adequate, (5) WBC normalizing, (6) lactate normalized, (7) hemodynamically stable without vasopressors. Don't wait for: complete CXR clearance (lags clinical improvement), negative follow-up cultures (no benefit), or arbitrary day-5/7. Earlier recognition of stability allows IV-to-PO switch, shorter course, discharge. Premature discontinuation risks relapse; clinical judgment needed.", "tags": ["pneumonia", "stewardship", "discontinuation"], "library": "intern_year_medicine"},
    {"topic": "Fluoroquinolone Use - Appropriate vs Inappropriate", "subtopic": "pneumonia_stewardship", "content": "Fluoroquinolone appropriate: outpatient CAP (monotherapy, no IV access), COPD with risk factors, atypical pneumonia (Legionella, Mycoplasma), mixed infection (beta-lactam + fluoroquinolone, then de-escalate), PCN allergy, GI intolerance to beta-lactams. Inappropriate: routine mild CAP in young patient (amoxicillin sufficient), empiric HAP/VAP if low MRSA/Pseudomonas risk (narrower agent better), prophylaxis (resistance risk). Side effects: Clostridioides difficile, QT prolongation, tendon rupture, neuropathy. Cost higher than beta-lactams. Reserve for indication-driven use. Resistance emerging (especially Pseudomonas).", "tags": ["pneumonia", "stewardship", "fluoroquinolones"], "library": "intern_year_medicine"},
    {"topic": "IV-to-PO Transition and Oral Antibiotic Bioavailability", "subtopic": "pneumonia_stewardship", "content": "Switch IV to PO (oral step-down) when: patient tolerating oral intake, able to absorb medications (no vomiting), adequate oral bioavailability of chosen agent, clinical improvement trend. Agents with good oral bioavailability: fluoroquinolones (levofloxacin 750mg PO = IV equivalent), macrolides (azithromycin), doxycycline, amoxicillin/clavulanate. Switch timing: 2-3 days into IV therapy once clinically improving. Benefits: reduced cost, line removal, early discharge, less nosocomial infection risk. Don't delay oral step-down in stable patients; shortens hospitalization without compromising outcomes.", "tags": ["pneumonia", "stewardship", "oral_transition"], "library": "intern_year_medicine"},
]

def main():
    """Generate Phase 2 pneumonia knowledge chunks and write to file."""
    output_dir = Path("C:/Users/Dean/anesthesia_attending/data")
    output_file = output_dir / "phase2_pneumonia_chunks.json"

    output_dir.mkdir(parents=True, exist_ok=True)

    # Add unique IDs and library field
    for idx, unit in enumerate(PHASE2_PNEUMONIA_UNITS):
        unit["id"] = f"phase2_pneumonia_unit_{idx}"
        if "library" not in unit:
            unit["library"] = "intern_year_medicine"
        unit["created_at"] = datetime.now().isoformat()

    # Write to file
    with open(output_file, "w") as f:
        for unit in PHASE2_PNEUMONIA_UNITS:
            f.write(json.dumps(unit) + "\n")

    print(f"Generated {len(PHASE2_PNEUMONIA_UNITS)} pneumonia knowledge units")
    print(f"Output: {output_file}")
    return len(PHASE2_PNEUMONIA_UNITS)

if __name__ == "__main__":
    main()
