#!/usr/bin/env python3
"""Phase 2 Thyroid knowledge base: hypo/hyperthyroidism, thyroid disease."""
import json
from datetime import datetime
from pathlib import Path

PHASE2_THYROID_UNITS = [
    {"topic": "Thyroid Physiology - TSH, T3, T4, Reverse T3", "subtopic": "thyroid_basics", "content": "TSH (thyroid-stimulating hormone): pituitary hormone stimulating thyroid hormone production. Feedback: low T4 -> high TSH (stimulates production); high T4 -> low TSH (suppresses). T4 (thyroxine): inactive precursor, 99% protein-bound, half-life 7 days. T3 (triiodothyronine): active hormone, faster-acting, converted from T4 peripherally. Reverse T3: inactive metabolite, increased in illness/stress. Free T4/T3: unbound, biologically active (preferred to measure). TSH most sensitive screening test for dysfunction. Normal TSH 0.4-4 mIU/L; reference ranges vary by lab.", "tags": ["thyroid", "physiology"], "library": "intern_year_medicine"},
    {"topic": "TSH as Screening Test - Strengths and Limitations", "subtopic": "thyroid_diagnosis", "content": "TSH advantages: most sensitive for primary hypo/hyperthyroidism, inexpensive, standard screening. First-line test for suspected thyroid disease. Limitations: (1) central hypo/hyperthyroidism (pituitary/hypothalamus disease) = normal TSH despite abnormal free T4 (rare). (2) Acute illness suppresses TSH (euthyroid sick syndrome). (3) Pregnancy, medications (estrogens, dopamine agonists, amiodarone) affect interpretation. (4) Population variation: 10-15% outside standard range without disease. Recommendation: check free T4 if TSH abnormal to confirm clinical significance.", "tags": ["thyroid", "diagnosis"], "library": "intern_year_medicine"},
    {"topic": "Hypothyroidism - Hashimoto's and Iodine Deficiency", "subtopic": "thyroid_hypothyroid", "content": "Hypothyroidism: elevated TSH, low free T4 (primary). Causes: Hashimoto thyroiditis (90% developed countries, autoimmune, anti-TPO/anti-thyroglobulin antibodies), iodine deficiency (worldwide leading cause of preventable hypothyroidism), medications (amiodarone, lithium, interferon), central causes (pituitary, hypothalamus). Hashimoto: slow progressive destruction, women >men, genetic predisposition. Iodine deficiency: endemic goiter, cretinism if severe in pregnancy. Presentation: fatigue, cold intolerance, weight gain, bradycardia, constipation, myxedema (skin thickening/puffiness), depression. Diagnosis: elevated TSH, low free T4 (low TSH = central hypo).", "tags": ["thyroid", "hypothyroid", "hashimoto"], "library": "intern_year_medicine"},
    {"topic": "Hypothyroidism Treatment - Levothyroxine Dosing and Monitoring", "subtopic": "thyroid_treatment", "content": "Levothyroxine (synthetic T4): first-line treatment for hypothyroidism. Dosing: 1.6 mcg/kg daily (usually 25-200 mcg depending on baseline TSH/body weight). Start low (25-50 mcg), increase by 25-50 mcg every 4-6 weeks until euthyroid. Take on empty stomach (fasting absorption best, 30-60 min before food/supplements). Recheck TSH 6-8 weeks after dose change (steady state takes 4-6 weeks due to long half-life). Titrate to TSH 0.5-2.5 mIU/L (target patient-specific: lower in post-thyroidectomy/thyroid cancer, elderly prefer TSH 1-3). Monitor annually once stable.", "tags": ["thyroid", "treatment"], "library": "intern_year_medicine"},
    {"topic": "Levothyroxine - Drug Interactions and Bioavailability Issues", "subtopic": "thyroid_treatment", "content": "Levothyroxine interactions: calcium (dairy, supplements), iron (ferrous sulfate), magnesium, aluminum hydroxide (antacids), proton pump inhibitors all decrease absorption (space dosing by 4+ hours). Estrogens (oral contraceptives, HRT) increase clearance; may need higher levothyroxine dose. Amiodarone, salicylates, anticonvulsants affect binding/metabolism. Switching brands: maintain same manufacturer if possible (bioequivalence varies slightly). Adequate dosing indicated by: TSH at goal, symptoms resolved (energy, weight stable, normal temperature), normal heart rate. Over-treatment risks: atrial fibrillation, osteoporosis, cardiac events (especially elderly/cardiac disease).", "tags": ["thyroid", "treatment"], "library": "intern_year_medicine"},
    {"topic": "Hyperthyroidism - Graves Disease and Toxic Nodule", "subtopic": "thyroid_hyperthyroid", "content": "Hyperthyroidism: low TSH, high free T4 (primary). Causes: Graves disease (autoimmune, 70% cases, TSI antibodies), toxic adenoma/multinodular goiter (10-15%), thyroiditis (viral, postpartum, drug-induced), drugs (iodine excess, amiodarone). Graves: women >men, genetic predisposition, associated ophthalmopathy (exophthalmos, diplopia), dermopathy (pretibial myxedema). Presentation: heat intolerance, anxiety, palpitations, weight loss, tremor, hyperdefecation, thyroid bruit (Graves), stare/lid lag. Diagnosis: low TSH, elevated free T4, elevated free T3 (often). TSI antibodies confirm Graves.", "tags": ["thyroid", "hyperthyroid", "graves"], "library": "intern_year_medicine"},
    {"topic": "Thyroid Storm - Life-Threatening Emergency", "subtopic": "thyroid_complications", "content": "Thyroid storm: decompensated hyperthyroidism, mortality 1-5% even treated, >25% if untreated. Triggers: inadequate antithyroid treatment, infection, surgery/anesthesia in untreated hyperthyroid. Presentation: fever (often high, >38.5C), tachycardia (often >140), atrial fibrillation, altered mental status, thyroid enlargement, GI symptoms (diarrhea, nausea), jaundice, hepatomegaly. Pathophysiology: excess thyroid hormone causing sympathomimetic toxicity, altered TH metabolism. Management: urgent hospitalization, beta-blockers (propranolol 40-80 mg q6h, reduces symptoms + T4->T3 conversion), PTU 150-200 mg q6h (preferred over methimazole in crisis for toxicity profile), Lugol's solution or SSKI 1-2 drops q6-8h (blocks T4 release, start after PTU 1 hour to prevent thyroid hormone synthesis worsening).", "tags": ["thyroid", "thyroid_storm", "high_yield"], "library": "intern_year_medicine"},
    {"topic": "PTU vs Methimazole - Dosing and Toxicity Profile", "subtopic": "thyroid_treatment", "content": "PTU (propylthiouracil): blocks thyroid peroxidase (TPO), reduces T4/T3 synthesis + inhibits T4->T3 conversion (faster symptom improvement). Dosing: 50-100 mg TID (start), taper to 25-50 mg TID maintenance. Risk: hepatotoxicity (0.1-0.3%, can be fulminant), agranulocytosis (rare), rash. Preferred in first trimester pregnancy (crosses placenta less), thyroid storm (faster T4->T3 inhibition). Methimazole: blocks TPO, T4/T3 synthesis only. Dosing: 5-20 mg daily. Risk: agranulocytosis (0.3%), rash, arthralgia. Preferred first-line (once-daily dosing, lower hepatotoxicity). Pregnancy: PTU first trimester, switch methimazole second/third trimester (PTU hepatotoxicity risk, methimazole embryopathy rare). Monitor: CBC baseline, LFTs baseline, repeat if fever/infection/jaundice.", "tags": ["thyroid", "treatment"], "library": "intern_year_medicine"},
    {"topic": "Beta-Blockers for Symptom Control in Hyperthyroidism", "subtopic": "thyroid_treatment", "content": "Beta-blockers (propranolol, atenolol, metoprolol): treat adrenergic symptoms (palpitations, tremor, anxiety) WITHOUT affecting thyroid hormone production. Used while waiting for PTU/methimazole or radioactive iodine to take effect (weeks). Propranolol preferred (also blocks T4->T3 conversion, reducing hormone activation). Dosing: propranolol 40-120 mg daily (TID-QID), target HR 60-80. Continue during antithyroid treatment until euthyroid (TSH normalized). Monitor: HR, symptoms, hypoglycemia risk (beta-blockers mask). Not sufficient monotherapy; must combine with PTU/methimazole or radioactive iodine for definitive treatment.", "tags": ["thyroid", "treatment"], "library": "intern_year_medicine"},
    {"topic": "Radioactive Iodine and Thyroidectomy - Definitive Treatment Options", "subtopic": "thyroid_treatment", "content": "Radioactive iodine (I-131): sodium iodide oral, accumulates in thyroid, destroys hyperactive tissue. Advantages: outpatient, definitive, single dose. Disadvantages: delayed effect (4-12 weeks to euthyroid), radiation exposure (low, contraindicated in pregnancy/breastfeeding), hypothyroidism develops in 80% over lifetime (requires levothyroxine replacement). Pregnancy/lactation absolute contraindication. Thyroidectomy: surgical ablation of thyroid. Advantages: immediate definitive cure, option if Graves ophthalmopathy (may worsen post-I131). Disadvantages: perioperative risk, laryngeal nerve injury (voice/breathing), hypoparathyroidism. Pretreated with PTU/methimazole + beta-blockers + iodine solution (Lugol's) x 7-10 days pre-op to reduce bleeding/thyroid storm risk.", "tags": ["thyroid", "treatment"], "library": "intern_year_medicine"},
    {"topic": "Thyroiditis - Viral, Autoimmune, Drug-Induced", "subtopic": "thyroid_inflammation", "content": "Thyroiditis: inflammation of thyroid gland, various etiologies. Viral (subacute): self-limited, follows viral URI, presents with thyroid pain, hyperthyroidism phase (T4 release) -> hypothyroid phase (recovery), 3-6 months course. Autoimmune (Hashimoto): progressive destruction (covered under hypothyroidism). Postpartum thyroiditis: autoimmune flare postpartum, 5-10% women, mild hyperthyroid phase then hypothyroid phase, usually self-limited but some develop permanent hypothyroidism. Drug-induced: amiodarone, interferon, checkpoint inhibitors, lithium. Diagnosis: RAIU (radioactive iodine uptake) low in thyroiditis (no uptake/release), high in Graves (active synthesis). Treatment: supportive in viral (NSAIDs, beta-blockers), levothyroxine if hypothyroid phase prolonged.", "tags": ["thyroid", "thyroiditis"], "library": "intern_year_medicine"},
    {"topic": "Postpartum Thyroiditis - Natural History and Management", "subtopic": "thyroid_special", "content": "Postpartum thyroiditis: autoimmune thyroiditis occurring 3-12 months postpartum. Incidence 5-10% postpartum, higher in women with positive TPO antibodies. Phases: (1) thyrotoxic phase (weeks 1-4 postpartum) - hormone release from damaged thyroid, low TSH, high T4, no iodine uptake. (2) Hypothyroid phase (weeks 4-12) - gland depleted, TSH elevated, low T4, symptoms of hypothyroidism. (3) Recovery phase (weeks 12-52) - most women return to euthyroid but 25% develop permanent hypothyroidism (long-term levothyroxine). Management: reassurance in mild thyrotoxic phase, beta-blockers if symptomatic, levothyroxine during hypothyroid phase, taper levothyroxine if recovering (not all need permanent therapy). Breastfeeding safe with levothyroxine (minimal excretion). Monitor TSH 6-12 weeks postpartum, yearly thereafter.", "tags": ["thyroid", "postpartum"], "library": "intern_year_medicine"},
    {"topic": "Thyroid Nodules and Cancer Screening", "subtopic": "thyroid_nodules", "content": "Thyroid nodules: palpable in 5% population, incidental ultrasound findings 16-67% (increased detection). Cancer risk 5-15% of nodules. Worrisome features: hard, fixed, rapid growth, associated lymphadenopathy, dysphagia, dysphonia (recurrent laryngeal nerve involvement), hyperfunctioning (low TSH, high uptake = Plummer's disease, benign but functional). Diagnosis: TSH first (suppress cancer likelihood), then ultrasound (characterize nodule), FNA (fine-needle aspiration) if concerning features or >1cm. Bethesda classification guides management. Management: follow-up ultrasound if benign features, surgery if malignant/suspicious, levothyroxine suppression therapy post-thyroidectomy (suppress TSH <0.5 to inhibit cancer cell growth).", "tags": ["thyroid", "nodules", "cancer"], "library": "intern_year_medicine"},
    {"topic": "Thyroid Antibodies and Autoimmune Thyroid Disease", "subtopic": "thyroid_diagnosis", "content": "TPO (thyroid peroxidase) antibodies: present in Hashimoto, Graves, may predict future hypothyroidism (30% positive TPO without overt disease). Thyroglobulin antibodies: often coexist with TPO, associated with autoimmune thyroid disease. TSI (thyroid-stimulating immunoglobulin): specific for Graves disease, activates TSH receptors. TSH receptor antibodies (TRAb): alternative to TSI, confirms Graves. Use: TPO/thyroglobulin antibodies help diagnosis of autoimmune hypothyroidism; TSI/TRAb confirm Graves (important differentiation from other causes hyperthyroidism). Positive antibodies without dysfunction: may monitor for future disease but no treatment unless TSH abnormal.", "tags": ["thyroid", "antibodies"], "library": "intern_year_medicine"},
    {"topic": "Iodine Excess - Jod-Basedow and Wolff-Chaikoff Effect", "subtopic": "thyroid_complications", "content": "Iodine excess sources: iodized salt, seaweed/kelp supplements, amiodarone (high iodine content), radiographic contrast, iodine-containing antiseptics. Acute iodine excess: Wolff-Chaikoff effect (TSH decreases, T4/T3 decrease transiently, self-limited as adaptation occurs). Jod-Basedow phenomenon: hyperthyroidism precipitated by sudden iodine excess in iodine-deficient areas or underlying thyroid disease (Graves, nodule). Amiodarone: high iodine content (75 mg elemental iodine per 200 mg tablet) causes iodine-induced hypothyroidism (10%) or hyperthyroidism (5%, types I and II). Management: evaluate for underlying disease (Graves +/- previous amiodarone = discontinue amiodarone; replace with beta-blockers/antiarrhythmic); if Jod-Basedow with Graves, treat with PTU/methimazole. Kelp supplements: counsel against (iodine content unpredictable, risk thyroid dysfunction).", "tags": ["thyroid", "iodine"], "library": "intern_year_medicine"},
    {"topic": "Amiodarone-Induced Thyroid Dysfunction", "subtopic": "thyroid_complications", "content": "Amiodarone (antiarrhythmic): contains high iodine, causes hypo/hyperthyroidism, abnormal TFTs even without overt dysfunction. Hypothyroidism (10% patients): Wolff-Chaikoff effect in predisposed individuals, risk if iodine deficiency, autoimmune thyroiditis history. Hyperthyroidism Type I (5%): iodine excess in underlying Graves or nodule (Jod-Basedow). Hyperthyroidism Type II (5%): thyroiditis with hormone release (different mechanism). Thyroiditis (amiodarone direct toxicity). Monitoring: TSH + free T4 baseline, at 6 months, then annually. Symptomatic: hypothyroidism = levothyroxine, continue amiodarone (usually outweighs benefit). Hyperthyroidism = challenging; PTU/methimazole less effective (need PTU >300mg for iodine excess), beta-blockers for symptom control, possible amiodarone discontinuation if possible (dangerous for arrhythmia).", "tags": ["thyroid", "amiodarone"], "library": "intern_year_medicine"},
]

def main():
    output_dir = Path("C:/Users/Dean/anesthesia_attending/data")
    output_file = output_dir / "phase2_thyroid_chunks.json"
    output_dir.mkdir(parents=True, exist_ok=True)

    for idx, unit in enumerate(PHASE2_THYROID_UNITS):
        unit["id"] = f"phase2_thyroid_unit_{idx}"
        if "library" not in unit:
            unit["library"] = "intern_year_medicine"
        unit["created_at"] = datetime.now().isoformat()

    with open(output_file, "w") as f:
        for unit in PHASE2_THYROID_UNITS:
            f.write(json.dumps(unit) + "\n")

    print(f"Generated {len(PHASE2_THYROID_UNITS)} Thyroid knowledge units")
    return len(PHASE2_THYROID_UNITS)

if __name__ == "__main__":
    main()
